//reg_lmac.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_LMAC_H__
#define __JL_REG_LMAC_H__

#include <jl_types.h>

#define LMAC4_BASE                                                                             ((jl_uint32)0x00140C00U)
#define LMAC4_BLOCK_SIZE                                                                       ((jl_uint32)0x00000200U)
#define LMAC3_BASE                                                                             ((jl_uint32)0x00140A00U)
#define LMAC3_BLOCK_SIZE                                                                       ((jl_uint32)0x00000200U)
#define LMAC2_BASE                                                                             ((jl_uint32)0x00140800U)
#define LMAC2_BLOCK_SIZE                                                                       ((jl_uint32)0x00000200U)
#define LMAC1_BASE                                                                             ((jl_uint32)0x00140600U)
#define LMAC1_BLOCK_SIZE                                                                       ((jl_uint32)0x00000200U)
#define LMAC0_BASE                                                                             ((jl_uint32)0x00140400U)
#define LMAC0_BLOCK_SIZE                                                                       ((jl_uint32)0x00000200U)

#define LMAC_MAC_CONFIG                                                                        ((jl_uint32)0x00140400U)
#define LMAC_MAC_CONFIG_NUM                                                                    ((jl_uint32)0x00000001U)
#define LMAC_MAC_CONFIG_ENTRY_SIZE                                                                                  (1)
#define LMAC_MAC_CONFIG_OFFSET_RSVD0                                                                               (31)
#define LMAC_MAC_CONFIG_OFFSET_RSVD0_WIDTH                                                                          (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_PREAMBLE_SIZE                                                                    (0)
#define LMAC_MAC_CONFIG_OFFSET_CFG_PREAMBLE_SIZE_WIDTH                                                              (2)
#define LMAC_MAC_CONFIG_OFFSET_CFG_RECEIVER_ENABLE                                                                  (2)
#define LMAC_MAC_CONFIG_OFFSET_CFG_RECEIVER_ENABLE_WIDTH                                                            (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_TRANSMITTER_ENABLE                                                               (3)
#define LMAC_MAC_CONFIG_OFFSET_CFG_TRANSMITTER_ENABLE_WIDTH                                                         (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DEFERRAL_CHECK                                                                   (4)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DEFERRAL_CHECK_WIDTH                                                             (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_BACK_OFF_LIMIT                                                                   (5)
#define LMAC_MAC_CONFIG_OFFSET_CFG_BACK_OFF_LIMIT_WIDTH                                                             (2)
#define LMAC_MAC_CONFIG_OFFSET_CFG_AUTOMATIC_PAD_CRC_STRIPPING                                                      (7)
#define LMAC_MAC_CONFIG_OFFSET_CFG_AUTOMATIC_PAD_CRC_STRIPPING_WIDTH                                                (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_LINK_UP_DOWN                                                                     (8)
#define LMAC_MAC_CONFIG_OFFSET_CFG_LINK_UP_DOWN_WIDTH                                                               (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DISABLE_RETRY                                                                    (9)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DISABLE_RETRY_WIDTH                                                              (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_CHECKSUM_OFFLOAD                                                                (10)
#define LMAC_MAC_CONFIG_OFFSET_CFG_CHECKSUM_OFFLOAD_WIDTH                                                           (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DUPLEX_MODE                                                                     (11)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DUPLEX_MODE_WIDTH                                                                (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_LOOPBACK_MODE                                                                   (12)
#define LMAC_MAC_CONFIG_OFFSET_CFG_LOOPBACK_MODE_WIDTH                                                              (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DISABLE_RECEIVE_OWN                                                             (13)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DISABLE_RECEIVE_OWN_WIDTH                                                        (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_SPEED                                                                           (14)
#define LMAC_MAC_CONFIG_OFFSET_CFG_SPEED_WIDTH                                                                      (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_PORT_SELECT                                                                     (15)
#define LMAC_MAC_CONFIG_OFFSET_CFG_PORT_SELECT_WIDTH                                                                (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DISABLE_CARRIER_SENSE_DURING_TRANSMISSION                                       (16)
#define LMAC_MAC_CONFIG_OFFSET_CFG_DISABLE_CARRIER_SENSE_DURING_TRANSMISSION_WIDTH                                  (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_INTER_FRAME_GAP                                                                 (17)
#define LMAC_MAC_CONFIG_OFFSET_CFG_INTER_FRAME_GAP_WIDTH                                                            (3)
#define LMAC_MAC_CONFIG_OFFSET_CFG_JUMBO_FRAME_ENABLE                                                              (20)
#define LMAC_MAC_CONFIG_OFFSET_CFG_JUMBO_FRAME_ENABLE_WIDTH                                                         (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_FRAME_BURST_ENABLE                                                              (21)
#define LMAC_MAC_CONFIG_OFFSET_CFG_FRAME_BURST_ENABLE_WIDTH                                                         (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_JABBER_DISABLE                                                                  (22)
#define LMAC_MAC_CONFIG_OFFSET_CFG_JABBER_DISABLE_WIDTH                                                             (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_WATCHDOG_DISABLE                                                                (23)
#define LMAC_MAC_CONFIG_OFFSET_CFG_WATCHDOG_DISABLE_WIDTH                                                           (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_TC                                                                              (24)
#define LMAC_MAC_CONFIG_OFFSET_CFG_TC_WIDTH                                                                         (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_CST                                                                             (25)
#define LMAC_MAC_CONFIG_OFFSET_CFG_CST_WIDTH                                                                        (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_SFTERR                                                                          (26)
#define LMAC_MAC_CONFIG_OFFSET_CFG_SFTERR_WIDTH                                                                     (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_TWOKPE                                                                          (27)
#define LMAC_MAC_CONFIG_OFFSET_CFG_TWOKPE_WIDTH                                                                     (1)
#define LMAC_MAC_CONFIG_OFFSET_CFG_SARC                                                                            (28)
#define LMAC_MAC_CONFIG_OFFSET_CFG_SARC_WIDTH                                                                       (3)
typedef union LMAC_MAC_CONFIG_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_preamble_size:LMAC_MAC_CONFIG_OFFSET_CFG_PREAMBLE_SIZE_WIDTH;                                       //[ 1: 0]
        jl_uint32 cfg_receiver_enable:LMAC_MAC_CONFIG_OFFSET_CFG_RECEIVER_ENABLE_WIDTH;                                   //[ 2: 2]
        jl_uint32 cfg_transmitter_enable:LMAC_MAC_CONFIG_OFFSET_CFG_TRANSMITTER_ENABLE_WIDTH;                             //[ 3: 3]
        jl_uint32 cfg_deferral_check:LMAC_MAC_CONFIG_OFFSET_CFG_DEFERRAL_CHECK_WIDTH;                                     //[ 4: 4]
        jl_uint32 cfg_back_off_limit:LMAC_MAC_CONFIG_OFFSET_CFG_BACK_OFF_LIMIT_WIDTH;                                     //[ 6: 5]
        jl_uint32 cfg_automatic_pad_crc_stripping:LMAC_MAC_CONFIG_OFFSET_CFG_AUTOMATIC_PAD_CRC_STRIPPING_WIDTH;           //[ 7: 7]
        jl_uint32 cfg_link_up_down:LMAC_MAC_CONFIG_OFFSET_CFG_LINK_UP_DOWN_WIDTH;                                         //[ 8: 8]
        jl_uint32 cfg_disable_retry:LMAC_MAC_CONFIG_OFFSET_CFG_DISABLE_RETRY_WIDTH;                                       //[ 9: 9]
        jl_uint32 cfg_checksum_offload:LMAC_MAC_CONFIG_OFFSET_CFG_CHECKSUM_OFFLOAD_WIDTH;                                 //[10:10]
        jl_uint32 cfg_duplex_mode:LMAC_MAC_CONFIG_OFFSET_CFG_DUPLEX_MODE_WIDTH;                                           //[11:11]
        jl_uint32 cfg_loopback_mode:LMAC_MAC_CONFIG_OFFSET_CFG_LOOPBACK_MODE_WIDTH;                                       //[12:12]
        jl_uint32 cfg_disable_receive_own:LMAC_MAC_CONFIG_OFFSET_CFG_DISABLE_RECEIVE_OWN_WIDTH;                           //[13:13]
        jl_uint32 cfg_speed:LMAC_MAC_CONFIG_OFFSET_CFG_SPEED_WIDTH;                                                       //[14:14]
        jl_uint32 cfg_port_select:LMAC_MAC_CONFIG_OFFSET_CFG_PORT_SELECT_WIDTH;                                           //[15:15]
        jl_uint32 cfg_disable_carrier_sense_during_transmission:LMAC_MAC_CONFIG_OFFSET_CFG_DISABLE_CARRIER_SENSE_DURING_TRANSMISSION_WIDTH;  //[16:16]
        jl_uint32 cfg_inter_frame_gap:LMAC_MAC_CONFIG_OFFSET_CFG_INTER_FRAME_GAP_WIDTH;                                   //[19:17]
        jl_uint32 cfg_jumbo_frame_enable:LMAC_MAC_CONFIG_OFFSET_CFG_JUMBO_FRAME_ENABLE_WIDTH;                             //[20:20]
        jl_uint32 cfg_frame_burst_enable:LMAC_MAC_CONFIG_OFFSET_CFG_FRAME_BURST_ENABLE_WIDTH;                             //[21:21]
        jl_uint32 cfg_jabber_disable:LMAC_MAC_CONFIG_OFFSET_CFG_JABBER_DISABLE_WIDTH;                                     //[22:22]
        jl_uint32 cfg_watchdog_disable:LMAC_MAC_CONFIG_OFFSET_CFG_WATCHDOG_DISABLE_WIDTH;                                 //[23:23]
        jl_uint32 cfg_tc:LMAC_MAC_CONFIG_OFFSET_CFG_TC_WIDTH;                                                             //[24:24]
        jl_uint32 cfg_cst:LMAC_MAC_CONFIG_OFFSET_CFG_CST_WIDTH;                                                           //[25:25]
        jl_uint32 cfg_sfterr:LMAC_MAC_CONFIG_OFFSET_CFG_SFTERR_WIDTH;                                                     //[26:26]
        jl_uint32 cfg_twokpe:LMAC_MAC_CONFIG_OFFSET_CFG_TWOKPE_WIDTH;                                                     //[27:27]
        jl_uint32 cfg_sarc:LMAC_MAC_CONFIG_OFFSET_CFG_SARC_WIDTH;                                                         //[30:28]
        jl_uint32 rsvd0:LMAC_MAC_CONFIG_OFFSET_RSVD0_WIDTH;                                                               //[31:31]
    } BF;
    jl_uint32 val[LMAC_MAC_CONFIG_ENTRY_SIZE];
} LMAC_MAC_CONFIG_t;

#define LMAC_MAC_FRAME_FILTER                                                                  ((jl_uint32)0x00140404U)
#define LMAC_MAC_FRAME_FILTER_NUM                                                              ((jl_uint32)0x00000001U)
#define LMAC_MAC_FRAME_FILTER_ENTRY_SIZE                                                                            (1)
#define LMAC_MAC_FRAME_FILTER_OFFSET_CFG_PROMISCUOUS_MODE                                                           (0)
#define LMAC_MAC_FRAME_FILTER_OFFSET_CFG_PROMISCUOUS_MODE_WIDTH                                                     (1)
#define LMAC_MAC_FRAME_FILTER_OFFSET_CFG_MAC_FRAME_FILTER                                                           (1)
#define LMAC_MAC_FRAME_FILTER_OFFSET_CFG_MAC_FRAME_FILTER_WIDTH                                                    (30)
#define LMAC_MAC_FRAME_FILTER_OFFSET_CFG_RECEIVE_ALL                                                               (31)
#define LMAC_MAC_FRAME_FILTER_OFFSET_CFG_RECEIVE_ALL_WIDTH                                                          (1)
typedef union LMAC_MAC_FRAME_FILTER_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_promiscuous_mode:LMAC_MAC_FRAME_FILTER_OFFSET_CFG_PROMISCUOUS_MODE_WIDTH;                           //[ 0: 0]
        jl_uint32 cfg_mac_frame_filter:LMAC_MAC_FRAME_FILTER_OFFSET_CFG_MAC_FRAME_FILTER_WIDTH;                           //[30: 1]
        jl_uint32 cfg_receive_all:LMAC_MAC_FRAME_FILTER_OFFSET_CFG_RECEIVE_ALL_WIDTH;                                     //[31:31]
    } BF;
    jl_uint32 val[LMAC_MAC_FRAME_FILTER_ENTRY_SIZE];
} LMAC_MAC_FRAME_FILTER_t;

#define LMAC_MAC_PAUSE                                                                         ((jl_uint32)0x00140418U)
#define LMAC_MAC_PAUSE_NUM                                                                     ((jl_uint32)0x00000001U)
#define LMAC_MAC_PAUSE_ENTRY_SIZE                                                                                   (1)
#define LMAC_MAC_PAUSE_OFFSET_CFG_SEND_PAUSE                                                                        (0)
#define LMAC_MAC_PAUSE_OFFSET_CFG_SEND_PAUSE_WIDTH                                                                  (1)
#define LMAC_MAC_PAUSE_OFFSET_CFG_TRANSMIT_PAUSE_ENABLE                                                             (1)
#define LMAC_MAC_PAUSE_OFFSET_CFG_TRANSMIT_PAUSE_ENABLE_WIDTH                                                       (1)
#define LMAC_MAC_PAUSE_OFFSET_CFG_RECEIVE_PAUSE_ENABLE                                                              (2)
#define LMAC_MAC_PAUSE_OFFSET_CFG_RECEIVE_PAUSE_ENABLE_WIDTH                                                        (1)
#define LMAC_MAC_PAUSE_OFFSET_CFG_UNICAST_PAUSE_FRAME_DETECT                                                        (3)
#define LMAC_MAC_PAUSE_OFFSET_CFG_UNICAST_PAUSE_FRAME_DETECT_WIDTH                                                  (1)
#define LMAC_MAC_PAUSE_OFFSET_CFG_PAUSE_LOW_THRESHOLD                                                               (4)
#define LMAC_MAC_PAUSE_OFFSET_CFG_PAUSE_LOW_THRESHOLD_WIDTH                                                         (2)
#define LMAC_MAC_PAUSE_OFFSET_RSVD1                                                                                 (6)
#define LMAC_MAC_PAUSE_OFFSET_RSVD1_WIDTH                                                                           (1)
#define LMAC_MAC_PAUSE_OFFSET_CFG_DISABLE_ZERO_QUATA_PAUSE                                                          (7)
#define LMAC_MAC_PAUSE_OFFSET_CFG_DISABLE_ZERO_QUATA_PAUSE_WIDTH                                                    (1)
#define LMAC_MAC_PAUSE_OFFSET_RSVD0                                                                                 (8)
#define LMAC_MAC_PAUSE_OFFSET_RSVD0_WIDTH                                                                           (8)
#define LMAC_MAC_PAUSE_OFFSET_CFG_PAUSE_TIME                                                                       (16)
#define LMAC_MAC_PAUSE_OFFSET_CFG_PAUSE_TIME_WIDTH                                                                 (16)
typedef union LMAC_MAC_PAUSE_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_send_pause:LMAC_MAC_PAUSE_OFFSET_CFG_SEND_PAUSE_WIDTH;                                              //[ 0: 0]
        jl_uint32 cfg_transmit_pause_enable:LMAC_MAC_PAUSE_OFFSET_CFG_TRANSMIT_PAUSE_ENABLE_WIDTH;                        //[ 1: 1]
        jl_uint32 cfg_receive_pause_enable:LMAC_MAC_PAUSE_OFFSET_CFG_RECEIVE_PAUSE_ENABLE_WIDTH;                          //[ 2: 2]
        jl_uint32 cfg_unicast_pause_frame_detect:LMAC_MAC_PAUSE_OFFSET_CFG_UNICAST_PAUSE_FRAME_DETECT_WIDTH;              //[ 3: 3]
        jl_uint32 cfg_pause_low_threshold:LMAC_MAC_PAUSE_OFFSET_CFG_PAUSE_LOW_THRESHOLD_WIDTH;                            //[ 5: 4]
        jl_uint32 rsvd1:LMAC_MAC_PAUSE_OFFSET_RSVD1_WIDTH;                                                                //[ 6: 6]
        jl_uint32 cfg_disable_zero_quata_pause:LMAC_MAC_PAUSE_OFFSET_CFG_DISABLE_ZERO_QUATA_PAUSE_WIDTH;                  //[ 7: 7]
        jl_uint32 rsvd0:LMAC_MAC_PAUSE_OFFSET_RSVD0_WIDTH;                                                                //[15: 8]
        jl_uint32 cfg_pause_time:LMAC_MAC_PAUSE_OFFSET_CFG_PAUSE_TIME_WIDTH;                                              //[31:16]
    } BF;
    jl_uint32 val[LMAC_MAC_PAUSE_ENTRY_SIZE];
} LMAC_MAC_PAUSE_t;

#define LMAC_MAC_VLAN                                                                          ((jl_uint32)0x0014041CU)
#define LMAC_MAC_VLAN_NUM                                                                      ((jl_uint32)0x00000001U)
#define LMAC_MAC_VLAN_ENTRY_SIZE                                                                                    (1)
#define LMAC_MAC_VLAN_OFFSET_RSVD0                                                                                 (20)
#define LMAC_MAC_VLAN_OFFSET_RSVD0_WIDTH                                                                           (12)
#define LMAC_MAC_VLAN_OFFSET_CFG_VLAN_TAG                                                                           (0)
#define LMAC_MAC_VLAN_OFFSET_CFG_VLAN_TAG_WIDTH                                                                    (20)
typedef union LMAC_MAC_VLAN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_vlan_tag:LMAC_MAC_VLAN_OFFSET_CFG_VLAN_TAG_WIDTH;                                                   //[19: 0]
        jl_uint32 rsvd0:LMAC_MAC_VLAN_OFFSET_RSVD0_WIDTH;                                                                 //[31:20]
    } BF;
    jl_uint32 val[LMAC_MAC_VLAN_ENTRY_SIZE];
} LMAC_MAC_VLAN_t;

#define LMAC_MAC_WATCHDOG                                                                      ((jl_uint32)0x001404DCU)
#define LMAC_MAC_WATCHDOG_NUM                                                                  ((jl_uint32)0x00000001U)
#define LMAC_MAC_WATCHDOG_ENTRY_SIZE                                                                                (1)
#define LMAC_MAC_WATCHDOG_OFFSET_RSVD0                                                                             (17)
#define LMAC_MAC_WATCHDOG_OFFSET_RSVD0_WIDTH                                                                       (15)
#define LMAC_MAC_WATCHDOG_OFFSET_CFG_WATCHDOG_TIMEOUT                                                               (0)
#define LMAC_MAC_WATCHDOG_OFFSET_CFG_WATCHDOG_TIMEOUT_WIDTH                                                        (17)
typedef union LMAC_MAC_WATCHDOG_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_watchdog_timeout:LMAC_MAC_WATCHDOG_OFFSET_CFG_WATCHDOG_TIMEOUT_WIDTH;                               //[16: 0]
        jl_uint32 rsvd0:LMAC_MAC_WATCHDOG_OFFSET_RSVD0_WIDTH;                                                             //[31:17]
    } BF;
    jl_uint32 val[LMAC_MAC_WATCHDOG_ENTRY_SIZE];
} LMAC_MAC_WATCHDOG_t;

#endif /* __JL_REG_LMAC_H__ */

