//reg_pmx.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_PMX_H__
#define __JL_REG_PMX_H__

#include <jl_types.h>

#define PMX_BASE                                                                               ((jl_uint32)0x00204000U)
#define PMX_BLOCK_SIZE                                                                         ((jl_uint32)0x00001000U)

#define PMX_PIN_MUX_0                                                                          ((jl_uint32)0x00204000U)
#define PMX_PIN_MUX_0_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_0_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_0_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_0_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_0_OFFSET_CFG_P4_LED2_SEL                                                                        (0)
#define PMX_PIN_MUX_0_OFFSET_CFG_P4_LED2_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P4_LED0_SEL                                                                        (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P4_LED0_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P4_LED1_SEL                                                                        (2)
#define PMX_PIN_MUX_0_OFFSET_CFG_P4_LED1_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P3_LED1_SEL                                                                        (3)
#define PMX_PIN_MUX_0_OFFSET_CFG_P3_LED1_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P3_LED2_SEL                                                                        (4)
#define PMX_PIN_MUX_0_OFFSET_CFG_P3_LED2_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P3_LED0_SEL                                                                        (5)
#define PMX_PIN_MUX_0_OFFSET_CFG_P3_LED0_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P2_LED2_SEL                                                                        (6)
#define PMX_PIN_MUX_0_OFFSET_CFG_P2_LED2_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P2_LED0_P7S_SEL                                                                    (7)
#define PMX_PIN_MUX_0_OFFSET_CFG_P2_LED0_P7S_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P2_LED0_SEL                                                                        (8)
#define PMX_PIN_MUX_0_OFFSET_CFG_P2_LED0_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P2_LED1_SEL                                                                        (9)
#define PMX_PIN_MUX_0_OFFSET_CFG_P2_LED1_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P1_LED2_SEL                                                                       (10)
#define PMX_PIN_MUX_0_OFFSET_CFG_P1_LED2_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P1_LED0_SEL                                                                       (11)
#define PMX_PIN_MUX_0_OFFSET_CFG_P1_LED0_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P1_LED0_P7S_SEL                                                                   (12)
#define PMX_PIN_MUX_0_OFFSET_CFG_P1_LED0_P7S_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P1_LED1_SEL                                                                       (13)
#define PMX_PIN_MUX_0_OFFSET_CFG_P1_LED1_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P0_LED2_SEL                                                                       (14)
#define PMX_PIN_MUX_0_OFFSET_CFG_P0_LED2_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_P0_LED1_SEL                                                                       (15)
#define PMX_PIN_MUX_0_OFFSET_CFG_P0_LED1_SEL_WIDTH                                                                  (1)
typedef union PMX_PIN_MUX_0_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_p4_led2_sel:PMX_PIN_MUX_0_OFFSET_CFG_P4_LED2_SEL_WIDTH;                                             //[ 0: 0]
        jl_uint32 cfg_p4_led0_sel:PMX_PIN_MUX_0_OFFSET_CFG_P4_LED0_SEL_WIDTH;                                             //[ 1: 1]
        jl_uint32 cfg_p4_led1_sel:PMX_PIN_MUX_0_OFFSET_CFG_P4_LED1_SEL_WIDTH;                                             //[ 2: 2]
        jl_uint32 cfg_p3_led1_sel:PMX_PIN_MUX_0_OFFSET_CFG_P3_LED1_SEL_WIDTH;                                             //[ 3: 3]
        jl_uint32 cfg_p3_led2_sel:PMX_PIN_MUX_0_OFFSET_CFG_P3_LED2_SEL_WIDTH;                                             //[ 4: 4]
        jl_uint32 cfg_p3_led0_sel:PMX_PIN_MUX_0_OFFSET_CFG_P3_LED0_SEL_WIDTH;                                             //[ 5: 5]
        jl_uint32 cfg_p2_led2_sel:PMX_PIN_MUX_0_OFFSET_CFG_P2_LED2_SEL_WIDTH;                                             //[ 6: 6]
        jl_uint32 cfg_p2_led0_p7s_sel:PMX_PIN_MUX_0_OFFSET_CFG_P2_LED0_P7S_SEL_WIDTH;                                     //[ 7: 7]
        jl_uint32 cfg_p2_led0_sel:PMX_PIN_MUX_0_OFFSET_CFG_P2_LED0_SEL_WIDTH;                                             //[ 8: 8]
        jl_uint32 cfg_p2_led1_sel:PMX_PIN_MUX_0_OFFSET_CFG_P2_LED1_SEL_WIDTH;                                             //[ 9: 9]
        jl_uint32 cfg_p1_led2_sel:PMX_PIN_MUX_0_OFFSET_CFG_P1_LED2_SEL_WIDTH;                                             //[10:10]
        jl_uint32 cfg_p1_led0_sel:PMX_PIN_MUX_0_OFFSET_CFG_P1_LED0_SEL_WIDTH;                                             //[11:11]
        jl_uint32 cfg_p1_led0_p7s_sel:PMX_PIN_MUX_0_OFFSET_CFG_P1_LED0_P7S_SEL_WIDTH;                                     //[12:12]
        jl_uint32 cfg_p1_led1_sel:PMX_PIN_MUX_0_OFFSET_CFG_P1_LED1_SEL_WIDTH;                                             //[13:13]
        jl_uint32 cfg_p0_led2_sel:PMX_PIN_MUX_0_OFFSET_CFG_P0_LED2_SEL_WIDTH;                                             //[14:14]
        jl_uint32 cfg_p0_led1_sel:PMX_PIN_MUX_0_OFFSET_CFG_P0_LED1_SEL_WIDTH;                                             //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_0_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_0_ENTRY_SIZE];
} PMX_PIN_MUX_0_t;

#define PMX_PIN_MUX_1                                                                          ((jl_uint32)0x00204004U)
#define PMX_PIN_MUX_1_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_1_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_1_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_1_OFFSET_CFG_P0_LED0_SEL                                                                        (0)
#define PMX_PIN_MUX_1_OFFSET_CFG_P0_LED0_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO0_SEL                                                                          (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO0_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO1_SEL                                                                          (2)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO1_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO2_SEL                                                                          (3)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO2_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO3_SEL                                                                          (4)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO3_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO4_SEL                                                                          (5)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO4_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO5_SEL                                                                          (6)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO5_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO6_SEL                                                                          (7)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO6_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO7_SEL                                                                          (8)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO7_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO8_SEL                                                                          (9)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO8_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO9_SEL                                                                         (10)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO9_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO10_SEL                                                                        (11)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO10_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO11_SEL                                                                        (12)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO11_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO12_SEL                                                                        (13)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO12_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO13_SEL                                                                        (14)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO13_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO14_SEL                                                                        (15)
#define PMX_PIN_MUX_1_OFFSET_CFG_GPIO14_SEL_WIDTH                                                                   (1)
typedef union PMX_PIN_MUX_1_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_p0_led0_sel:PMX_PIN_MUX_1_OFFSET_CFG_P0_LED0_SEL_WIDTH;                                             //[ 0: 0]
        jl_uint32 cfg_gpio0_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO0_SEL_WIDTH;                                                 //[ 1: 1]
        jl_uint32 cfg_gpio1_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO1_SEL_WIDTH;                                                 //[ 2: 2]
        jl_uint32 cfg_gpio2_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO2_SEL_WIDTH;                                                 //[ 3: 3]
        jl_uint32 cfg_gpio3_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO3_SEL_WIDTH;                                                 //[ 4: 4]
        jl_uint32 cfg_gpio4_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO4_SEL_WIDTH;                                                 //[ 5: 5]
        jl_uint32 cfg_gpio5_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO5_SEL_WIDTH;                                                 //[ 6: 6]
        jl_uint32 cfg_gpio6_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO6_SEL_WIDTH;                                                 //[ 7: 7]
        jl_uint32 cfg_gpio7_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO7_SEL_WIDTH;                                                 //[ 8: 8]
        jl_uint32 cfg_gpio8_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO8_SEL_WIDTH;                                                 //[ 9: 9]
        jl_uint32 cfg_gpio9_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO9_SEL_WIDTH;                                                 //[10:10]
        jl_uint32 cfg_gpio10_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO10_SEL_WIDTH;                                               //[11:11]
        jl_uint32 cfg_gpio11_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO11_SEL_WIDTH;                                               //[12:12]
        jl_uint32 cfg_gpio12_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO12_SEL_WIDTH;                                               //[13:13]
        jl_uint32 cfg_gpio13_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO13_SEL_WIDTH;                                               //[14:14]
        jl_uint32 cfg_gpio14_sel:PMX_PIN_MUX_1_OFFSET_CFG_GPIO14_SEL_WIDTH;                                               //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_1_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_1_ENTRY_SIZE];
} PMX_PIN_MUX_1_t;

#define PMX_PIN_MUX_2                                                                          ((jl_uint32)0x00204008U)
#define PMX_PIN_MUX_2_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_2_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_2_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_2_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO15_SEL                                                                         (0)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO15_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO16_SEL                                                                         (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO16_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO17_SEL                                                                         (2)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO17_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO18_SEL                                                                         (3)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO18_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO19_SEL                                                                         (4)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO19_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO20_SEL                                                                         (5)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO20_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO21_SEL                                                                         (6)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO21_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO22_SEL                                                                         (7)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO22_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO23_SEL                                                                         (8)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO23_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO24_SEL                                                                         (9)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO24_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO25_SEL                                                                        (10)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO25_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO26_SEL                                                                        (11)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO26_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO27_SEL                                                                        (12)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO27_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO28_SEL                                                                        (13)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO28_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO29_SEL                                                                        (14)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO29_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO30_SEL                                                                        (15)
#define PMX_PIN_MUX_2_OFFSET_CFG_GPIO30_SEL_WIDTH                                                                   (1)
typedef union PMX_PIN_MUX_2_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_gpio15_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO15_SEL_WIDTH;                                               //[ 0: 0]
        jl_uint32 cfg_gpio16_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO16_SEL_WIDTH;                                               //[ 1: 1]
        jl_uint32 cfg_gpio17_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO17_SEL_WIDTH;                                               //[ 2: 2]
        jl_uint32 cfg_gpio18_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO18_SEL_WIDTH;                                               //[ 3: 3]
        jl_uint32 cfg_gpio19_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO19_SEL_WIDTH;                                               //[ 4: 4]
        jl_uint32 cfg_gpio20_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO20_SEL_WIDTH;                                               //[ 5: 5]
        jl_uint32 cfg_gpio21_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO21_SEL_WIDTH;                                               //[ 6: 6]
        jl_uint32 cfg_gpio22_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO22_SEL_WIDTH;                                               //[ 7: 7]
        jl_uint32 cfg_gpio23_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO23_SEL_WIDTH;                                               //[ 8: 8]
        jl_uint32 cfg_gpio24_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO24_SEL_WIDTH;                                               //[ 9: 9]
        jl_uint32 cfg_gpio25_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO25_SEL_WIDTH;                                               //[10:10]
        jl_uint32 cfg_gpio26_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO26_SEL_WIDTH;                                               //[11:11]
        jl_uint32 cfg_gpio27_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO27_SEL_WIDTH;                                               //[12:12]
        jl_uint32 cfg_gpio28_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO28_SEL_WIDTH;                                               //[13:13]
        jl_uint32 cfg_gpio29_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO29_SEL_WIDTH;                                               //[14:14]
        jl_uint32 cfg_gpio30_sel:PMX_PIN_MUX_2_OFFSET_CFG_GPIO30_SEL_WIDTH;                                               //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_2_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_2_ENTRY_SIZE];
} PMX_PIN_MUX_2_t;

#define PMX_PIN_MUX_3                                                                          ((jl_uint32)0x0020400CU)
#define PMX_PIN_MUX_3_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_3_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_3_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO31_SEL                                                                         (0)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO31_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO32_SEL                                                                         (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO32_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO33_SEL                                                                         (2)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO33_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO34_SEL                                                                         (3)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO34_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO35_SEL                                                                         (4)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO35_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO36_SEL                                                                         (5)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO36_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO37_SEL                                                                         (6)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO37_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO38_SEL                                                                         (7)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO38_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO39_SEL                                                                         (8)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO39_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO40_SEL                                                                         (9)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO40_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO41_SEL                                                                        (10)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO41_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO42_SEL                                                                        (11)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO42_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO43_SEL                                                                        (12)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO43_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO44_SEL                                                                        (13)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO44_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO45_SEL                                                                        (14)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO45_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO46_SEL                                                                        (15)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO46_SEL_WIDTH                                                                   (1)
typedef union PMX_PIN_MUX_3_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_gpio31_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO31_SEL_WIDTH;                                               //[ 0: 0]
        jl_uint32 cfg_gpio32_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO32_SEL_WIDTH;                                               //[ 1: 1]
        jl_uint32 cfg_gpio33_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO33_SEL_WIDTH;                                               //[ 2: 2]
        jl_uint32 cfg_gpio34_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO34_SEL_WIDTH;                                               //[ 3: 3]
        jl_uint32 cfg_gpio35_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO35_SEL_WIDTH;                                               //[ 4: 4]
        jl_uint32 cfg_gpio36_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO36_SEL_WIDTH;                                               //[ 5: 5]
        jl_uint32 cfg_gpio37_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO37_SEL_WIDTH;                                               //[ 6: 6]
        jl_uint32 cfg_gpio38_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO38_SEL_WIDTH;                                               //[ 7: 7]
        jl_uint32 cfg_gpio39_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO39_SEL_WIDTH;                                               //[ 8: 8]
        jl_uint32 cfg_gpio40_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO40_SEL_WIDTH;                                               //[ 9: 9]
        jl_uint32 cfg_gpio41_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO41_SEL_WIDTH;                                               //[10:10]
        jl_uint32 cfg_gpio42_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO42_SEL_WIDTH;                                               //[11:11]
        jl_uint32 cfg_gpio43_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO43_SEL_WIDTH;                                               //[12:12]
        jl_uint32 cfg_gpio44_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO44_SEL_WIDTH;                                               //[13:13]
        jl_uint32 cfg_gpio45_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO45_SEL_WIDTH;                                               //[14:14]
        jl_uint32 cfg_gpio46_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO46_SEL_WIDTH;                                               //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_3_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_3_ENTRY_SIZE];
} PMX_PIN_MUX_3_t;

#define PMX_PIN_MUX_4                                                                          ((jl_uint32)0x00204010U)
#define PMX_PIN_MUX_4_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_4_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_4_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_4_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO47_SEL                                                                         (0)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO47_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_SMI_MODE                                                                           (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_SMI_MODE_WIDTH                                                                     (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_I2C_M_MODE                                                                         (2)
#define PMX_PIN_MUX_4_OFFSET_CFG_I2C_M_MODE_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_I2C_S_MODE                                                                         (3)
#define PMX_PIN_MUX_4_OFFSET_CFG_I2C_S_MODE_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_UART_MODE                                                                          (4)
#define PMX_PIN_MUX_4_OFFSET_CFG_UART_MODE_WIDTH                                                                    (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_SPF_SEL                                                                            (5)
#define PMX_PIN_MUX_4_OFFSET_CFG_SPF_SEL_WIDTH                                                                      (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_SPI_MODE                                                                           (6)
#define PMX_PIN_MUX_4_OFFSET_CFG_SPI_MODE_WIDTH                                                                     (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_SERI_LED_MODE                                                                      (7)
#define PMX_PIN_MUX_4_OFFSET_CFG_SERI_LED_MODE_WIDTH                                                                (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_INTN_SEL                                                                           (8)
#define PMX_PIN_MUX_4_OFFSET_CFG_INTN_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_INTN_P7SC_SEL                                                                      (9)
#define PMX_PIN_MUX_4_OFFSET_CFG_INTN_P7SC_SEL_WIDTH                                                                (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV0_SEL                                                                          (10)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV0_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV0_P5_SEL                                                                       (11)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV0_P5_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV1_SEL                                                                          (12)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV1_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV2_SEL                                                                          (13)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV2_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV2_P7_SEL                                                                       (14)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV2_P7_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV3_SEL                                                                          (15)
#define PMX_PIN_MUX_4_OFFSET_CFG_RSV3_SEL_WIDTH                                                                     (1)
typedef union PMX_PIN_MUX_4_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_gpio47_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO47_SEL_WIDTH;                                               //[ 0: 0]
        jl_uint32 cfg_smi_mode:PMX_PIN_MUX_4_OFFSET_CFG_SMI_MODE_WIDTH;                                                   //[ 1: 1]
        jl_uint32 cfg_i2c_m_mode:PMX_PIN_MUX_4_OFFSET_CFG_I2C_M_MODE_WIDTH;                                               //[ 2: 2]
        jl_uint32 cfg_i2c_s_mode:PMX_PIN_MUX_4_OFFSET_CFG_I2C_S_MODE_WIDTH;                                               //[ 3: 3]
        jl_uint32 cfg_uart_mode:PMX_PIN_MUX_4_OFFSET_CFG_UART_MODE_WIDTH;                                                 //[ 4: 4]
        jl_uint32 cfg_spf_sel:PMX_PIN_MUX_4_OFFSET_CFG_SPF_SEL_WIDTH;                                                     //[ 5: 5]
        jl_uint32 cfg_spi_mode:PMX_PIN_MUX_4_OFFSET_CFG_SPI_MODE_WIDTH;                                                   //[ 6: 6]
        jl_uint32 cfg_seri_led_mode:PMX_PIN_MUX_4_OFFSET_CFG_SERI_LED_MODE_WIDTH;                                         //[ 7: 7]
        jl_uint32 cfg_intn_sel:PMX_PIN_MUX_4_OFFSET_CFG_INTN_SEL_WIDTH;                                                   //[ 8: 8]
        jl_uint32 cfg_intn_p7sc_sel:PMX_PIN_MUX_4_OFFSET_CFG_INTN_P7SC_SEL_WIDTH;                                         //[ 9: 9]
        jl_uint32 cfg_rsv0_sel:PMX_PIN_MUX_4_OFFSET_CFG_RSV0_SEL_WIDTH;                                                   //[10:10]
        jl_uint32 cfg_rsv0_p5_sel:PMX_PIN_MUX_4_OFFSET_CFG_RSV0_P5_SEL_WIDTH;                                             //[11:11]
        jl_uint32 cfg_rsv1_sel:PMX_PIN_MUX_4_OFFSET_CFG_RSV1_SEL_WIDTH;                                                   //[12:12]
        jl_uint32 cfg_rsv2_sel:PMX_PIN_MUX_4_OFFSET_CFG_RSV2_SEL_WIDTH;                                                   //[13:13]
        jl_uint32 cfg_rsv2_p7_sel:PMX_PIN_MUX_4_OFFSET_CFG_RSV2_P7_SEL_WIDTH;                                             //[14:14]
        jl_uint32 cfg_rsv3_sel:PMX_PIN_MUX_4_OFFSET_CFG_RSV3_SEL_WIDTH;                                                   //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_4_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_4_ENTRY_SIZE];
} PMX_PIN_MUX_4_t;

#define PMX_PIN_MUX_5                                                                          ((jl_uint32)0x00204014U)
#define PMX_PIN_MUX_5_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_5_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_5_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_5_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_5_OFFSET_CFG_RSV3_P7_SEL                                                                        (0)
#define PMX_PIN_MUX_5_OFFSET_CFG_RSV3_P7_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_RSV4_SEL                                                                           (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_RSV4_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_RSV4_P7_SEL                                                                        (2)
#define PMX_PIN_MUX_5_OFFSET_CFG_RSV4_P7_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_INNER_I2C_SEL                                                                      (3)
#define PMX_PIN_MUX_5_OFFSET_CFG_INNER_I2C_SEL_WIDTH                                                                (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_JTAG_SEL                                                                           (4)
#define PMX_PIN_MUX_5_OFFSET_CFG_JTAG_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_INTN_SEL                                                                       (5)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_INTN_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_DIG_DIS_LPD                                                                    (6)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_DIG_DIS_LPD_WIDTH                                                              (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_MII_CRS                                                                   (7)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_MII_CRS_WIDTH                                                             (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD3                                                                   (8)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD3_WIDTH                                                             (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD2                                                                   (9)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD2_WIDTH                                                             (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD1                                                                  (10)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD1_WIDTH                                                             (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD0                                                                  (11)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD0_WIDTH                                                             (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXCTL                                                                 (12)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXCTL_WIDTH                                                            (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXCLK                                                                 (13)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXCLK_WIDTH                                                            (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_RXCLK                                                                 (14)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_RXCLK_WIDTH                                                            (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_RXCTL                                                                 (15)
#define PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_RXCTL_WIDTH                                                            (1)
typedef union PMX_PIN_MUX_5_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_rsv3_p7_sel:PMX_PIN_MUX_5_OFFSET_CFG_RSV3_P7_SEL_WIDTH;                                             //[ 0: 0]
        jl_uint32 cfg_rsv4_sel:PMX_PIN_MUX_5_OFFSET_CFG_RSV4_SEL_WIDTH;                                                   //[ 1: 1]
        jl_uint32 cfg_rsv4_p7_sel:PMX_PIN_MUX_5_OFFSET_CFG_RSV4_P7_SEL_WIDTH;                                             //[ 2: 2]
        jl_uint32 cfg_inner_i2c_sel:PMX_PIN_MUX_5_OFFSET_CFG_INNER_I2C_SEL_WIDTH;                                         //[ 3: 3]
        jl_uint32 cfg_jtag_sel:PMX_PIN_MUX_5_OFFSET_CFG_JTAG_SEL_WIDTH;                                                   //[ 4: 4]
        jl_uint32 cfg_dbg_intn_sel:PMX_PIN_MUX_5_OFFSET_CFG_DBG_INTN_SEL_WIDTH;                                           //[ 5: 5]
        jl_uint32 cfg_dbg_dig_dis_lpd:PMX_PIN_MUX_5_OFFSET_CFG_DBG_DIG_DIS_LPD_WIDTH;                                     //[ 6: 6]
        jl_uint32 cfg_dbg_sys0_mii_crs:PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_MII_CRS_WIDTH;                                   //[ 7: 7]
        jl_uint32 cfg_dbg_sys0_rg_txd3:PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD3_WIDTH;                                   //[ 8: 8]
        jl_uint32 cfg_dbg_sys0_rg_txd2:PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD2_WIDTH;                                   //[ 9: 9]
        jl_uint32 cfg_dbg_sys0_rg_txd1:PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD1_WIDTH;                                   //[10:10]
        jl_uint32 cfg_dbg_sys0_rg_txd0:PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXD0_WIDTH;                                   //[11:11]
        jl_uint32 cfg_dbg_sys0_rg_txctl:PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXCTL_WIDTH;                                 //[12:12]
        jl_uint32 cfg_dbg_sys0_rg_txclk:PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_TXCLK_WIDTH;                                 //[13:13]
        jl_uint32 cfg_dbg_sys0_rg_rxclk:PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_RXCLK_WIDTH;                                 //[14:14]
        jl_uint32 cfg_dbg_sys0_rg_rxctl:PMX_PIN_MUX_5_OFFSET_CFG_DBG_SYS0_RG_RXCTL_WIDTH;                                 //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_5_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_5_ENTRY_SIZE];
} PMX_PIN_MUX_5_t;

#define PMX_PIN_MUX_6                                                                          ((jl_uint32)0x00204018U)
#define PMX_PIN_MUX_6_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_6_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_6_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_6_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD0                                                                   (0)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD0_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD1                                                                   (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD1_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD2                                                                   (2)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD2_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD3                                                                   (3)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD3_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_MII_CRS                                                                   (4)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_MII_CRS_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD3                                                                   (5)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD3_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD2                                                                   (6)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD2_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD1                                                                   (7)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD1_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD0                                                                   (8)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD0_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXCTL                                                                  (9)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXCTL_WIDTH                                                            (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXCLK                                                                 (10)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXCLK_WIDTH                                                            (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXCLK                                                                 (11)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXCLK_WIDTH                                                            (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXCTL                                                                 (12)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXCTL_WIDTH                                                            (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXD0                                                                  (13)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXD0_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXD1                                                                  (14)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXD1_WIDTH                                                             (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXD2                                                                  (15)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXD2_WIDTH                                                             (1)
typedef union PMX_PIN_MUX_6_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_dbg_sys0_rg_rxd0:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD0_WIDTH;                                   //[ 0: 0]
        jl_uint32 cfg_dbg_sys0_rg_rxd1:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD1_WIDTH;                                   //[ 1: 1]
        jl_uint32 cfg_dbg_sys0_rg_rxd2:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD2_WIDTH;                                   //[ 2: 2]
        jl_uint32 cfg_dbg_sys0_rg_rxd3:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS0_RG_RXD3_WIDTH;                                   //[ 3: 3]
        jl_uint32 cfg_dbg_sys1_mii_crs:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_MII_CRS_WIDTH;                                   //[ 4: 4]
        jl_uint32 cfg_dbg_sys1_rg_txd3:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD3_WIDTH;                                   //[ 5: 5]
        jl_uint32 cfg_dbg_sys1_rg_txd2:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD2_WIDTH;                                   //[ 6: 6]
        jl_uint32 cfg_dbg_sys1_rg_txd1:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD1_WIDTH;                                   //[ 7: 7]
        jl_uint32 cfg_dbg_sys1_rg_txd0:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXD0_WIDTH;                                   //[ 8: 8]
        jl_uint32 cfg_dbg_sys1_rg_txctl:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXCTL_WIDTH;                                 //[ 9: 9]
        jl_uint32 cfg_dbg_sys1_rg_txclk:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_TXCLK_WIDTH;                                 //[10:10]
        jl_uint32 cfg_dbg_sys1_rg_rxclk:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXCLK_WIDTH;                                 //[11:11]
        jl_uint32 cfg_dbg_sys1_rg_rxctl:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXCTL_WIDTH;                                 //[12:12]
        jl_uint32 cfg_dbg_sys1_rg_rxd0:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXD0_WIDTH;                                   //[13:13]
        jl_uint32 cfg_dbg_sys1_rg_rxd1:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXD1_WIDTH;                                   //[14:14]
        jl_uint32 cfg_dbg_sys1_rg_rxd2:PMX_PIN_MUX_6_OFFSET_CFG_DBG_SYS1_RG_RXD2_WIDTH;                                   //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_6_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_6_ENTRY_SIZE];
} PMX_PIN_MUX_6_t;

#define PMX_PIN_MUX_7                                                                          ((jl_uint32)0x0020401CU)
#define PMX_PIN_MUX_7_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_7_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_7_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_7_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXD3                                                                   (0)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXD3_WIDTH                                                             (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_GPIO26                                                                     (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_GPIO26_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P4LED2                                                                     (2)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P4LED2_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P4LED0                                                                     (3)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P4LED0_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P4LED1                                                                     (4)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P4LED1_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P3LED1                                                                     (5)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P3LED1_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P3LED2                                                                     (6)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P3LED2_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P3LED0                                                                     (7)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P3LED0_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P2LED2                                                                     (8)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P2LED2_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P2LED0                                                                     (9)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P2LED0_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P2LED1                                                                    (10)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P2LED1_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P1LED2                                                                    (11)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P1LED2_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P1LED0                                                                    (12)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P1LED0_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P1LED1                                                                    (13)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P1LED1_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P0LED2                                                                    (14)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P0LED2_WIDTH                                                               (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_LED_DA                                                                    (15)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_LED_DA_WIDTH                                                               (1)
typedef union PMX_PIN_MUX_7_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_dbg_sys1_rg_rxd3:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXD3_WIDTH;                                   //[ 0: 0]
        jl_uint32 cfg_dbg_dig_gpio26:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_GPIO26_WIDTH;                                       //[ 1: 1]
        jl_uint32 cfg_dbg_dig_p4led2:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P4LED2_WIDTH;                                       //[ 2: 2]
        jl_uint32 cfg_dbg_dig_p4led0:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P4LED0_WIDTH;                                       //[ 3: 3]
        jl_uint32 cfg_dbg_dig_p4led1:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P4LED1_WIDTH;                                       //[ 4: 4]
        jl_uint32 cfg_dbg_dig_p3led1:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P3LED1_WIDTH;                                       //[ 5: 5]
        jl_uint32 cfg_dbg_dig_p3led2:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P3LED2_WIDTH;                                       //[ 6: 6]
        jl_uint32 cfg_dbg_dig_p3led0:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P3LED0_WIDTH;                                       //[ 7: 7]
        jl_uint32 cfg_dbg_dig_p2led2:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P2LED2_WIDTH;                                       //[ 8: 8]
        jl_uint32 cfg_dbg_dig_p2led0:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P2LED0_WIDTH;                                       //[ 9: 9]
        jl_uint32 cfg_dbg_dig_p2led1:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P2LED1_WIDTH;                                       //[10:10]
        jl_uint32 cfg_dbg_dig_p1led2:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P1LED2_WIDTH;                                       //[11:11]
        jl_uint32 cfg_dbg_dig_p1led0:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P1LED0_WIDTH;                                       //[12:12]
        jl_uint32 cfg_dbg_dig_p1led1:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P1LED1_WIDTH;                                       //[13:13]
        jl_uint32 cfg_dbg_dig_p0led2:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_P0LED2_WIDTH;                                       //[14:14]
        jl_uint32 cfg_dbg_dig_led_da:PMX_PIN_MUX_7_OFFSET_CFG_DBG_DIG_LED_DA_WIDTH;                                       //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_7_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_7_ENTRY_SIZE];
} PMX_PIN_MUX_7_t;

#define PMX_PIN_MUX_8                                                                          ((jl_uint32)0x00204020U)
#define PMX_PIN_MUX_8_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_8_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_8_OFFSET_RSVD0                                                                                 (12)
#define PMX_PIN_MUX_8_OFFSET_RSVD0_WIDTH                                                                           (20)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_DIG_SMI_SEL                                                                    (0)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_DIG_SMI_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SPI_CS                                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SPI_CS_WIDTH                                                                   (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SCL_MDC_SPI_CK                                                                 (2)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SCL_MDC_SPI_CK_WIDTH                                                           (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SDA_MDIO_SPI_SI                                                                (3)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SDA_MDIO_SPI_SI_WIDTH                                                          (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SPI_SO                                                                         (4)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SPI_SO_WIDTH                                                                   (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_INNER_SCL                                                                      (5)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_INNER_SCL_WIDTH                                                                (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_INNER_SDA                                                                      (6)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_INNER_SDA_WIDTH                                                                (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_CLK_IN_MODE                                                              (7)
#define PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_CLK_IN_MODE_WIDTH                                                        (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_CLK_OUT_MODE                                                             (8)
#define PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_CLK_OUT_MODE_WIDTH                                                       (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_OUT_MODE                                                                 (9)
#define PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_OUT_MODE_WIDTH                                                           (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_IN_MODE                                                                 (10)
#define PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_IN_MODE_WIDTH                                                            (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_SWC_DEBUG_MODE                                                                    (11)
#define PMX_PIN_MUX_8_OFFSET_CFG_SWC_DEBUG_MODE_WIDTH                                                               (1)
typedef union PMX_PIN_MUX_8_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_dbg_dig_smi_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_DIG_SMI_SEL_WIDTH;                                     //[ 0: 0]
        jl_uint32 cfg_dbg_spi_cs:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SPI_CS_WIDTH;                                               //[ 1: 1]
        jl_uint32 cfg_dbg_scl_mdc_spi_ck:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SCL_MDC_SPI_CK_WIDTH;                               //[ 2: 2]
        jl_uint32 cfg_dbg_sda_mdio_spi_si:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SDA_MDIO_SPI_SI_WIDTH;                             //[ 3: 3]
        jl_uint32 cfg_dbg_spi_so:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SPI_SO_WIDTH;                                               //[ 4: 4]
        jl_uint32 cfg_dbg_inner_scl:PMX_PIN_MUX_8_OFFSET_CFG_DBG_INNER_SCL_WIDTH;                                         //[ 5: 5]
        jl_uint32 cfg_dbg_inner_sda:PMX_PIN_MUX_8_OFFSET_CFG_DBG_INNER_SDA_WIDTH;                                         //[ 6: 6]
        jl_uint32 cfg_phy_debug_clk_in_mode:PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_CLK_IN_MODE_WIDTH;                         //[ 7: 7]
        jl_uint32 cfg_phy_debug_clk_out_mode:PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_CLK_OUT_MODE_WIDTH;                       //[ 8: 8]
        jl_uint32 cfg_phy_debug_out_mode:PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_OUT_MODE_WIDTH;                               //[ 9: 9]
        jl_uint32 cfg_phy_debug_in_mode:PMX_PIN_MUX_8_OFFSET_CFG_PHY_DEBUG_IN_MODE_WIDTH;                                 //[10:10]
        jl_uint32 cfg_swc_debug_mode:PMX_PIN_MUX_8_OFFSET_CFG_SWC_DEBUG_MODE_WIDTH;                                       //[11:11]
        jl_uint32 rsvd0:PMX_PIN_MUX_8_OFFSET_RSVD0_WIDTH;                                                                 //[31:12]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_8_ENTRY_SIZE];
} PMX_PIN_MUX_8_t;

#endif /* __JL_REG_PMX_H__ */

