//reg_phg_afe_sdspll.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_PHG_AFE_SDSPLL_H__
#define __JL_REG_PHG_AFE_SDSPLL_H__

#include <jl_types.h>

#define PHG_AFE_SDSPLL_BASE                                                                    ((jl_uint32)0x00240080U)
#define PHG_AFE_SDSPLL_BLOCK_SIZE                                                              ((jl_uint32)0x00000040U)

#define PHG_AFE_SDSPLL_ANA_PU0                                                                 ((jl_uint32)0x00240080U)
#define PHG_AFE_SDSPLL_ANA_PU0_NUM                                                             ((jl_uint32)0x00000001U)
#define PHG_AFE_SDSPLL_ANA_PU0_ENTRY_SIZE                                                                           (1)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_RSVD1                                                                        (13)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_RSVD1_WIDTH                                                                  (19)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_RSVD0                                                                         (0)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_RSVD0_WIDTH                                                                   (1)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_RSVD_WR_PU0                                                                   (1)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_RSVD_WR_PU0_WIDTH                                                             (7)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_PLL                                                                        (8)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_PLL_WIDTH                                                                  (1)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_1V_TO_0P9V_TX                                                      (9)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_1V_TO_0P9V_TX_WIDTH                                                (1)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_1V_TO_0P9V                                                        (10)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_1V_TO_0P9V_WIDTH                                                   (1)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_3P3V_TO_1V                                                        (11)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_3P3V_TO_1V_WIDTH                                                   (1)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_1P8V_TO_0P9V                                                      (12)
#define PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_1P8V_TO_0P9V_WIDTH                                                 (1)
typedef union PHG_AFE_SDSPLL_ANA_PU0_u {
    struct __attribute__ ((packed)) {
        jl_uint32 rsvd0:PHG_AFE_SDSPLL_ANA_PU0_OFFSET_RSVD0_WIDTH;                                                        //[ 0: 0]
        jl_uint32 rsvd_wr_pu0:PHG_AFE_SDSPLL_ANA_PU0_OFFSET_RSVD_WR_PU0_WIDTH;                                            //[ 7: 1]
        jl_uint32 pu_pll:PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_PLL_WIDTH;                                                      //[ 8: 8]
        jl_uint32 pu_ana_ldo_1v_to_0p9v_tx:PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_1V_TO_0P9V_TX_WIDTH;                  //[ 9: 9]
        jl_uint32 pu_ana_ldo_1v_to_0p9v:PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_1V_TO_0P9V_WIDTH;                        //[10:10]
        jl_uint32 pu_ana_ldo_3p3v_to_1v:PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_3P3V_TO_1V_WIDTH;                        //[11:11]
        jl_uint32 pu_ana_ldo_1p8v_to_0p9v:PHG_AFE_SDSPLL_ANA_PU0_OFFSET_PU_ANA_LDO_1P8V_TO_0P9V_WIDTH;                    //[12:12]
        jl_uint32 rsvd1:PHG_AFE_SDSPLL_ANA_PU0_OFFSET_RSVD1_WIDTH;                                                        //[31:13]
    } BF;
    jl_uint32 val[PHG_AFE_SDSPLL_ANA_PU0_ENTRY_SIZE];
} PHG_AFE_SDSPLL_ANA_PU0_t;

#define PHG_AFE_SDSPLL_ANA_CFG0                                                                ((jl_uint32)0x00240084U)
#define PHG_AFE_SDSPLL_ANA_CFG0_NUM                                                            ((jl_uint32)0x00000001U)
#define PHG_AFE_SDSPLL_ANA_CFG0_ENTRY_SIZE                                                                          (1)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_RSVD0                                                                       (16)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_RSVD0_WIDTH                                                                 (16)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_LOCK_OUT                                                                 (0)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_LOCK_OUT_WIDTH                                                           (1)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_LOCKDET_EN                                                               (1)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_LOCKDET_EN_WIDTH                                                         (1)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_FBDIV_RSTN                                                               (2)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_FBDIV_RSTN_WIDTH                                                         (1)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_FBDIV_RAT                                                                (3)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_FBDIV_RAT_WIDTH                                                          (7)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_DAC_IN_EN                                                               (10)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_DAC_IN_EN_WIDTH                                                          (1)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_CP_PUB                                                                  (11)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_CP_PUB_WIDTH                                                             (1)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_CP_ISEL                                                                 (12)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_CP_ISEL_WIDTH                                                            (3)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_AVDD_VCO_TST_EN                                                         (15)
#define PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_AVDD_VCO_TST_EN_WIDTH                                                    (1)
typedef union PHG_AFE_SDSPLL_ANA_CFG0_u {
    struct __attribute__ ((packed)) {
        jl_uint32 pll_lock_out:PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_LOCK_OUT_WIDTH;                                         //[ 0: 0]
        jl_uint32 pll_lockdet_en:PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_LOCKDET_EN_WIDTH;                                     //[ 1: 1]
        jl_uint32 pll_fbdiv_rstn:PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_FBDIV_RSTN_WIDTH;                                     //[ 2: 2]
        jl_uint32 pll_fbdiv_rat:PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_FBDIV_RAT_WIDTH;                                       //[ 9: 3]
        jl_uint32 pll_dac_in_en:PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_DAC_IN_EN_WIDTH;                                       //[10:10]
        jl_uint32 pll_cp_pub:PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_CP_PUB_WIDTH;                                             //[11:11]
        jl_uint32 pll_cp_isel:PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_CP_ISEL_WIDTH;                                           //[14:12]
        jl_uint32 pll_avdd_vco_tst_en:PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_PLL_AVDD_VCO_TST_EN_WIDTH;                           //[15:15]
        jl_uint32 rsvd0:PHG_AFE_SDSPLL_ANA_CFG0_OFFSET_RSVD0_WIDTH;                                                       //[31:16]
    } BF;
    jl_uint32 val[PHG_AFE_SDSPLL_ANA_CFG0_ENTRY_SIZE];
} PHG_AFE_SDSPLL_ANA_CFG0_t;

#define PHG_AFE_SDSPLL_ANA_CFG1                                                                ((jl_uint32)0x00240088U)
#define PHG_AFE_SDSPLL_ANA_CFG1_NUM                                                            ((jl_uint32)0x00000001U)
#define PHG_AFE_SDSPLL_ANA_CFG1_ENTRY_SIZE                                                                          (1)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_RSVD0                                                                       (16)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_RSVD0_WIDTH                                                                 (16)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCO_BUF_PUL_UPB                                                          (0)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCO_BUF_PUL_UPB_WIDTH                                                    (1)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCO_SEL_BAND                                                             (1)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCO_SEL_BAND_WIDTH                                                       (3)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCO_LDO_BIAS_SEL                                                         (4)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCO_LDO_BIAS_SEL_WIDTH                                                   (1)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCON_TST_EN                                                              (5)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCON_TST_EN_WIDTH                                                        (1)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCON_DAC_SEL                                                             (6)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCON_DAC_SEL_WIDTH                                                       (3)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_PU_ANA_LDO_CP_VCO                                                        (9)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_PU_ANA_LDO_CP_VCO_WIDTH                                                  (1)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_PFD_FREEZE_CP_B                                                         (10)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_PFD_FREEZE_CP_B_WIDTH                                                    (1)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_VCON_RSTN                                                           (11)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_VCON_RSTN_WIDTH                                                      (1)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_R1_SEL                                                              (12)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_R1_SEL_WIDTH                                                         (2)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_C2_SEL                                                              (14)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_C2_SEL_WIDTH                                                         (1)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_C1_SEL                                                              (15)
#define PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_C1_SEL_WIDTH                                                         (1)
typedef union PHG_AFE_SDSPLL_ANA_CFG1_u {
    struct __attribute__ ((packed)) {
        jl_uint32 pll_vco_buf_pul_upb:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCO_BUF_PUL_UPB_WIDTH;                           //[ 0: 0]
        jl_uint32 pll_vco_sel_band:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCO_SEL_BAND_WIDTH;                                 //[ 3: 1]
        jl_uint32 pll_vco_ldo_bias_sel:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCO_LDO_BIAS_SEL_WIDTH;                         //[ 4: 4]
        jl_uint32 pll_vcon_tst_en:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCON_TST_EN_WIDTH;                                   //[ 5: 5]
        jl_uint32 pll_vcon_dac_sel:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_VCON_DAC_SEL_WIDTH;                                 //[ 8: 6]
        jl_uint32 pll_pu_ana_ldo_cp_vco:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_PU_ANA_LDO_CP_VCO_WIDTH;                       //[ 9: 9]
        jl_uint32 pll_pfd_freeze_cp_b:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_PFD_FREEZE_CP_B_WIDTH;                           //[10:10]
        jl_uint32 pll_lpf_vcon_rstn:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_VCON_RSTN_WIDTH;                               //[11:11]
        jl_uint32 pll_lpf_r1_sel:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_R1_SEL_WIDTH;                                     //[13:12]
        jl_uint32 pll_lpf_c2_sel:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_C2_SEL_WIDTH;                                     //[14:14]
        jl_uint32 pll_lpf_c1_sel:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_PLL_LPF_C1_SEL_WIDTH;                                     //[15:15]
        jl_uint32 rsvd0:PHG_AFE_SDSPLL_ANA_CFG1_OFFSET_RSVD0_WIDTH;                                                       //[31:16]
    } BF;
    jl_uint32 val[PHG_AFE_SDSPLL_ANA_CFG1_ENTRY_SIZE];
} PHG_AFE_SDSPLL_ANA_CFG1_t;

#define PHG_AFE_SDSPLL_ANA_CFG2                                                                ((jl_uint32)0x0024008CU)
#define PHG_AFE_SDSPLL_ANA_CFG2_NUM                                                            ((jl_uint32)0x00000001U)
#define PHG_AFE_SDSPLL_ANA_CFG2_ENTRY_SIZE                                                                          (1)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_RSVD0                                                                       (15)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_RSVD0_WIDTH                                                                 (17)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_RSVD_WR_CFG2                                                                 (0)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_RSVD_WR_CFG2_WIDTH                                                           (5)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_RSVD_RD_CFG2                                                                 (5)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_RSVD_RD_CFG2_WIDTH                                                           (5)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_PI_ISEL                                                                     (10)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_PI_ISEL_WIDTH                                                                (1)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_EN_0P9V_THRGH_MODE                                                          (11)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_EN_0P9V_THRGH_MODE_WIDTH                                                     (1)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_PLL_PFD_LDO_BIAS_SEL                                                        (12)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_PLL_PFD_LDO_BIAS_SEL_WIDTH                                                   (1)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_VREF_SEL                                                                    (13)
#define PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_VREF_SEL_WIDTH                                                               (2)
typedef union PHG_AFE_SDSPLL_ANA_CFG2_u {
    struct __attribute__ ((packed)) {
        jl_uint32 rsvd_wr_cfg2:PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_RSVD_WR_CFG2_WIDTH;                                         //[ 4: 0]
        jl_uint32 rsvd_rd_cfg2:PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_RSVD_RD_CFG2_WIDTH;                                         //[ 9: 5]
        jl_uint32 pi_isel:PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_PI_ISEL_WIDTH;                                                   //[10:10]
        jl_uint32 en_0p9v_thrgh_mode:PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_EN_0P9V_THRGH_MODE_WIDTH;                             //[11:11]
        jl_uint32 pll_pfd_ldo_bias_sel:PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_PLL_PFD_LDO_BIAS_SEL_WIDTH;                         //[12:12]
        jl_uint32 vref_sel:PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_VREF_SEL_WIDTH;                                                 //[14:13]
        jl_uint32 rsvd0:PHG_AFE_SDSPLL_ANA_CFG2_OFFSET_RSVD0_WIDTH;                                                       //[31:15]
    } BF;
    jl_uint32 val[PHG_AFE_SDSPLL_ANA_CFG2_ENTRY_SIZE];
} PHG_AFE_SDSPLL_ANA_CFG2_t;

#define PHG_AFE_SDSPLL_ANA_AZCAL0                                                              ((jl_uint32)0x00240090U)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_NUM                                                          ((jl_uint32)0x00000001U)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_ENTRY_SIZE                                                                        (1)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RSVD1                                                                     (16)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RSVD1_WIDTH                                                               (16)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RSVD0                                                                      (0)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RSVD0_WIDTH                                                                (1)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_PU_AZCMP                                                                   (1)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_PU_AZCMP_WIDTH                                                             (1)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RCAL_BR_SEL                                                                (2)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RCAL_BR_SEL_WIDTH                                                          (3)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RCALPG_B                                                                   (5)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RCALPG_B_WIDTH                                                             (3)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZ_IN_SEL                                                                  (8)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZ_IN_SEL_WIDTH                                                            (3)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZSEL                                                                     (11)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZSEL_WIDTH                                                                (3)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZB                                                                       (14)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZB_WIDTH                                                                  (1)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZCMPOUT                                                                  (15)
#define PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZCMPOUT_WIDTH                                                             (1)
typedef union PHG_AFE_SDSPLL_ANA_AZCAL0_u {
    struct __attribute__ ((packed)) {
        jl_uint32 rsvd0:PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RSVD0_WIDTH;                                                     //[ 0: 0]
        jl_uint32 pu_azcmp:PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_PU_AZCMP_WIDTH;                                               //[ 1: 1]
        jl_uint32 rcal_br_sel:PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RCAL_BR_SEL_WIDTH;                                         //[ 4: 2]
        jl_uint32 rcalpg_b:PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RCALPG_B_WIDTH;                                               //[ 7: 5]
        jl_uint32 az_in_sel:PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZ_IN_SEL_WIDTH;                                             //[10: 8]
        jl_uint32 azsel:PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZSEL_WIDTH;                                                     //[13:11]
        jl_uint32 azb:PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZB_WIDTH;                                                         //[14:14]
        jl_uint32 azcmpout:PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_AZCMPOUT_WIDTH;                                               //[15:15]
        jl_uint32 rsvd1:PHG_AFE_SDSPLL_ANA_AZCAL0_OFFSET_RSVD1_WIDTH;                                                     //[31:16]
    } BF;
    jl_uint32 val[PHG_AFE_SDSPLL_ANA_AZCAL0_ENTRY_SIZE];
} PHG_AFE_SDSPLL_ANA_AZCAL0_t;

#define PHG_AFE_SDSPLL_ANA_ATEST0                                                              ((jl_uint32)0x00240094U)
#define PHG_AFE_SDSPLL_ANA_ATEST0_NUM                                                          ((jl_uint32)0x00000001U)
#define PHG_AFE_SDSPLL_ANA_ATEST0_ENTRY_SIZE                                                                        (1)
#define PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_RSVD1                                                                     (16)
#define PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_RSVD1_WIDTH                                                               (16)
#define PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_RSVD0                                                                      (0)
#define PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_RSVD0_WIDTH                                                                (9)
#define PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_TE_BLK                                                                     (9)
#define PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_TE_BLK_WIDTH                                                               (4)
#define PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_TR                                                                        (13)
#define PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_TR_WIDTH                                                                   (3)
typedef union PHG_AFE_SDSPLL_ANA_ATEST0_u {
    struct __attribute__ ((packed)) {
        jl_uint32 rsvd0:PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_RSVD0_WIDTH;                                                     //[ 8: 0]
        jl_uint32 te_blk:PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_TE_BLK_WIDTH;                                                   //[12: 9]
        jl_uint32 tr:PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_TR_WIDTH;                                                           //[15:13]
        jl_uint32 rsvd1:PHG_AFE_SDSPLL_ANA_ATEST0_OFFSET_RSVD1_WIDTH;                                                     //[31:16]
    } BF;
    jl_uint32 val[PHG_AFE_SDSPLL_ANA_ATEST0_ENTRY_SIZE];
} PHG_AFE_SDSPLL_ANA_ATEST0_t;

#endif /* __JL_REG_PHG_AFE_SDSPLL_H__ */

