//reg_phg_afe_misc.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_PHG_AFE_MISC_H__
#define __JL_REG_PHG_AFE_MISC_H__

#include <jl_types.h>

#define PHG_AFE_MISC_BASE                                                                      ((jl_uint32)0x002400C0U)
#define PHG_AFE_MISC_BLOCK_SIZE                                                                ((jl_uint32)0x00000040U)

#define PHG_AFE_MISC_ANA_ID                                                                    ((jl_uint32)0x002400C0U)
#define PHG_AFE_MISC_ANA_ID_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_AFE_MISC_ANA_ID_ENTRY_SIZE                                                                              (1)
#define PHG_AFE_MISC_ANA_ID_OFFSET_RSVD0                                                                           (16)
#define PHG_AFE_MISC_ANA_ID_OFFSET_RSVD0_WIDTH                                                                     (16)
#define PHG_AFE_MISC_ANA_ID_OFFSET_IP_INFO                                                                          (0)
#define PHG_AFE_MISC_ANA_ID_OFFSET_IP_INFO_WIDTH                                                                    (8)
#define PHG_AFE_MISC_ANA_ID_OFFSET_IP_REV                                                                           (8)
#define PHG_AFE_MISC_ANA_ID_OFFSET_IP_REV_WIDTH                                                                     (8)
typedef union PHG_AFE_MISC_ANA_ID_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ip_info:PHG_AFE_MISC_ANA_ID_OFFSET_IP_INFO_WIDTH;                                                       //[ 7: 0]
        jl_uint32 ip_rev:PHG_AFE_MISC_ANA_ID_OFFSET_IP_REV_WIDTH;                                                         //[15: 8]
        jl_uint32 rsvd0:PHG_AFE_MISC_ANA_ID_OFFSET_RSVD0_WIDTH;                                                           //[31:16]
    } BF;
    jl_uint32 val[PHG_AFE_MISC_ANA_ID_ENTRY_SIZE];
} PHG_AFE_MISC_ANA_ID_t;

#define PHG_AFE_MISC_ANA_ATEST                                                                 ((jl_uint32)0x002400C4U)
#define PHG_AFE_MISC_ANA_ATEST_NUM                                                             ((jl_uint32)0x00000001U)
#define PHG_AFE_MISC_ANA_ATEST_ENTRY_SIZE                                                                           (1)
#define PHG_AFE_MISC_ANA_ATEST_OFFSET_RSVD1                                                                        (16)
#define PHG_AFE_MISC_ANA_ATEST_OFFSET_RSVD1_WIDTH                                                                  (16)
#define PHG_AFE_MISC_ANA_ATEST_OFFSET_RSVD0                                                                         (0)
#define PHG_AFE_MISC_ANA_ATEST_OFFSET_RSVD0_WIDTH                                                                   (8)
#define PHG_AFE_MISC_ANA_ATEST_OFFSET_MISC_TR                                                                       (8)
#define PHG_AFE_MISC_ANA_ATEST_OFFSET_MISC_TR_WIDTH                                                                 (3)
#define PHG_AFE_MISC_ANA_ATEST_OFFSET_MISC_TE_BLK                                                                  (11)
#define PHG_AFE_MISC_ANA_ATEST_OFFSET_MISC_TE_BLK_WIDTH                                                             (5)
typedef union PHG_AFE_MISC_ANA_ATEST_u {
    struct __attribute__ ((packed)) {
        jl_uint32 rsvd0:PHG_AFE_MISC_ANA_ATEST_OFFSET_RSVD0_WIDTH;                                                        //[ 7: 0]
        jl_uint32 misc_tr:PHG_AFE_MISC_ANA_ATEST_OFFSET_MISC_TR_WIDTH;                                                    //[10: 8]
        jl_uint32 misc_te_blk:PHG_AFE_MISC_ANA_ATEST_OFFSET_MISC_TE_BLK_WIDTH;                                            //[15:11]
        jl_uint32 rsvd1:PHG_AFE_MISC_ANA_ATEST_OFFSET_RSVD1_WIDTH;                                                        //[31:16]
    } BF;
    jl_uint32 val[PHG_AFE_MISC_ANA_ATEST_ENTRY_SIZE];
} PHG_AFE_MISC_ANA_ATEST_t;

#define PHG_AFE_MISC_ANA_REFERENCE                                                             ((jl_uint32)0x002400C8U)
#define PHG_AFE_MISC_ANA_REFERENCE_NUM                                                         ((jl_uint32)0x00000001U)
#define PHG_AFE_MISC_ANA_REFERENCE_ENTRY_SIZE                                                                       (1)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_RSVD0                                                                    (16)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_RSVD0_WIDTH                                                              (16)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_RSVD_WR_REFERENCE                                                    (0)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_RSVD_WR_REFERENCE_WIDTH                                             (11)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_PU_RANDOM                                                           (11)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_PU_RANDOM_WIDTH                                                      (1)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_SEL_DEGLITCH_WIDTH_REF_CLK                                          (12)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_SEL_DEGLITCH_WIDTH_REF_CLK_WIDTH                                     (2)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_SEL_DEGLITCH_REF_CLK                                                (14)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_SEL_DEGLITCH_REF_CLK_WIDTH                                           (1)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_CLK_DIG_DGLTCH_EN                                                   (15)
#define PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_CLK_DIG_DGLTCH_EN_WIDTH                                              (1)
typedef union PHG_AFE_MISC_ANA_REFERENCE_u {
    struct __attribute__ ((packed)) {
        jl_uint32 misc_rsvd_wr_reference:PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_RSVD_WR_REFERENCE_WIDTH;                  //[10: 0]
        jl_uint32 misc_pu_random:PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_PU_RANDOM_WIDTH;                                  //[11:11]
        jl_uint32 misc_sel_deglitch_width_ref_clk:PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_SEL_DEGLITCH_WIDTH_REF_CLK_WIDTH;  //[13:12]
        jl_uint32 misc_sel_deglitch_ref_clk:PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_SEL_DEGLITCH_REF_CLK_WIDTH;            //[14:14]
        jl_uint32 misc_clk_dig_dgltch_en:PHG_AFE_MISC_ANA_REFERENCE_OFFSET_MISC_CLK_DIG_DGLTCH_EN_WIDTH;                  //[15:15]
        jl_uint32 rsvd0:PHG_AFE_MISC_ANA_REFERENCE_OFFSET_RSVD0_WIDTH;                                                    //[31:16]
    } BF;
    jl_uint32 val[PHG_AFE_MISC_ANA_REFERENCE_ENTRY_SIZE];
} PHG_AFE_MISC_ANA_REFERENCE_t;

#define PHG_AFE_MISC_ANA_TSEN                                                                  ((jl_uint32)0x002400CCU)
#define PHG_AFE_MISC_ANA_TSEN_NUM                                                              ((jl_uint32)0x00000001U)
#define PHG_AFE_MISC_ANA_TSEN_ENTRY_SIZE                                                                            (1)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_RSVD1                                                                         (16)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_RSVD1_WIDTH                                                                   (16)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_RSVD0                                                                          (0)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_RSVD0_WIDTH                                                                    (8)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_AZ                                                                        (8)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_AZ_WIDTH                                                                  (1)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_CHOP_EN                                                                   (9)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_CHOP_EN_WIDTH                                                             (2)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_MODE                                                                     (11)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_MODE_WIDTH                                                                (1)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_INBUF_EN                                                                 (12)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_INBUF_EN_WIDTH                                                            (1)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_IN05_SEL                                                                 (13)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_IN05_SEL_WIDTH                                                            (1)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_CLK_SEL                                                                  (14)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_CLK_SEL_WIDTH                                                             (1)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_EN                                                                       (15)
#define PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_EN_WIDTH                                                                  (1)
typedef union PHG_AFE_MISC_ANA_TSEN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 rsvd0:PHG_AFE_MISC_ANA_TSEN_OFFSET_RSVD0_WIDTH;                                                         //[ 7: 0]
        jl_uint32 tsen_az:PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_AZ_WIDTH;                                                     //[ 8: 8]
        jl_uint32 tsen_chop_en:PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_CHOP_EN_WIDTH;                                           //[10: 9]
        jl_uint32 tsen_mode:PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_MODE_WIDTH;                                                 //[11:11]
        jl_uint32 tsen_inbuf_en:PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_INBUF_EN_WIDTH;                                         //[12:12]
        jl_uint32 tsen_in05_sel:PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_IN05_SEL_WIDTH;                                         //[13:13]
        jl_uint32 tsen_clk_sel:PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_CLK_SEL_WIDTH;                                           //[14:14]
        jl_uint32 tsen_en:PHG_AFE_MISC_ANA_TSEN_OFFSET_TSEN_EN_WIDTH;                                                     //[15:15]
        jl_uint32 rsvd1:PHG_AFE_MISC_ANA_TSEN_OFFSET_RSVD1_WIDTH;                                                         //[31:16]
    } BF;
    jl_uint32 val[PHG_AFE_MISC_ANA_TSEN_ENTRY_SIZE];
} PHG_AFE_MISC_ANA_TSEN_t;

#endif /* __JL_REG_PHG_AFE_MISC_H__ */

