//reg_crg.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_CRG_H__
#define __JL_REG_CRG_H__

#include <jl_types.h>

#define CRG_BASE                                                                               ((jl_uint32)0x00202000U)
#define CRG_BLOCK_SIZE                                                                         ((jl_uint32)0x00001000U)

#define CRG_COMMON_CLK_EN                                                                      ((jl_uint32)0x00202000U)
#define CRG_COMMON_CLK_EN_NUM                                                                  ((jl_uint32)0x00000001U)
#define CRG_COMMON_CLK_EN_ENTRY_SIZE                                                                                (1)
#define CRG_COMMON_CLK_EN_OFFSET_RSVD0                                                                              (6)
#define CRG_COMMON_CLK_EN_OFFSET_RSVD0_WIDTH                                                                       (26)
#define CRG_COMMON_CLK_EN_OFFSET_SWC_CLK_EN                                                                         (0)
#define CRG_COMMON_CLK_EN_OFFSET_SWC_CLK_EN_WIDTH                                                                   (1)
#define CRG_COMMON_CLK_EN_OFFSET_SWC_125M_CLK_EN                                                                    (1)
#define CRG_COMMON_CLK_EN_OFFSET_SWC_125M_CLK_EN_WIDTH                                                              (1)
#define CRG_COMMON_CLK_EN_OFFSET_SWC_50M_CLK_EN                                                                     (2)
#define CRG_COMMON_CLK_EN_OFFSET_SWC_50M_CLK_EN_WIDTH                                                               (1)
#define CRG_COMMON_CLK_EN_OFFSET_MAG_CLK_EN                                                                         (3)
#define CRG_COMMON_CLK_EN_OFFSET_MAG_CLK_EN_WIDTH                                                                   (1)
#define CRG_COMMON_CLK_EN_OFFSET_LED_CLK_EN                                                                         (4)
#define CRG_COMMON_CLK_EN_OFFSET_LED_CLK_EN_WIDTH                                                                   (1)
#define CRG_COMMON_CLK_EN_OFFSET_LED_SERIAL_CLK_EN                                                                  (5)
#define CRG_COMMON_CLK_EN_OFFSET_LED_SERIAL_CLK_EN_WIDTH                                                            (1)
typedef union CRG_COMMON_CLK_EN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 swc_clk_en:CRG_COMMON_CLK_EN_OFFSET_SWC_CLK_EN_WIDTH;                                                   //[ 0: 0]
        jl_uint32 swc_125m_clk_en:CRG_COMMON_CLK_EN_OFFSET_SWC_125M_CLK_EN_WIDTH;                                         //[ 1: 1]
        jl_uint32 swc_50m_clk_en:CRG_COMMON_CLK_EN_OFFSET_SWC_50M_CLK_EN_WIDTH;                                           //[ 2: 2]
        jl_uint32 mag_clk_en:CRG_COMMON_CLK_EN_OFFSET_MAG_CLK_EN_WIDTH;                                                   //[ 3: 3]
        jl_uint32 led_clk_en:CRG_COMMON_CLK_EN_OFFSET_LED_CLK_EN_WIDTH;                                                   //[ 4: 4]
        jl_uint32 led_serial_clk_en:CRG_COMMON_CLK_EN_OFFSET_LED_SERIAL_CLK_EN_WIDTH;                                     //[ 5: 5]
        jl_uint32 rsvd0:CRG_COMMON_CLK_EN_OFFSET_RSVD0_WIDTH;                                                             //[31: 6]
    } BF;
    jl_uint32 val[CRG_COMMON_CLK_EN_ENTRY_SIZE];
} CRG_COMMON_CLK_EN_t;

#define CRG_COMMON_RSTN                                                                        ((jl_uint32)0x00202004U)
#define CRG_COMMON_RSTN_NUM                                                                    ((jl_uint32)0x00000001U)
#define CRG_COMMON_RSTN_ENTRY_SIZE                                                                                  (1)
#define CRG_COMMON_RSTN_OFFSET_RSVD0                                                                                (7)
#define CRG_COMMON_RSTN_OFFSET_RSVD0_WIDTH                                                                         (25)
#define CRG_COMMON_RSTN_OFFSET_SWC_RSTN                                                                             (0)
#define CRG_COMMON_RSTN_OFFSET_SWC_RSTN_WIDTH                                                                       (1)
#define CRG_COMMON_RSTN_OFFSET_LED_RSTN                                                                             (1)
#define CRG_COMMON_RSTN_OFFSET_LED_RSTN_WIDTH                                                                       (1)
#define CRG_COMMON_RSTN_OFFSET_MAG_RSTN                                                                             (2)
#define CRG_COMMON_RSTN_OFFSET_MAG_RSTN_WIDTH                                                                       (1)
#define CRG_COMMON_RSTN_OFFSET_SAG_RSTN                                                                             (3)
#define CRG_COMMON_RSTN_OFFSET_SAG_RSTN_WIDTH                                                                       (1)
#define CRG_COMMON_RSTN_OFFSET_PINMUX_RSTN                                                                          (4)
#define CRG_COMMON_RSTN_OFFSET_PINMUX_RSTN_WIDTH                                                                    (1)
#define CRG_COMMON_RSTN_OFFSET_IOPAD_RSTN                                                                           (5)
#define CRG_COMMON_RSTN_OFFSET_IOPAD_RSTN_WIDTH                                                                     (1)
#define CRG_COMMON_RSTN_OFFSET_TOP_CMN_RSTN                                                                         (6)
#define CRG_COMMON_RSTN_OFFSET_TOP_CMN_RSTN_WIDTH                                                                   (1)
typedef union CRG_COMMON_RSTN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 swc_rstn:CRG_COMMON_RSTN_OFFSET_SWC_RSTN_WIDTH;                                                         //[ 0: 0]
        jl_uint32 led_rstn:CRG_COMMON_RSTN_OFFSET_LED_RSTN_WIDTH;                                                         //[ 1: 1]
        jl_uint32 mag_rstn:CRG_COMMON_RSTN_OFFSET_MAG_RSTN_WIDTH;                                                         //[ 2: 2]
        jl_uint32 sag_rstn:CRG_COMMON_RSTN_OFFSET_SAG_RSTN_WIDTH;                                                         //[ 3: 3]
        jl_uint32 pinmux_rstn:CRG_COMMON_RSTN_OFFSET_PINMUX_RSTN_WIDTH;                                                   //[ 4: 4]
        jl_uint32 iopad_rstn:CRG_COMMON_RSTN_OFFSET_IOPAD_RSTN_WIDTH;                                                     //[ 5: 5]
        jl_uint32 top_cmn_rstn:CRG_COMMON_RSTN_OFFSET_TOP_CMN_RSTN_WIDTH;                                                 //[ 6: 6]
        jl_uint32 rsvd0:CRG_COMMON_RSTN_OFFSET_RSVD0_WIDTH;                                                               //[31: 7]
    } BF;
    jl_uint32 val[CRG_COMMON_RSTN_ENTRY_SIZE];
} CRG_COMMON_RSTN_t;

#define CRG_MAC_RSTN                                                                           ((jl_uint32)0x00202008U)
#define CRG_MAC_RSTN_NUM                                                                       ((jl_uint32)0x00000001U)
#define CRG_MAC_RSTN_ENTRY_SIZE                                                                                     (1)
#define CRG_MAC_RSTN_OFFSET_RSVD0                                                                                  (11)
#define CRG_MAC_RSTN_OFFSET_RSVD0_WIDTH                                                                            (21)
#define CRG_MAC_RSTN_OFFSET_LMAC_0_RSTN                                                                             (0)
#define CRG_MAC_RSTN_OFFSET_LMAC_0_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_LMAC_1_RSTN                                                                             (1)
#define CRG_MAC_RSTN_OFFSET_LMAC_1_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_LMAC_2_RSTN                                                                             (2)
#define CRG_MAC_RSTN_OFFSET_LMAC_2_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_LMAC_3_RSTN                                                                             (3)
#define CRG_MAC_RSTN_OFFSET_LMAC_3_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_LMAC_4_RSTN                                                                             (4)
#define CRG_MAC_RSTN_OFFSET_LMAC_4_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_LMAC_5_RSTN                                                                             (5)
#define CRG_MAC_RSTN_OFFSET_LMAC_5_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_LMAC_6_RSTN                                                                             (6)
#define CRG_MAC_RSTN_OFFSET_LMAC_6_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_LMAC_7_RSTN                                                                             (7)
#define CRG_MAC_RSTN_OFFSET_LMAC_7_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_SMAC_0_RSTN                                                                             (8)
#define CRG_MAC_RSTN_OFFSET_SMAC_0_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_SMAC_1_RSTN                                                                             (9)
#define CRG_MAC_RSTN_OFFSET_SMAC_1_RSTN_WIDTH                                                                       (1)
#define CRG_MAC_RSTN_OFFSET_CMAC_0_RSTN                                                                            (10)
#define CRG_MAC_RSTN_OFFSET_CMAC_0_RSTN_WIDTH                                                                       (1)
typedef union CRG_MAC_RSTN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 lmac_0_rstn:CRG_MAC_RSTN_OFFSET_LMAC_0_RSTN_WIDTH;                                                      //[ 0: 0]
        jl_uint32 lmac_1_rstn:CRG_MAC_RSTN_OFFSET_LMAC_1_RSTN_WIDTH;                                                      //[ 1: 1]
        jl_uint32 lmac_2_rstn:CRG_MAC_RSTN_OFFSET_LMAC_2_RSTN_WIDTH;                                                      //[ 2: 2]
        jl_uint32 lmac_3_rstn:CRG_MAC_RSTN_OFFSET_LMAC_3_RSTN_WIDTH;                                                      //[ 3: 3]
        jl_uint32 lmac_4_rstn:CRG_MAC_RSTN_OFFSET_LMAC_4_RSTN_WIDTH;                                                      //[ 4: 4]
        jl_uint32 lmac_5_rstn:CRG_MAC_RSTN_OFFSET_LMAC_5_RSTN_WIDTH;                                                      //[ 5: 5]
        jl_uint32 lmac_6_rstn:CRG_MAC_RSTN_OFFSET_LMAC_6_RSTN_WIDTH;                                                      //[ 6: 6]
        jl_uint32 lmac_7_rstn:CRG_MAC_RSTN_OFFSET_LMAC_7_RSTN_WIDTH;                                                      //[ 7: 7]
        jl_uint32 smac_0_rstn:CRG_MAC_RSTN_OFFSET_SMAC_0_RSTN_WIDTH;                                                      //[ 8: 8]
        jl_uint32 smac_1_rstn:CRG_MAC_RSTN_OFFSET_SMAC_1_RSTN_WIDTH;                                                      //[ 9: 9]
        jl_uint32 cmac_0_rstn:CRG_MAC_RSTN_OFFSET_CMAC_0_RSTN_WIDTH;                                                      //[10:10]
        jl_uint32 rsvd0:CRG_MAC_RSTN_OFFSET_RSVD0_WIDTH;                                                                  //[31:11]
    } BF;
    jl_uint32 val[CRG_MAC_RSTN_ENTRY_SIZE];
} CRG_MAC_RSTN_t;

#define CRG_MAC_TX_RSTN                                                                        ((jl_uint32)0x0020200CU)
#define CRG_MAC_TX_RSTN_NUM                                                                    ((jl_uint32)0x00000001U)
#define CRG_MAC_TX_RSTN_ENTRY_SIZE                                                                                  (1)
#define CRG_MAC_TX_RSTN_OFFSET_RSVD0                                                                               (11)
#define CRG_MAC_TX_RSTN_OFFSET_RSVD0_WIDTH                                                                         (21)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_0_TX_RSTN                                                                       (0)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_0_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_1_TX_RSTN                                                                       (1)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_1_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_2_TX_RSTN                                                                       (2)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_2_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_3_TX_RSTN                                                                       (3)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_3_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_4_TX_RSTN                                                                       (4)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_4_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_5_TX_RSTN                                                                       (5)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_5_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_6_TX_RSTN                                                                       (6)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_6_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_7_TX_RSTN                                                                       (7)
#define CRG_MAC_TX_RSTN_OFFSET_LMAC_7_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_SMAC_0_TX_RSTN                                                                       (8)
#define CRG_MAC_TX_RSTN_OFFSET_SMAC_0_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_SMAC_1_TX_RSTN                                                                       (9)
#define CRG_MAC_TX_RSTN_OFFSET_SMAC_1_TX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_TX_RSTN_OFFSET_CMAC_0_TX_RSTN                                                                      (10)
#define CRG_MAC_TX_RSTN_OFFSET_CMAC_0_TX_RSTN_WIDTH                                                                 (1)
typedef union CRG_MAC_TX_RSTN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 lmac_0_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_LMAC_0_TX_RSTN_WIDTH;                                             //[ 0: 0]
        jl_uint32 lmac_1_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_LMAC_1_TX_RSTN_WIDTH;                                             //[ 1: 1]
        jl_uint32 lmac_2_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_LMAC_2_TX_RSTN_WIDTH;                                             //[ 2: 2]
        jl_uint32 lmac_3_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_LMAC_3_TX_RSTN_WIDTH;                                             //[ 3: 3]
        jl_uint32 lmac_4_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_LMAC_4_TX_RSTN_WIDTH;                                             //[ 4: 4]
        jl_uint32 lmac_5_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_LMAC_5_TX_RSTN_WIDTH;                                             //[ 5: 5]
        jl_uint32 lmac_6_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_LMAC_6_TX_RSTN_WIDTH;                                             //[ 6: 6]
        jl_uint32 lmac_7_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_LMAC_7_TX_RSTN_WIDTH;                                             //[ 7: 7]
        jl_uint32 smac_0_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_SMAC_0_TX_RSTN_WIDTH;                                             //[ 8: 8]
        jl_uint32 smac_1_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_SMAC_1_TX_RSTN_WIDTH;                                             //[ 9: 9]
        jl_uint32 cmac_0_tx_rstn:CRG_MAC_TX_RSTN_OFFSET_CMAC_0_TX_RSTN_WIDTH;                                             //[10:10]
        jl_uint32 rsvd0:CRG_MAC_TX_RSTN_OFFSET_RSVD0_WIDTH;                                                               //[31:11]
    } BF;
    jl_uint32 val[CRG_MAC_TX_RSTN_ENTRY_SIZE];
} CRG_MAC_TX_RSTN_t;

#define CRG_MAC_RX_RSTN                                                                        ((jl_uint32)0x00202010U)
#define CRG_MAC_RX_RSTN_NUM                                                                    ((jl_uint32)0x00000001U)
#define CRG_MAC_RX_RSTN_ENTRY_SIZE                                                                                  (1)
#define CRG_MAC_RX_RSTN_OFFSET_RSVD0                                                                               (11)
#define CRG_MAC_RX_RSTN_OFFSET_RSVD0_WIDTH                                                                         (21)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_0_RX_RSTN                                                                       (0)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_0_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_1_RX_RSTN                                                                       (1)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_1_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_2_RX_RSTN                                                                       (2)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_2_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_3_RX_RSTN                                                                       (3)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_3_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_4_RX_RSTN                                                                       (4)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_4_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_5_RX_RSTN                                                                       (5)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_5_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_6_RX_RSTN                                                                       (6)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_6_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_7_RX_RSTN                                                                       (7)
#define CRG_MAC_RX_RSTN_OFFSET_LMAC_7_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_SMAC_0_RX_RSTN                                                                       (8)
#define CRG_MAC_RX_RSTN_OFFSET_SMAC_0_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_SMAC_1_RX_RSTN                                                                       (9)
#define CRG_MAC_RX_RSTN_OFFSET_SMAC_1_RX_RSTN_WIDTH                                                                 (1)
#define CRG_MAC_RX_RSTN_OFFSET_CMAC_0_RX_RSTN                                                                      (10)
#define CRG_MAC_RX_RSTN_OFFSET_CMAC_0_RX_RSTN_WIDTH                                                                 (1)
typedef union CRG_MAC_RX_RSTN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 lmac_0_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_LMAC_0_RX_RSTN_WIDTH;                                             //[ 0: 0]
        jl_uint32 lmac_1_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_LMAC_1_RX_RSTN_WIDTH;                                             //[ 1: 1]
        jl_uint32 lmac_2_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_LMAC_2_RX_RSTN_WIDTH;                                             //[ 2: 2]
        jl_uint32 lmac_3_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_LMAC_3_RX_RSTN_WIDTH;                                             //[ 3: 3]
        jl_uint32 lmac_4_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_LMAC_4_RX_RSTN_WIDTH;                                             //[ 4: 4]
        jl_uint32 lmac_5_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_LMAC_5_RX_RSTN_WIDTH;                                             //[ 5: 5]
        jl_uint32 lmac_6_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_LMAC_6_RX_RSTN_WIDTH;                                             //[ 6: 6]
        jl_uint32 lmac_7_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_LMAC_7_RX_RSTN_WIDTH;                                             //[ 7: 7]
        jl_uint32 smac_0_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_SMAC_0_RX_RSTN_WIDTH;                                             //[ 8: 8]
        jl_uint32 smac_1_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_SMAC_1_RX_RSTN_WIDTH;                                             //[ 9: 9]
        jl_uint32 cmac_0_rx_rstn:CRG_MAC_RX_RSTN_OFFSET_CMAC_0_RX_RSTN_WIDTH;                                             //[10:10]
        jl_uint32 rsvd0:CRG_MAC_RX_RSTN_OFFSET_RSVD0_WIDTH;                                                               //[31:11]
    } BF;
    jl_uint32 val[CRG_MAC_RX_RSTN_ENTRY_SIZE];
} CRG_MAC_RX_RSTN_t;

#define CRG_SAG_TX_RSTN                                                                        ((jl_uint32)0x00202014U)
#define CRG_SAG_TX_RSTN_NUM                                                                    ((jl_uint32)0x00000001U)
#define CRG_SAG_TX_RSTN_ENTRY_SIZE                                                                                  (1)
#define CRG_SAG_TX_RSTN_OFFSET_RSVD0                                                                               (10)
#define CRG_SAG_TX_RSTN_OFFSET_RSVD0_WIDTH                                                                         (22)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_0_TX_RSTN                                                                       (0)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_0_TX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_1_TX_RSTN                                                                       (1)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_1_TX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_2_TX_RSTN                                                                       (2)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_2_TX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_3_TX_RSTN                                                                       (3)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_3_TX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_4_TX_RSTN                                                                       (4)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_4_TX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_5_TX_RSTN                                                                       (5)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_5_TX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_6_TX_RSTN                                                                       (6)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_6_TX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_7_TX_RSTN                                                                       (7)
#define CRG_SAG_TX_RSTN_OFFSET_LADP_7_TX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_TX_RSTN_OFFSET_SADP_0_TX_RSTN                                                                       (8)
#define CRG_SAG_TX_RSTN_OFFSET_SADP_0_TX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_TX_RSTN_OFFSET_SADP_1_TX_RSTN                                                                       (9)
#define CRG_SAG_TX_RSTN_OFFSET_SADP_1_TX_RSTN_WIDTH                                                                 (1)
typedef union CRG_SAG_TX_RSTN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ladp_0_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_LADP_0_TX_RSTN_WIDTH;                                             //[ 0: 0]
        jl_uint32 ladp_1_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_LADP_1_TX_RSTN_WIDTH;                                             //[ 1: 1]
        jl_uint32 ladp_2_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_LADP_2_TX_RSTN_WIDTH;                                             //[ 2: 2]
        jl_uint32 ladp_3_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_LADP_3_TX_RSTN_WIDTH;                                             //[ 3: 3]
        jl_uint32 ladp_4_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_LADP_4_TX_RSTN_WIDTH;                                             //[ 4: 4]
        jl_uint32 ladp_5_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_LADP_5_TX_RSTN_WIDTH;                                             //[ 5: 5]
        jl_uint32 ladp_6_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_LADP_6_TX_RSTN_WIDTH;                                             //[ 6: 6]
        jl_uint32 ladp_7_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_LADP_7_TX_RSTN_WIDTH;                                             //[ 7: 7]
        jl_uint32 sadp_0_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_SADP_0_TX_RSTN_WIDTH;                                             //[ 8: 8]
        jl_uint32 sadp_1_tx_rstn:CRG_SAG_TX_RSTN_OFFSET_SADP_1_TX_RSTN_WIDTH;                                             //[ 9: 9]
        jl_uint32 rsvd0:CRG_SAG_TX_RSTN_OFFSET_RSVD0_WIDTH;                                                               //[31:10]
    } BF;
    jl_uint32 val[CRG_SAG_TX_RSTN_ENTRY_SIZE];
} CRG_SAG_TX_RSTN_t;

#define CRG_SAG_RX_RSTN                                                                        ((jl_uint32)0x00202018U)
#define CRG_SAG_RX_RSTN_NUM                                                                    ((jl_uint32)0x00000001U)
#define CRG_SAG_RX_RSTN_ENTRY_SIZE                                                                                  (1)
#define CRG_SAG_RX_RSTN_OFFSET_RSVD0                                                                               (10)
#define CRG_SAG_RX_RSTN_OFFSET_RSVD0_WIDTH                                                                         (22)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_0_RX_RSTN                                                                       (0)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_0_RX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_1_RX_RSTN                                                                       (1)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_1_RX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_2_RX_RSTN                                                                       (2)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_2_RX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_3_RX_RSTN                                                                       (3)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_3_RX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_4_RX_RSTN                                                                       (4)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_4_RX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_5_RX_RSTN                                                                       (5)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_5_RX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_6_RX_RSTN                                                                       (6)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_6_RX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_7_RX_RSTN                                                                       (7)
#define CRG_SAG_RX_RSTN_OFFSET_LADP_7_RX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_RX_RSTN_OFFSET_SADP_0_RX_RSTN                                                                       (8)
#define CRG_SAG_RX_RSTN_OFFSET_SADP_0_RX_RSTN_WIDTH                                                                 (1)
#define CRG_SAG_RX_RSTN_OFFSET_SADP_1_RX_RSTN                                                                       (9)
#define CRG_SAG_RX_RSTN_OFFSET_SADP_1_RX_RSTN_WIDTH                                                                 (1)
typedef union CRG_SAG_RX_RSTN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ladp_0_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_LADP_0_RX_RSTN_WIDTH;                                             //[ 0: 0]
        jl_uint32 ladp_1_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_LADP_1_RX_RSTN_WIDTH;                                             //[ 1: 1]
        jl_uint32 ladp_2_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_LADP_2_RX_RSTN_WIDTH;                                             //[ 2: 2]
        jl_uint32 ladp_3_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_LADP_3_RX_RSTN_WIDTH;                                             //[ 3: 3]
        jl_uint32 ladp_4_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_LADP_4_RX_RSTN_WIDTH;                                             //[ 4: 4]
        jl_uint32 ladp_5_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_LADP_5_RX_RSTN_WIDTH;                                             //[ 5: 5]
        jl_uint32 ladp_6_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_LADP_6_RX_RSTN_WIDTH;                                             //[ 6: 6]
        jl_uint32 ladp_7_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_LADP_7_RX_RSTN_WIDTH;                                             //[ 7: 7]
        jl_uint32 sadp_0_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_SADP_0_RX_RSTN_WIDTH;                                             //[ 8: 8]
        jl_uint32 sadp_1_rx_rstn:CRG_SAG_RX_RSTN_OFFSET_SADP_1_RX_RSTN_WIDTH;                                             //[ 9: 9]
        jl_uint32 rsvd0:CRG_SAG_RX_RSTN_OFFSET_RSVD0_WIDTH;                                                               //[31:10]
    } BF;
    jl_uint32 val[CRG_SAG_RX_RSTN_ENTRY_SIZE];
} CRG_SAG_RX_RSTN_t;

#define CRG_SWC_PTK_TX_RSTN                                                                    ((jl_uint32)0x0020201CU)
#define CRG_SWC_PTK_TX_RSTN_NUM                                                                ((jl_uint32)0x00000001U)
#define CRG_SWC_PTK_TX_RSTN_ENTRY_SIZE                                                                              (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_RSVD0                                                                           (11)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_RSVD0_WIDTH                                                                     (21)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_0_RSTN                                                                (0)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_0_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_1_RSTN                                                                (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_1_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_2_RSTN                                                                (2)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_2_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_3_RSTN                                                                (3)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_3_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_4_RSTN                                                                (4)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_4_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_5_RSTN                                                                (5)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_5_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_6_RSTN                                                                (6)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_6_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_7_RSTN                                                                (7)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_7_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_8_RSTN                                                                (8)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_8_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_9_RSTN                                                                (9)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_9_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_10_RSTN                                                              (10)
#define CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_10_RSTN_WIDTH                                                         (1)
typedef union CRG_SWC_PTK_TX_RSTN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 swc_pkt_tx_0_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_0_RSTN_WIDTH;                                   //[ 0: 0]
        jl_uint32 swc_pkt_tx_1_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_1_RSTN_WIDTH;                                   //[ 1: 1]
        jl_uint32 swc_pkt_tx_2_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_2_RSTN_WIDTH;                                   //[ 2: 2]
        jl_uint32 swc_pkt_tx_3_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_3_RSTN_WIDTH;                                   //[ 3: 3]
        jl_uint32 swc_pkt_tx_4_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_4_RSTN_WIDTH;                                   //[ 4: 4]
        jl_uint32 swc_pkt_tx_5_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_5_RSTN_WIDTH;                                   //[ 5: 5]
        jl_uint32 swc_pkt_tx_6_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_6_RSTN_WIDTH;                                   //[ 6: 6]
        jl_uint32 swc_pkt_tx_7_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_7_RSTN_WIDTH;                                   //[ 7: 7]
        jl_uint32 swc_pkt_tx_8_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_8_RSTN_WIDTH;                                   //[ 8: 8]
        jl_uint32 swc_pkt_tx_9_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_9_RSTN_WIDTH;                                   //[ 9: 9]
        jl_uint32 swc_pkt_tx_10_rstn:CRG_SWC_PTK_TX_RSTN_OFFSET_SWC_PKT_TX_10_RSTN_WIDTH;                                 //[10:10]
        jl_uint32 rsvd0:CRG_SWC_PTK_TX_RSTN_OFFSET_RSVD0_WIDTH;                                                           //[31:11]
    } BF;
    jl_uint32 val[CRG_SWC_PTK_TX_RSTN_ENTRY_SIZE];
} CRG_SWC_PTK_TX_RSTN_t;

#define CRG_SWC_PTK_RX_RSTN                                                                    ((jl_uint32)0x00202020U)
#define CRG_SWC_PTK_RX_RSTN_NUM                                                                ((jl_uint32)0x00000001U)
#define CRG_SWC_PTK_RX_RSTN_ENTRY_SIZE                                                                              (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_RSVD0                                                                           (11)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_RSVD0_WIDTH                                                                     (21)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_0_RSTN                                                                (0)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_0_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_1_RSTN                                                                (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_1_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_2_RSTN                                                                (2)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_2_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_3_RSTN                                                                (3)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_3_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_4_RSTN                                                                (4)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_4_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_5_RSTN                                                                (5)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_5_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_6_RSTN                                                                (6)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_6_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_7_RSTN                                                                (7)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_7_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_8_RSTN                                                                (8)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_8_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_9_RSTN                                                                (9)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_9_RSTN_WIDTH                                                          (1)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_10_RSTN                                                              (10)
#define CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_10_RSTN_WIDTH                                                         (1)
typedef union CRG_SWC_PTK_RX_RSTN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 swc_pkt_rx_0_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_0_RSTN_WIDTH;                                   //[ 0: 0]
        jl_uint32 swc_pkt_rx_1_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_1_RSTN_WIDTH;                                   //[ 1: 1]
        jl_uint32 swc_pkt_rx_2_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_2_RSTN_WIDTH;                                   //[ 2: 2]
        jl_uint32 swc_pkt_rx_3_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_3_RSTN_WIDTH;                                   //[ 3: 3]
        jl_uint32 swc_pkt_rx_4_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_4_RSTN_WIDTH;                                   //[ 4: 4]
        jl_uint32 swc_pkt_rx_5_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_5_RSTN_WIDTH;                                   //[ 5: 5]
        jl_uint32 swc_pkt_rx_6_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_6_RSTN_WIDTH;                                   //[ 6: 6]
        jl_uint32 swc_pkt_rx_7_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_7_RSTN_WIDTH;                                   //[ 7: 7]
        jl_uint32 swc_pkt_rx_8_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_8_RSTN_WIDTH;                                   //[ 8: 8]
        jl_uint32 swc_pkt_rx_9_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_9_RSTN_WIDTH;                                   //[ 9: 9]
        jl_uint32 swc_pkt_rx_10_rstn:CRG_SWC_PTK_RX_RSTN_OFFSET_SWC_PKT_RX_10_RSTN_WIDTH;                                 //[10:10]
        jl_uint32 rsvd0:CRG_SWC_PTK_RX_RSTN_OFFSET_RSVD0_WIDTH;                                                           //[31:11]
    } BF;
    jl_uint32 val[CRG_SWC_PTK_RX_RSTN_ENTRY_SIZE];
} CRG_SWC_PTK_RX_RSTN_t;

#define CRG_CCS_RST                                                                            ((jl_uint32)0x00202024U)
#define CRG_CCS_RST_NUM                                                                        ((jl_uint32)0x00000001U)
#define CRG_CCS_RST_ENTRY_SIZE                                                                                      (1)
#define CRG_CCS_RST_OFFSET_RSVD0                                                                                    (1)
#define CRG_CCS_RST_OFFSET_RSVD0_WIDTH                                                                             (31)
#define CRG_CCS_RST_OFFSET_CCS_RST                                                                                  (0)
#define CRG_CCS_RST_OFFSET_CCS_RST_WIDTH                                                                            (1)
typedef union CRG_CCS_RST_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ccs_rst:CRG_CCS_RST_OFFSET_CCS_RST_WIDTH;                                                               //[ 0: 0]
        jl_uint32 rsvd0:CRG_CCS_RST_OFFSET_RSVD0_WIDTH;                                                                   //[31: 1]
    } BF;
    jl_uint32 val[CRG_CCS_RST_ENTRY_SIZE];
} CRG_CCS_RST_t;

#define CRG_CLKGEN_CTL_11                                                                      ((jl_uint32)0x0020202CU)
#define CRG_CLKGEN_CTL_11_NUM                                                                  ((jl_uint32)0x00000001U)
#define CRG_CLKGEN_CTL_11_ENTRY_SIZE                                                                                (1)
#define CRG_CLKGEN_CTL_11_OFFSET_RSVD0                                                                             (16)
#define CRG_CLKGEN_CTL_11_OFFSET_RSVD0_WIDTH                                                                       (16)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_0_CLK_EN                                                                (0)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_0_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_0_CLK_EN                                                                (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_0_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_1_CLK_EN                                                                (2)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_1_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_1_CLK_EN                                                                (3)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_1_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_2_CLK_EN                                                                (4)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_2_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_2_CLK_EN                                                                (5)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_2_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_3_CLK_EN                                                                (6)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_3_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_3_CLK_EN                                                                (7)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_3_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_4_CLK_EN                                                                (8)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_4_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_4_CLK_EN                                                                (9)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_4_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_5_CLK_EN                                                               (10)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_5_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_5_CLK_EN                                                               (11)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_5_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_6_CLK_EN                                                               (12)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_6_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_6_CLK_EN                                                               (13)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_6_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_7_CLK_EN                                                               (14)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_7_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_7_CLK_EN                                                               (15)
#define CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_7_CLK_EN_WIDTH                                                          (1)
typedef union CRG_CLKGEN_CTL_11_u {
    struct __attribute__ ((packed)) {
        jl_uint32 sag_phy_tx_0_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_0_CLK_EN_WIDTH;                                 //[ 0: 0]
        jl_uint32 sag_phy_rx_0_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_0_CLK_EN_WIDTH;                                 //[ 1: 1]
        jl_uint32 sag_phy_tx_1_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_1_CLK_EN_WIDTH;                                 //[ 2: 2]
        jl_uint32 sag_phy_rx_1_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_1_CLK_EN_WIDTH;                                 //[ 3: 3]
        jl_uint32 sag_phy_tx_2_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_2_CLK_EN_WIDTH;                                 //[ 4: 4]
        jl_uint32 sag_phy_rx_2_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_2_CLK_EN_WIDTH;                                 //[ 5: 5]
        jl_uint32 sag_phy_tx_3_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_3_CLK_EN_WIDTH;                                 //[ 6: 6]
        jl_uint32 sag_phy_rx_3_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_3_CLK_EN_WIDTH;                                 //[ 7: 7]
        jl_uint32 sag_phy_tx_4_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_4_CLK_EN_WIDTH;                                 //[ 8: 8]
        jl_uint32 sag_phy_rx_4_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_4_CLK_EN_WIDTH;                                 //[ 9: 9]
        jl_uint32 sag_phy_tx_5_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_5_CLK_EN_WIDTH;                                 //[10:10]
        jl_uint32 sag_phy_rx_5_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_5_CLK_EN_WIDTH;                                 //[11:11]
        jl_uint32 sag_phy_tx_6_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_6_CLK_EN_WIDTH;                                 //[12:12]
        jl_uint32 sag_phy_rx_6_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_6_CLK_EN_WIDTH;                                 //[13:13]
        jl_uint32 sag_phy_tx_7_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_TX_7_CLK_EN_WIDTH;                                 //[14:14]
        jl_uint32 sag_phy_rx_7_clk_en:CRG_CLKGEN_CTL_11_OFFSET_SAG_PHY_RX_7_CLK_EN_WIDTH;                                 //[15:15]
        jl_uint32 rsvd0:CRG_CLKGEN_CTL_11_OFFSET_RSVD0_WIDTH;                                                             //[31:16]
    } BF;
    jl_uint32 val[CRG_CLKGEN_CTL_11_ENTRY_SIZE];
} CRG_CLKGEN_CTL_11_t;

#define CRG_CLKGEN_CTL_12                                                                      ((jl_uint32)0x00202030U)
#define CRG_CLKGEN_CTL_12_NUM                                                                  ((jl_uint32)0x00000001U)
#define CRG_CLKGEN_CTL_12_ENTRY_SIZE                                                                                (1)
#define CRG_CLKGEN_CTL_12_OFFSET_RSVD0                                                                              (4)
#define CRG_CLKGEN_CTL_12_OFFSET_RSVD0_WIDTH                                                                       (28)
#define CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_TX_0_CLK_EN                                                                (0)
#define CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_TX_0_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_RX_0_CLK_EN                                                                (1)
#define CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_RX_0_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_TX_1_CLK_EN                                                                (2)
#define CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_TX_1_CLK_EN_WIDTH                                                          (1)
#define CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_RX_1_CLK_EN                                                                (3)
#define CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_RX_1_CLK_EN_WIDTH                                                          (1)
typedef union CRG_CLKGEN_CTL_12_u {
    struct __attribute__ ((packed)) {
        jl_uint32 sag_sds_tx_0_clk_en:CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_TX_0_CLK_EN_WIDTH;                                 //[ 0: 0]
        jl_uint32 sag_sds_rx_0_clk_en:CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_RX_0_CLK_EN_WIDTH;                                 //[ 1: 1]
        jl_uint32 sag_sds_tx_1_clk_en:CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_TX_1_CLK_EN_WIDTH;                                 //[ 2: 2]
        jl_uint32 sag_sds_rx_1_clk_en:CRG_CLKGEN_CTL_12_OFFSET_SAG_SDS_RX_1_CLK_EN_WIDTH;                                 //[ 3: 3]
        jl_uint32 rsvd0:CRG_CLKGEN_CTL_12_OFFSET_RSVD0_WIDTH;                                                             //[31: 4]
    } BF;
    jl_uint32 val[CRG_CLKGEN_CTL_12_ENTRY_SIZE];
} CRG_CLKGEN_CTL_12_t;

#define CRG_CLKGEN_CTL_13                                                                      ((jl_uint32)0x00202034U)
#define CRG_CLKGEN_CTL_13_NUM                                                                  ((jl_uint32)0x00000001U)
#define CRG_CLKGEN_CTL_13_ENTRY_SIZE                                                                                (1)
#define CRG_CLKGEN_CTL_13_OFFSET_RSVD0                                                                              (8)
#define CRG_CLKGEN_CTL_13_OFFSET_RSVD0_WIDTH                                                                       (24)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_0_CLK_EN                                                                      (0)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_0_CLK_EN_WIDTH                                                                (1)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_1_CLK_EN                                                                      (1)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_1_CLK_EN_WIDTH                                                                (1)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_2_CLK_EN                                                                      (2)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_2_CLK_EN_WIDTH                                                                (1)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_3_CLK_EN                                                                      (3)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_3_CLK_EN_WIDTH                                                                (1)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_4_CLK_EN                                                                      (4)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_4_CLK_EN_WIDTH                                                                (1)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_5_CLK_EN                                                                      (5)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_5_CLK_EN_WIDTH                                                                (1)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_6_CLK_EN                                                                      (6)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_6_CLK_EN_WIDTH                                                                (1)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_7_CLK_EN                                                                      (7)
#define CRG_CLKGEN_CTL_13_OFFSET_LMAC_7_CLK_EN_WIDTH                                                                (1)
typedef union CRG_CLKGEN_CTL_13_u {
    struct __attribute__ ((packed)) {
        jl_uint32 lmac_0_clk_en:CRG_CLKGEN_CTL_13_OFFSET_LMAC_0_CLK_EN_WIDTH;                                             //[ 0: 0]
        jl_uint32 lmac_1_clk_en:CRG_CLKGEN_CTL_13_OFFSET_LMAC_1_CLK_EN_WIDTH;                                             //[ 1: 1]
        jl_uint32 lmac_2_clk_en:CRG_CLKGEN_CTL_13_OFFSET_LMAC_2_CLK_EN_WIDTH;                                             //[ 2: 2]
        jl_uint32 lmac_3_clk_en:CRG_CLKGEN_CTL_13_OFFSET_LMAC_3_CLK_EN_WIDTH;                                             //[ 3: 3]
        jl_uint32 lmac_4_clk_en:CRG_CLKGEN_CTL_13_OFFSET_LMAC_4_CLK_EN_WIDTH;                                             //[ 4: 4]
        jl_uint32 lmac_5_clk_en:CRG_CLKGEN_CTL_13_OFFSET_LMAC_5_CLK_EN_WIDTH;                                             //[ 5: 5]
        jl_uint32 lmac_6_clk_en:CRG_CLKGEN_CTL_13_OFFSET_LMAC_6_CLK_EN_WIDTH;                                             //[ 6: 6]
        jl_uint32 lmac_7_clk_en:CRG_CLKGEN_CTL_13_OFFSET_LMAC_7_CLK_EN_WIDTH;                                             //[ 7: 7]
        jl_uint32 rsvd0:CRG_CLKGEN_CTL_13_OFFSET_RSVD0_WIDTH;                                                             //[31: 8]
    } BF;
    jl_uint32 val[CRG_CLKGEN_CTL_13_ENTRY_SIZE];
} CRG_CLKGEN_CTL_13_t;

#define CRG_CLKGEN_CTL_14                                                                      ((jl_uint32)0x00202038U)
#define CRG_CLKGEN_CTL_14_NUM                                                                  ((jl_uint32)0x00000001U)
#define CRG_CLKGEN_CTL_14_ENTRY_SIZE                                                                                (1)
#define CRG_CLKGEN_CTL_14_OFFSET_RSVD0                                                                              (1)
#define CRG_CLKGEN_CTL_14_OFFSET_RSVD0_WIDTH                                                                       (31)
#define CRG_CLKGEN_CTL_14_OFFSET_CMAC_0_CLK_EN                                                                      (0)
#define CRG_CLKGEN_CTL_14_OFFSET_CMAC_0_CLK_EN_WIDTH                                                                (1)
typedef union CRG_CLKGEN_CTL_14_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cmac_0_clk_en:CRG_CLKGEN_CTL_14_OFFSET_CMAC_0_CLK_EN_WIDTH;                                             //[ 0: 0]
        jl_uint32 rsvd0:CRG_CLKGEN_CTL_14_OFFSET_RSVD0_WIDTH;                                                             //[31: 1]
    } BF;
    jl_uint32 val[CRG_CLKGEN_CTL_14_ENTRY_SIZE];
} CRG_CLKGEN_CTL_14_t;

#define CRG_CLKGEN_CTL_15                                                                      ((jl_uint32)0x0020203CU)
#define CRG_CLKGEN_CTL_15_NUM                                                                  ((jl_uint32)0x00000001U)
#define CRG_CLKGEN_CTL_15_ENTRY_SIZE                                                                                (1)
#define CRG_CLKGEN_CTL_15_OFFSET_RSVD0                                                                              (2)
#define CRG_CLKGEN_CTL_15_OFFSET_RSVD0_WIDTH                                                                       (30)
#define CRG_CLKGEN_CTL_15_OFFSET_SMAC_0_CLK_EN                                                                      (0)
#define CRG_CLKGEN_CTL_15_OFFSET_SMAC_0_CLK_EN_WIDTH                                                                (1)
#define CRG_CLKGEN_CTL_15_OFFSET_SMAC_1_CLK_EN                                                                      (1)
#define CRG_CLKGEN_CTL_15_OFFSET_SMAC_1_CLK_EN_WIDTH                                                                (1)
typedef union CRG_CLKGEN_CTL_15_u {
    struct __attribute__ ((packed)) {
        jl_uint32 smac_0_clk_en:CRG_CLKGEN_CTL_15_OFFSET_SMAC_0_CLK_EN_WIDTH;                                             //[ 0: 0]
        jl_uint32 smac_1_clk_en:CRG_CLKGEN_CTL_15_OFFSET_SMAC_1_CLK_EN_WIDTH;                                             //[ 1: 1]
        jl_uint32 rsvd0:CRG_CLKGEN_CTL_15_OFFSET_RSVD0_WIDTH;                                                             //[31: 2]
    } BF;
    jl_uint32 val[CRG_CLKGEN_CTL_15_ENTRY_SIZE];
} CRG_CLKGEN_CTL_15_t;

#define CRG_CLKGEN_CTL_16                                                                      ((jl_uint32)0x00202040U)
#define CRG_CLKGEN_CTL_16_NUM                                                                  ((jl_uint32)0x00000001U)
#define CRG_CLKGEN_CTL_16_ENTRY_SIZE                                                                                (1)
#define CRG_CLKGEN_CTL_16_OFFSET_RSVD0                                                                              (4)
#define CRG_CLKGEN_CTL_16_OFFSET_RSVD0_WIDTH                                                                       (28)
#define CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_TXCLK_OUT_0_CLK_EN                                                     (0)
#define CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_TXCLK_OUT_0_CLK_EN_WIDTH                                               (1)
#define CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_RXCLK_OUT_0_CLK_EN                                                     (1)
#define CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_RXCLK_OUT_0_CLK_EN_WIDTH                                               (1)
#define CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_TXCLK_OUT_1_CLK_EN                                                     (2)
#define CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_TXCLK_OUT_1_CLK_EN_WIDTH                                               (1)
#define CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_RXCLK_OUT_1_CLK_EN                                                     (3)
#define CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_RXCLK_OUT_1_CLK_EN_WIDTH                                               (1)
typedef union CRG_CLKGEN_CTL_16_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ext_sys_mii_txclk_out_0_clk_en:CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_TXCLK_OUT_0_CLK_EN_WIDTH;           //[ 0: 0]
        jl_uint32 ext_sys_mii_rxclk_out_0_clk_en:CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_RXCLK_OUT_0_CLK_EN_WIDTH;           //[ 1: 1]
        jl_uint32 ext_sys_mii_txclk_out_1_clk_en:CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_TXCLK_OUT_1_CLK_EN_WIDTH;           //[ 2: 2]
        jl_uint32 ext_sys_mii_rxclk_out_1_clk_en:CRG_CLKGEN_CTL_16_OFFSET_EXT_SYS_MII_RXCLK_OUT_1_CLK_EN_WIDTH;           //[ 3: 3]
        jl_uint32 rsvd0:CRG_CLKGEN_CTL_16_OFFSET_RSVD0_WIDTH;                                                             //[31: 4]
    } BF;
    jl_uint32 val[CRG_CLKGEN_CTL_16_ENTRY_SIZE];
} CRG_CLKGEN_CTL_16_t;

#define CRG_CLKGEN_CTL_17                                                                      ((jl_uint32)0x00202044U)
#define CRG_CLKGEN_CTL_17_NUM                                                                  ((jl_uint32)0x00000001U)
#define CRG_CLKGEN_CTL_17_ENTRY_SIZE                                                                                (1)
#define CRG_CLKGEN_CTL_17_OFFSET_RSVD0                                                                              (2)
#define CRG_CLKGEN_CTL_17_OFFSET_RSVD0_WIDTH                                                                       (30)
#define CRG_CLKGEN_CTL_17_OFFSET_EXT_SYS_RMII_REFCLK_OUT_0_CLK_EN                                                   (0)
#define CRG_CLKGEN_CTL_17_OFFSET_EXT_SYS_RMII_REFCLK_OUT_0_CLK_EN_WIDTH                                             (1)
#define CRG_CLKGEN_CTL_17_OFFSET_EXT_SYS_RMII_REFCLK_OUT_1_CLK_EN                                                   (1)
#define CRG_CLKGEN_CTL_17_OFFSET_EXT_SYS_RMII_REFCLK_OUT_1_CLK_EN_WIDTH                                             (1)
typedef union CRG_CLKGEN_CTL_17_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ext_sys_rmii_refclk_out_0_clk_en:CRG_CLKGEN_CTL_17_OFFSET_EXT_SYS_RMII_REFCLK_OUT_0_CLK_EN_WIDTH;       //[ 0: 0]
        jl_uint32 ext_sys_rmii_refclk_out_1_clk_en:CRG_CLKGEN_CTL_17_OFFSET_EXT_SYS_RMII_REFCLK_OUT_1_CLK_EN_WIDTH;       //[ 1: 1]
        jl_uint32 rsvd0:CRG_CLKGEN_CTL_17_OFFSET_RSVD0_WIDTH;                                                             //[31: 2]
    } BF;
    jl_uint32 val[CRG_CLKGEN_CTL_17_ENTRY_SIZE];
} CRG_CLKGEN_CTL_17_t;

#define CRG_CLKGEN_CTL_18                                                                      ((jl_uint32)0x00202048U)
#define CRG_CLKGEN_CTL_18_NUM                                                                  ((jl_uint32)0x00000001U)
#define CRG_CLKGEN_CTL_18_ENTRY_SIZE                                                                                (1)
#define CRG_CLKGEN_CTL_18_OFFSET_RSVD0                                                                              (4)
#define CRG_CLKGEN_CTL_18_OFFSET_RSVD0_WIDTH                                                                       (28)
#define CRG_CLKGEN_CTL_18_OFFSET_SADP_TX_0_CLK_EN                                                                   (0)
#define CRG_CLKGEN_CTL_18_OFFSET_SADP_TX_0_CLK_EN_WIDTH                                                             (1)
#define CRG_CLKGEN_CTL_18_OFFSET_SADP_RX_0_CLK_EN                                                                   (1)
#define CRG_CLKGEN_CTL_18_OFFSET_SADP_RX_0_CLK_EN_WIDTH                                                             (1)
#define CRG_CLKGEN_CTL_18_OFFSET_SADP_TX_1_CLK_EN                                                                   (2)
#define CRG_CLKGEN_CTL_18_OFFSET_SADP_TX_1_CLK_EN_WIDTH                                                             (1)
#define CRG_CLKGEN_CTL_18_OFFSET_SADP_RX_1_CLK_EN                                                                   (3)
#define CRG_CLKGEN_CTL_18_OFFSET_SADP_RX_1_CLK_EN_WIDTH                                                             (1)
typedef union CRG_CLKGEN_CTL_18_u {
    struct __attribute__ ((packed)) {
        jl_uint32 sadp_tx_0_clk_en:CRG_CLKGEN_CTL_18_OFFSET_SADP_TX_0_CLK_EN_WIDTH;                                       //[ 0: 0]
        jl_uint32 sadp_rx_0_clk_en:CRG_CLKGEN_CTL_18_OFFSET_SADP_RX_0_CLK_EN_WIDTH;                                       //[ 1: 1]
        jl_uint32 sadp_tx_1_clk_en:CRG_CLKGEN_CTL_18_OFFSET_SADP_TX_1_CLK_EN_WIDTH;                                       //[ 2: 2]
        jl_uint32 sadp_rx_1_clk_en:CRG_CLKGEN_CTL_18_OFFSET_SADP_RX_1_CLK_EN_WIDTH;                                       //[ 3: 3]
        jl_uint32 rsvd0:CRG_CLKGEN_CTL_18_OFFSET_RSVD0_WIDTH;                                                             //[31: 4]
    } BF;
    jl_uint32 val[CRG_CLKGEN_CTL_18_ENTRY_SIZE];
} CRG_CLKGEN_CTL_18_t;

#endif /* __JL_REG_CRG_H__ */

