//reg_phg_top.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_PHG_TOP_H__
#define __JL_REG_PHG_TOP_H__

#include <jl_types.h>

#define PHG_TOP_BASE                                                                           ((jl_uint32)0x00240100U)
#define PHG_TOP_BLOCK_SIZE                                                                     ((jl_uint32)0x00000400U)

#define PHG_TOP_TOP_RSVD0                                                                      ((jl_uint32)0x00240100U)
#define PHG_TOP_TOP_RSVD0_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD0_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD0_OFFSET_GEPHY_ENABLES                                                                      (0)
#define PHG_TOP_TOP_RSVD0_OFFSET_GEPHY_ENABLES_WIDTH                                                                (8)
#define PHG_TOP_TOP_RSVD0_OFFSET_SERDES_ENABLES                                                                     (8)
#define PHG_TOP_TOP_RSVD0_OFFSET_SERDES_ENABLES_WIDTH                                                               (2)
#define PHG_TOP_TOP_RSVD0_OFFSET_TOP_RSVD0                                                                         (10)
#define PHG_TOP_TOP_RSVD0_OFFSET_TOP_RSVD0_WIDTH                                                                    (5)
#define PHG_TOP_TOP_RSVD0_OFFSET_CONFIG_VALID                                                                      (15)
#define PHG_TOP_TOP_RSVD0_OFFSET_CONFIG_VALID_WIDTH                                                                 (1)
#define PHG_TOP_TOP_RSVD0_OFFSET_TOP_RSVD1                                                                         (16)
#define PHG_TOP_TOP_RSVD0_OFFSET_TOP_RSVD1_WIDTH                                                                   (15)
#define PHG_TOP_TOP_RSVD0_OFFSET_SOFTWARE_RESET                                                                    (31)
#define PHG_TOP_TOP_RSVD0_OFFSET_SOFTWARE_RESET_WIDTH                                                               (1)
typedef union PHG_TOP_TOP_RSVD0_u {
    struct __attribute__ ((packed)) {
    	jl_uint32 gephy_enables:PHG_TOP_TOP_RSVD0_OFFSET_GEPHY_ENABLES_WIDTH;                                             //[ 7: 0]
    	jl_uint32 serdes_enables:PHG_TOP_TOP_RSVD0_OFFSET_SERDES_ENABLES_WIDTH;                                           //[ 9: 8]
        jl_uint32 top_rsvd0:PHG_TOP_TOP_RSVD0_OFFSET_TOP_RSVD0_WIDTH;                                                     //[14:10]
        jl_uint32 config_valid:PHG_TOP_TOP_RSVD0_OFFSET_CONFIG_VALID_WIDTH;                                               //[15:15]
        jl_uint32 top_rsvd1:PHG_TOP_TOP_RSVD0_OFFSET_TOP_RSVD1_WIDTH;                                                     //[30:16]
        jl_uint32 software_reset:PHG_TOP_TOP_RSVD0_OFFSET_SOFTWARE_RESET_WIDTH;                                           //[31:31]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD0_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD0_t;

#define PHG_TOP_TOP_RSVD1                                                                      ((jl_uint32)0x00240104U)
#define PHG_TOP_TOP_RSVD1_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD1_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD1_OFFSET_TOP_RSVD1                                                                          (0)
#define PHG_TOP_TOP_RSVD1_OFFSET_TOP_RSVD1_WIDTH                                                                   (32)
typedef union PHG_TOP_TOP_RSVD1_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd1:PHG_TOP_TOP_RSVD1_OFFSET_TOP_RSVD1_WIDTH;                                                     //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD1_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD1_t;

#define PHG_TOP_TOP_RSVD2                                                                      ((jl_uint32)0x00240108U)
#define PHG_TOP_TOP_RSVD2_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD2_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD2_OFFSET_TOP_RSVD2                                                                          (0)
#define PHG_TOP_TOP_RSVD2_OFFSET_TOP_RSVD2_WIDTH                                                                   (32)
typedef union PHG_TOP_TOP_RSVD2_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd2:PHG_TOP_TOP_RSVD2_OFFSET_TOP_RSVD2_WIDTH;                                                     //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD2_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD2_t;

#define PHG_TOP_TOP_RSVD3                                                                      ((jl_uint32)0x0024010CU)
#define PHG_TOP_TOP_RSVD3_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD3_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD3_OFFSET_TOP_RSVD3                                                                          (0)
#define PHG_TOP_TOP_RSVD3_OFFSET_TOP_RSVD3_WIDTH                                                                   (32)
typedef union PHG_TOP_TOP_RSVD3_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd3:PHG_TOP_TOP_RSVD3_OFFSET_TOP_RSVD3_WIDTH;                                                     //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD3_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD3_t;

#define PHG_TOP_TOP_RSVD4                                                                      ((jl_uint32)0x00240110U)
#define PHG_TOP_TOP_RSVD4_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD4_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD4_OFFSET_TOP_RSVD4                                                                          (0)
#define PHG_TOP_TOP_RSVD4_OFFSET_TOP_RSVD4_WIDTH                                                                   (32)
typedef union PHG_TOP_TOP_RSVD4_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd4:PHG_TOP_TOP_RSVD4_OFFSET_TOP_RSVD4_WIDTH;                                                     //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD4_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD4_t;

#define PHG_TOP_TOP_RSVD5                                                                      ((jl_uint32)0x00240114U)
#define PHG_TOP_TOP_RSVD5_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD5_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD5_OFFSET_TOP_RSVD5                                                                          (0)
#define PHG_TOP_TOP_RSVD5_OFFSET_TOP_RSVD5_WIDTH                                                                   (32)
typedef union PHG_TOP_TOP_RSVD5_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd5:PHG_TOP_TOP_RSVD5_OFFSET_TOP_RSVD5_WIDTH;                                                     //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD5_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD5_t;

#define PHG_TOP_TOP_RSVD6                                                                      ((jl_uint32)0x00240118U)
#define PHG_TOP_TOP_RSVD6_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD6_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD6_OFFSET_TOP_RSVD6                                                                          (0)
#define PHG_TOP_TOP_RSVD6_OFFSET_TOP_RSVD6_WIDTH                                                                   (32)
typedef union PHG_TOP_TOP_RSVD6_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd6:PHG_TOP_TOP_RSVD6_OFFSET_TOP_RSVD6_WIDTH;                                                     //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD6_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD6_t;

#define PHG_TOP_TOP_RSVD7                                                                      ((jl_uint32)0x0024011CU)
#define PHG_TOP_TOP_RSVD7_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD7_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD7_OFFSET_TOP_RSVD7                                                                          (0)
#define PHG_TOP_TOP_RSVD7_OFFSET_TOP_RSVD7_WIDTH                                                                   (32)
typedef union PHG_TOP_TOP_RSVD7_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd7:PHG_TOP_TOP_RSVD7_OFFSET_TOP_RSVD7_WIDTH;                                                     //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD7_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD7_t;

#define PHG_TOP_TOP_RSVD8                                                                      ((jl_uint32)0x00240120U)
#define PHG_TOP_TOP_RSVD8_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD8_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD8_OFFSET_TOP_RSVD8                                                                          (0)
#define PHG_TOP_TOP_RSVD8_OFFSET_TOP_RSVD8_WIDTH                                                                   (32)
typedef union PHG_TOP_TOP_RSVD8_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd8:PHG_TOP_TOP_RSVD8_OFFSET_TOP_RSVD8_WIDTH;                                                     //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD8_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD8_t;

#define PHG_TOP_TOP_RSVD9                                                                      ((jl_uint32)0x00240124U)
#define PHG_TOP_TOP_RSVD9_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD9_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TOP_RSVD9_OFFSET_TOP_RSVD9                                                                          (0)
#define PHG_TOP_TOP_RSVD9_OFFSET_TOP_RSVD9_WIDTH                                                                   (32)
typedef union PHG_TOP_TOP_RSVD9_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd9:PHG_TOP_TOP_RSVD9_OFFSET_TOP_RSVD9_WIDTH;                                                     //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD9_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD9_t;

#define PHG_TOP_TOP_RSVD10                                                                     ((jl_uint32)0x00240128U)
#define PHG_TOP_TOP_RSVD10_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD10_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD10_OFFSET_TOP_RSVD10                                                                        (0)
#define PHG_TOP_TOP_RSVD10_OFFSET_TOP_RSVD10_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD10_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd10:PHG_TOP_TOP_RSVD10_OFFSET_TOP_RSVD10_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD10_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD10_t;

#define PHG_TOP_TOP_RSVD11                                                                     ((jl_uint32)0x0024012CU)
#define PHG_TOP_TOP_RSVD11_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD11_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD11_OFFSET_TOP_RSVD11                                                                        (0)
#define PHG_TOP_TOP_RSVD11_OFFSET_TOP_RSVD11_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD11_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd11:PHG_TOP_TOP_RSVD11_OFFSET_TOP_RSVD11_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD11_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD11_t;

#define PHG_TOP_TOP_RSVD12                                                                     ((jl_uint32)0x00240130U)
#define PHG_TOP_TOP_RSVD12_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD12_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD12_OFFSET_TOP_RSVD12                                                                        (0)
#define PHG_TOP_TOP_RSVD12_OFFSET_TOP_RSVD12_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD12_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd12:PHG_TOP_TOP_RSVD12_OFFSET_TOP_RSVD12_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD12_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD12_t;

#define PHG_TOP_TOP_RSVD13                                                                     ((jl_uint32)0x00240134U)
#define PHG_TOP_TOP_RSVD13_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD13_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD13_OFFSET_TOP_RSVD13                                                                        (0)
#define PHG_TOP_TOP_RSVD13_OFFSET_TOP_RSVD13_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD13_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd13:PHG_TOP_TOP_RSVD13_OFFSET_TOP_RSVD13_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD13_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD13_t;

#define PHG_TOP_TOP_RSVD14                                                                     ((jl_uint32)0x00240138U)
#define PHG_TOP_TOP_RSVD14_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD14_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD14_OFFSET_TOP_RSVD14                                                                        (0)
#define PHG_TOP_TOP_RSVD14_OFFSET_TOP_RSVD14_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD14_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd14:PHG_TOP_TOP_RSVD14_OFFSET_TOP_RSVD14_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD14_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD14_t;

#define PHG_TOP_TOP_RSVD15                                                                     ((jl_uint32)0x0024013CU)
#define PHG_TOP_TOP_RSVD15_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD15_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD15_OFFSET_TOP_RSVD15                                                                        (0)
#define PHG_TOP_TOP_RSVD15_OFFSET_TOP_RSVD15_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD15_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd15:PHG_TOP_TOP_RSVD15_OFFSET_TOP_RSVD15_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD15_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD15_t;

#define PHG_TOP_TOP_RSVD16                                                                     ((jl_uint32)0x00240140U)
#define PHG_TOP_TOP_RSVD16_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD16_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD16_OFFSET_TOP_RSVD16                                                                        (0)
#define PHG_TOP_TOP_RSVD16_OFFSET_TOP_RSVD16_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD16_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd16:PHG_TOP_TOP_RSVD16_OFFSET_TOP_RSVD16_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD16_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD16_t;

#define PHG_TOP_TOP_RSVD17                                                                     ((jl_uint32)0x00240144U)
#define PHG_TOP_TOP_RSVD17_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD17_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD17_OFFSET_TOP_RSVD17                                                                        (0)
#define PHG_TOP_TOP_RSVD17_OFFSET_TOP_RSVD17_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD17_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd17:PHG_TOP_TOP_RSVD17_OFFSET_TOP_RSVD17_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD17_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD17_t;

#define PHG_TOP_TOP_RSVD18                                                                     ((jl_uint32)0x00240148U)
#define PHG_TOP_TOP_RSVD18_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD18_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD18_OFFSET_TOP_RSVD18                                                                        (0)
#define PHG_TOP_TOP_RSVD18_OFFSET_TOP_RSVD18_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD18_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd18:PHG_TOP_TOP_RSVD18_OFFSET_TOP_RSVD18_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD18_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD18_t;

#define PHG_TOP_TOP_RSVD19                                                                     ((jl_uint32)0x0024014CU)
#define PHG_TOP_TOP_RSVD19_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD19_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD19_OFFSET_TOP_RSVD19                                                                        (0)
#define PHG_TOP_TOP_RSVD19_OFFSET_TOP_RSVD19_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD19_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd19:PHG_TOP_TOP_RSVD19_OFFSET_TOP_RSVD19_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD19_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD19_t;

#define PHG_TOP_TOP_RSVD20                                                                     ((jl_uint32)0x00240150U)
#define PHG_TOP_TOP_RSVD20_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD20_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD20_OFFSET_TOP_RSVD20                                                                        (0)
#define PHG_TOP_TOP_RSVD20_OFFSET_TOP_RSVD20_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD20_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd20:PHG_TOP_TOP_RSVD20_OFFSET_TOP_RSVD20_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD20_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD20_t;

#define PHG_TOP_TOP_RSVD21                                                                     ((jl_uint32)0x00240154U)
#define PHG_TOP_TOP_RSVD21_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD21_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD21_OFFSET_TOP_RSVD21                                                                        (0)
#define PHG_TOP_TOP_RSVD21_OFFSET_TOP_RSVD21_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD21_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd21:PHG_TOP_TOP_RSVD21_OFFSET_TOP_RSVD21_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD21_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD21_t;

#define PHG_TOP_TOP_RSVD22                                                                     ((jl_uint32)0x00240158U)
#define PHG_TOP_TOP_RSVD22_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD22_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD22_OFFSET_TOP_RSVD22                                                                        (0)
#define PHG_TOP_TOP_RSVD22_OFFSET_TOP_RSVD22_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD22_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd22:PHG_TOP_TOP_RSVD22_OFFSET_TOP_RSVD22_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD22_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD22_t;

#define PHG_TOP_TOP_RSVD23                                                                     ((jl_uint32)0x0024015CU)
#define PHG_TOP_TOP_RSVD23_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD23_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD23_OFFSET_TOP_RSVD23                                                                        (0)
#define PHG_TOP_TOP_RSVD23_OFFSET_TOP_RSVD23_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD23_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd23:PHG_TOP_TOP_RSVD23_OFFSET_TOP_RSVD23_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD23_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD23_t;

#define PHG_TOP_TOP_RSVD24                                                                     ((jl_uint32)0x00240160U)
#define PHG_TOP_TOP_RSVD24_NUM                                                                 ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_RSVD24_ENTRY_SIZE                                                                               (1)
#define PHG_TOP_TOP_RSVD24_OFFSET_TOP_RSVD24                                                                        (0)
#define PHG_TOP_TOP_RSVD24_OFFSET_TOP_RSVD24_WIDTH                                                                 (32)
typedef union PHG_TOP_TOP_RSVD24_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_rsvd24:PHG_TOP_TOP_RSVD24_OFFSET_TOP_RSVD24_WIDTH;                                                  //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_RSVD24_ENTRY_SIZE];
} PHG_TOP_TOP_RSVD24_t;

#define PHG_TOP_TEMP_SENS_CON                                                                  ((jl_uint32)0x00240180U)
#define PHG_TOP_TEMP_SENS_CON_NUM                                                              ((jl_uint32)0x00000001U)
#define PHG_TOP_TEMP_SENS_CON_ENTRY_SIZE                                                                            (1)
#define PHG_TOP_TEMP_SENS_CON_OFFSET_RSVD1                                                                         (16)
#define PHG_TOP_TEMP_SENS_CON_OFFSET_RSVD1_WIDTH                                                                   (16)
#define PHG_TOP_TEMP_SENS_CON_OFFSET_TSEN_AVG                                                                       (0)
#define PHG_TOP_TEMP_SENS_CON_OFFSET_TSEN_AVG_WIDTH                                                                 (1)
#define PHG_TOP_TEMP_SENS_CON_OFFSET_RSVD0                                                                          (1)
#define PHG_TOP_TEMP_SENS_CON_OFFSET_RSVD0_WIDTH                                                                   (14)
#define PHG_TOP_TEMP_SENS_CON_OFFSET_TSEN_DIG_RESETB                                                               (15)
#define PHG_TOP_TEMP_SENS_CON_OFFSET_TSEN_DIG_RESETB_WIDTH                                                          (1)
typedef union PHG_TOP_TEMP_SENS_CON_u {
    struct __attribute__ ((packed)) {
        jl_uint32 tsen_avg:PHG_TOP_TEMP_SENS_CON_OFFSET_TSEN_AVG_WIDTH;                                                   //[ 0: 0]
        jl_uint32 rsvd0:PHG_TOP_TEMP_SENS_CON_OFFSET_RSVD0_WIDTH;                                                         //[14: 1]
        jl_uint32 tsen_dig_resetb:PHG_TOP_TEMP_SENS_CON_OFFSET_TSEN_DIG_RESETB_WIDTH;                                     //[15:15]
        jl_uint32 rsvd1:PHG_TOP_TEMP_SENS_CON_OFFSET_RSVD1_WIDTH;                                                         //[31:16]
    } BF;
    jl_uint32 val[PHG_TOP_TEMP_SENS_CON_ENTRY_SIZE];
} PHG_TOP_TEMP_SENS_CON_t;

#define PHG_TOP_TEMP_SENS_RESULT                                                               ((jl_uint32)0x00240184U)
#define PHG_TOP_TEMP_SENS_RESULT_NUM                                                           ((jl_uint32)0x00000001U)
#define PHG_TOP_TEMP_SENS_RESULT_ENTRY_SIZE                                                                         (1)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_RSVD1                                                                      (16)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_RSVD1_WIDTH                                                                (16)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_TSEN_DOUT                                                                   (0)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_TSEN_DOUT_WIDTH                                                            (12)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_RSVD0                                                                      (12)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_RSVD0_WIDTH                                                                 (2)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_TRNG                                                                       (14)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_TRNG_WIDTH                                                                  (1)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_TSEN_DONE                                                                  (15)
#define PHG_TOP_TEMP_SENS_RESULT_OFFSET_TSEN_DONE_WIDTH                                                             (1)
typedef union PHG_TOP_TEMP_SENS_RESULT_u {
    struct __attribute__ ((packed)) {
        jl_uint32 tsen_dout:PHG_TOP_TEMP_SENS_RESULT_OFFSET_TSEN_DOUT_WIDTH;                                              //[11: 0]
        jl_uint32 rsvd0:PHG_TOP_TEMP_SENS_RESULT_OFFSET_RSVD0_WIDTH;                                                      //[13:12]
        jl_uint32 trng:PHG_TOP_TEMP_SENS_RESULT_OFFSET_TRNG_WIDTH;                                                        //[14:14]
        jl_uint32 tsen_done:PHG_TOP_TEMP_SENS_RESULT_OFFSET_TSEN_DONE_WIDTH;                                              //[15:15]
        jl_uint32 rsvd1:PHG_TOP_TEMP_SENS_RESULT_OFFSET_RSVD1_WIDTH;                                                      //[31:16]
    } BF;
    jl_uint32 val[PHG_TOP_TEMP_SENS_RESULT_ENTRY_SIZE];
} PHG_TOP_TEMP_SENS_RESULT_t;

#define PHG_TOP_TOP_SET                                                                        ((jl_uint32)0x00240188U)
#define PHG_TOP_TOP_SET_NUM                                                                    ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_SET_ENTRY_SIZE                                                                                  (1)
#define PHG_TOP_TOP_SET_OFFSET_RANDOM_OUT                                                                           (0)
#define PHG_TOP_TOP_SET_OFFSET_RANDOM_OUT_WIDTH                                                                     (1)
#define PHG_TOP_TOP_SET_OFFSET_CLK_TO_SWITCH_RDY                                                                    (1)
#define PHG_TOP_TOP_SET_OFFSET_CLK_TO_SWITCH_RDY_WIDTH                                                              (1)
#define PHG_TOP_TOP_SET_OFFSET_RSVD0                                                                                (2)
#define PHG_TOP_TOP_SET_OFFSET_RSVD0_WIDTH                                                                         (29)
#define PHG_TOP_TOP_SET_OFFSET_SOFTWARE_RESET_CLR                                                                  (31)
#define PHG_TOP_TOP_SET_OFFSET_SOFTWARE_RESET_CLR_WIDTH                                                             (1)
typedef union PHG_TOP_TOP_SET_u {
    struct __attribute__ ((packed)) {
        jl_uint32 random_out:PHG_TOP_TOP_SET_OFFSET_RANDOM_OUT_WIDTH;                                                     //[ 0: 0]
        jl_uint32 clk_to_switch_rdy:PHG_TOP_TOP_SET_OFFSET_CLK_TO_SWITCH_RDY_WIDTH;                                       //[ 1: 1]
        jl_uint32 rsvd0:PHG_TOP_TOP_SET_OFFSET_RSVD0_WIDTH;                                                               //[30: 2]
        jl_uint32 software_reset_clr:PHG_TOP_TOP_SET_OFFSET_SOFTWARE_RESET_CLR_WIDTH;                                     //[31:31]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_SET_ENTRY_SIZE];
} PHG_TOP_TOP_SET_t;

#define PHG_TOP_MISC_CTRL                                                                      ((jl_uint32)0x0024018CU)
#define PHG_TOP_MISC_CTRL_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_MISC_CTRL_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_MISC_CTRL_OFFSET_RSVD0                                                                             (11)
#define PHG_TOP_MISC_CTRL_OFFSET_RSVD0_WIDTH                                                                       (21)
#define PHG_TOP_MISC_CTRL_OFFSET_DBG_SEL                                                                            (0)
#define PHG_TOP_MISC_CTRL_OFFSET_DBG_SEL_WIDTH                                                                      (4)
#define PHG_TOP_MISC_CTRL_OFFSET_ROM_EMA                                                                            (4)
#define PHG_TOP_MISC_CTRL_OFFSET_ROM_EMA_WIDTH                                                                      (3)
#define PHG_TOP_MISC_CTRL_OFFSET_RAM_EMA                                                                            (7)
#define PHG_TOP_MISC_CTRL_OFFSET_RAM_EMA_WIDTH                                                                      (3)
#define PHG_TOP_MISC_CTRL_OFFSET_DBG_IN_CLK_INV_SEL                                                                (10)
#define PHG_TOP_MISC_CTRL_OFFSET_DBG_IN_CLK_INV_SEL_WIDTH                                                           (1)
typedef union PHG_TOP_MISC_CTRL_u {
    struct __attribute__ ((packed)) {
        jl_uint32 dbg_sel:PHG_TOP_MISC_CTRL_OFFSET_DBG_SEL_WIDTH;                                                         //[ 3: 0]
        jl_uint32 rom_ema:PHG_TOP_MISC_CTRL_OFFSET_ROM_EMA_WIDTH;                                                         //[ 6: 4]
        jl_uint32 ram_ema:PHG_TOP_MISC_CTRL_OFFSET_RAM_EMA_WIDTH;                                                         //[ 9: 7]
        jl_uint32 dbg_in_clk_inv_sel:PHG_TOP_MISC_CTRL_OFFSET_DBG_IN_CLK_INV_SEL_WIDTH;                                   //[10:10]
        jl_uint32 rsvd0:PHG_TOP_MISC_CTRL_OFFSET_RSVD0_WIDTH;                                                             //[31:11]
    } BF;
    jl_uint32 val[PHG_TOP_MISC_CTRL_ENTRY_SIZE];
} PHG_TOP_MISC_CTRL_t;

#define PHG_TOP_CORE_CTRL                                                                      ((jl_uint32)0x00240190U)
#define PHG_TOP_CORE_CTRL_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_CORE_CTRL_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_CORE_CTRL_OFFSET_RSVD0                                                                             (24)
#define PHG_TOP_CORE_CTRL_OFFSET_RSVD0_WIDTH                                                                        (8)
#define PHG_TOP_CORE_CTRL_OFFSET_SYS_IOMEM_ENC_ADDR                                                                 (0)
#define PHG_TOP_CORE_CTRL_OFFSET_SYS_IOMEM_ENC_ADDR_WIDTH                                                          (16)
#define PHG_TOP_CORE_CTRL_OFFSET_CFG_APB_TIMEOUT                                                                   (16)
#define PHG_TOP_CORE_CTRL_OFFSET_CFG_APB_TIMEOUT_WIDTH                                                              (8)
typedef union PHG_TOP_CORE_CTRL_u {
    struct __attribute__ ((packed)) {
        jl_uint32 sys_iomem_enc_addr:PHG_TOP_CORE_CTRL_OFFSET_SYS_IOMEM_ENC_ADDR_WIDTH;                                   //[15: 0]
        jl_uint32 cfg_apb_timeout:PHG_TOP_CORE_CTRL_OFFSET_CFG_APB_TIMEOUT_WIDTH;                                         //[23:16]
        jl_uint32 rsvd0:PHG_TOP_CORE_CTRL_OFFSET_RSVD0_WIDTH;                                                             //[31:24]
    } BF;
    jl_uint32 val[PHG_TOP_CORE_CTRL_ENTRY_SIZE];
} PHG_TOP_CORE_CTRL_t;

#define PHG_TOP_CPU_PC                                                                         ((jl_uint32)0x00240194U)
#define PHG_TOP_CPU_PC_NUM                                                                     ((jl_uint32)0x00000001U)
#define PHG_TOP_CPU_PC_ENTRY_SIZE                                                                                   (1)
#define PHG_TOP_CPU_PC_OFFSET_CPU_PC                                                                                (0)
#define PHG_TOP_CPU_PC_OFFSET_CPU_PC_WIDTH                                                                         (32)
typedef union PHG_TOP_CPU_PC_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cpu_pc:PHG_TOP_CPU_PC_OFFSET_CPU_PC_WIDTH;                                                              //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_CPU_PC_ENTRY_SIZE];
} PHG_TOP_CPU_PC_t;

#define PHG_TOP_TOP_CLK_RSTN                                                                   ((jl_uint32)0x00240198U)
#define PHG_TOP_TOP_CLK_RSTN_NUM                                                               ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_CLK_RSTN_ENTRY_SIZE                                                                             (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY0_CLK_EN                                                                   (0)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY0_CLK_EN_WIDTH                                                             (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY1_CLK_EN                                                                   (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY1_CLK_EN_WIDTH                                                             (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY2_CLK_EN                                                                   (2)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY2_CLK_EN_WIDTH                                                             (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY3_CLK_EN                                                                   (3)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY3_CLK_EN_WIDTH                                                             (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY4_CLK_EN                                                                   (4)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY4_CLK_EN_WIDTH                                                             (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY5_CLK_EN                                                                   (5)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY5_CLK_EN_WIDTH                                                             (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY6_CLK_EN                                                                   (6)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY6_CLK_EN_WIDTH                                                             (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY7_CLK_EN                                                                   (7)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY7_CLK_EN_WIDTH                                                             (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_RSVD1                                                                           (8)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_RSVD1_WIDTH                                                                     (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_TOP_RF_SW_RSTN                                                                  (9)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_TOP_RF_SW_RSTN_WIDTH                                                            (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_RSVD0                                                                          (10)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_RSVD0_WIDTH                                                                     (2)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_SERDES0_RSTN                                                                   (12)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_SERDES0_RSTN_WIDTH                                                              (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_SERDES1_RSTN                                                                   (13)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_SERDES1_RSTN_WIDTH                                                              (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_TOP_RSTN_CPU                                                                   (14)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_TOP_RSTN_CPU_WIDTH                                                              (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_TOP_CLK_CPU_EN                                                                 (15)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_TOP_CLK_CPU_EN_WIDTH                                                            (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY0_RSTN_PHY                                                                (16)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY0_RSTN_PHY_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY1_RSTN_PHY                                                                (17)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY1_RSTN_PHY_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY2_RSTN_PHY                                                                (18)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY2_RSTN_PHY_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY3_RSTN_PHY                                                                (19)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY3_RSTN_PHY_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY4_RSTN_PHY                                                                (20)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY4_RSTN_PHY_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY5_RSTN_PHY                                                                (21)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY5_RSTN_PHY_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY6_RSTN_PHY                                                                (22)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY6_RSTN_PHY_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY7_RSTN_PHY                                                                (23)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY7_RSTN_PHY_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY0_RSTN_MCU                                                                (24)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY0_RSTN_MCU_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY1_RSTN_MCU                                                                (25)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY1_RSTN_MCU_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY2_RSTN_MCU                                                                (26)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY2_RSTN_MCU_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY3_RSTN_MCU                                                                (27)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY3_RSTN_MCU_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY4_RSTN_MCU                                                                (28)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY4_RSTN_MCU_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY5_RSTN_MCU                                                                (29)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY5_RSTN_MCU_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY6_RSTN_MCU                                                                (30)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY6_RSTN_MCU_WIDTH                                                           (1)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY7_RSTN_MCU                                                                (31)
#define PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY7_RSTN_MCU_WIDTH                                                           (1)
typedef union PHG_TOP_TOP_CLK_RSTN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 gephy0_clk_en:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY0_CLK_EN_WIDTH;                                          //[ 0: 0]
        jl_uint32 gephy1_clk_en:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY1_CLK_EN_WIDTH;                                          //[ 1: 1]
        jl_uint32 gephy2_clk_en:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY2_CLK_EN_WIDTH;                                          //[ 2: 2]
        jl_uint32 gephy3_clk_en:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY3_CLK_EN_WIDTH;                                          //[ 3: 3]
        jl_uint32 gephy4_clk_en:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY4_CLK_EN_WIDTH;                                          //[ 4: 4]
        jl_uint32 gephy5_clk_en:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY5_CLK_EN_WIDTH;                                          //[ 5: 5]
        jl_uint32 gephy6_clk_en:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY6_CLK_EN_WIDTH;                                          //[ 6: 6]
        jl_uint32 gephy7_clk_en:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY7_CLK_EN_WIDTH;                                          //[ 7: 7]
        jl_uint32 rsvd1:PHG_TOP_TOP_CLK_RSTN_OFFSET_RSVD1_WIDTH;                                                          //[ 8: 8]
        jl_uint32 top_rf_sw_rstn:PHG_TOP_TOP_CLK_RSTN_OFFSET_TOP_RF_SW_RSTN_WIDTH;                                        //[ 9: 9]
        jl_uint32 rsvd0:PHG_TOP_TOP_CLK_RSTN_OFFSET_RSVD0_WIDTH;                                                          //[11:10]
        jl_uint32 serdes0_rstn:PHG_TOP_TOP_CLK_RSTN_OFFSET_SERDES0_RSTN_WIDTH;                                            //[12:12]
        jl_uint32 serdes1_rstn:PHG_TOP_TOP_CLK_RSTN_OFFSET_SERDES1_RSTN_WIDTH;                                            //[13:13]
        jl_uint32 top_rstn_cpu:PHG_TOP_TOP_CLK_RSTN_OFFSET_TOP_RSTN_CPU_WIDTH;                                            //[14:14]
        jl_uint32 top_clk_cpu_en:PHG_TOP_TOP_CLK_RSTN_OFFSET_TOP_CLK_CPU_EN_WIDTH;                                        //[15:15]
        jl_uint32 gephy0_rstn_phy:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY0_RSTN_PHY_WIDTH;                                      //[16:16]
        jl_uint32 gephy1_rstn_phy:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY1_RSTN_PHY_WIDTH;                                      //[17:17]
        jl_uint32 gephy2_rstn_phy:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY2_RSTN_PHY_WIDTH;                                      //[18:18]
        jl_uint32 gephy3_rstn_phy:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY3_RSTN_PHY_WIDTH;                                      //[19:19]
        jl_uint32 gephy4_rstn_phy:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY4_RSTN_PHY_WIDTH;                                      //[20:20]
        jl_uint32 gephy5_rstn_phy:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY5_RSTN_PHY_WIDTH;                                      //[21:21]
        jl_uint32 gephy6_rstn_phy:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY6_RSTN_PHY_WIDTH;                                      //[22:22]
        jl_uint32 gephy7_rstn_phy:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY7_RSTN_PHY_WIDTH;                                      //[23:23]
        jl_uint32 gephy0_rstn_mcu:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY0_RSTN_MCU_WIDTH;                                      //[24:24]
        jl_uint32 gephy1_rstn_mcu:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY1_RSTN_MCU_WIDTH;                                      //[25:25]
        jl_uint32 gephy2_rstn_mcu:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY2_RSTN_MCU_WIDTH;                                      //[26:26]
        jl_uint32 gephy3_rstn_mcu:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY3_RSTN_MCU_WIDTH;                                      //[27:27]
        jl_uint32 gephy4_rstn_mcu:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY4_RSTN_MCU_WIDTH;                                      //[28:28]
        jl_uint32 gephy5_rstn_mcu:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY5_RSTN_MCU_WIDTH;                                      //[29:29]
        jl_uint32 gephy6_rstn_mcu:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY6_RSTN_MCU_WIDTH;                                      //[30:30]
        jl_uint32 gephy7_rstn_mcu:PHG_TOP_TOP_CLK_RSTN_OFFSET_GEPHY7_RSTN_MCU_WIDTH;                                      //[31:31]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_CLK_RSTN_ENTRY_SIZE];
} PHG_TOP_TOP_CLK_RSTN_t;

#define PHG_TOP_TIMER_MATCH                                                                    ((jl_uint32)0x0024019CU)
#define PHG_TOP_TIMER_MATCH_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TIMER_MATCH_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TIMER_MATCH_OFFSET_RSVD0                                                                           (16)
#define PHG_TOP_TIMER_MATCH_OFFSET_RSVD0_WIDTH                                                                     (16)
#define PHG_TOP_TIMER_MATCH_OFFSET_TIMER_MATCH                                                                      (0)
#define PHG_TOP_TIMER_MATCH_OFFSET_TIMER_MATCH_WIDTH                                                               (16)
typedef union PHG_TOP_TIMER_MATCH_u {
    struct __attribute__ ((packed)) {
        jl_uint32 timer_match:PHG_TOP_TIMER_MATCH_OFFSET_TIMER_MATCH_WIDTH;                                               //[15: 0]
        jl_uint32 rsvd0:PHG_TOP_TIMER_MATCH_OFFSET_RSVD0_WIDTH;                                                           //[31:16]
    } BF;
    jl_uint32 val[PHG_TOP_TIMER_MATCH_ENTRY_SIZE];
} PHG_TOP_TIMER_MATCH_t;

#define PHG_TOP_TIMER                                                                          ((jl_uint32)0x002401A0U)
#define PHG_TOP_TIMER_NUM                                                                      ((jl_uint32)0x00000001U)
#define PHG_TOP_TIMER_ENTRY_SIZE                                                                                    (1)
#define PHG_TOP_TIMER_OFFSET_RSVD0                                                                                 (16)
#define PHG_TOP_TIMER_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PHG_TOP_TIMER_OFFSET_TIMER                                                                                  (0)
#define PHG_TOP_TIMER_OFFSET_TIMER_WIDTH                                                                           (16)
typedef union PHG_TOP_TIMER_u {
    struct __attribute__ ((packed)) {
        jl_uint32 timer:PHG_TOP_TIMER_OFFSET_TIMER_WIDTH;                                                                 //[15: 0]
        jl_uint32 rsvd0:PHG_TOP_TIMER_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PHG_TOP_TIMER_ENTRY_SIZE];
} PHG_TOP_TIMER_t;

#define PHG_TOP_TIMER_CFG                                                                      ((jl_uint32)0x002401A4U)
#define PHG_TOP_TIMER_CFG_NUM                                                                  ((jl_uint32)0x00000001U)
#define PHG_TOP_TIMER_CFG_ENTRY_SIZE                                                                                (1)
#define PHG_TOP_TIMER_CFG_OFFSET_RSVD0                                                                              (5)
#define PHG_TOP_TIMER_CFG_OFFSET_RSVD0_WIDTH                                                                       (27)
#define PHG_TOP_TIMER_CFG_OFFSET_TIMER_INTERVAL                                                                     (0)
#define PHG_TOP_TIMER_CFG_OFFSET_TIMER_INTERVAL_WIDTH                                                               (2)
#define PHG_TOP_TIMER_CFG_OFFSET_TIMER_CLR                                                                          (2)
#define PHG_TOP_TIMER_CFG_OFFSET_TIMER_CLR_WIDTH                                                                    (1)
#define PHG_TOP_TIMER_CFG_OFFSET_TIMER_EN                                                                           (3)
#define PHG_TOP_TIMER_CFG_OFFSET_TIMER_EN_WIDTH                                                                     (1)
#define PHG_TOP_TIMER_CFG_OFFSET_TIMER_MODE                                                                         (4)
#define PHG_TOP_TIMER_CFG_OFFSET_TIMER_MODE_WIDTH                                                                   (1)
typedef union PHG_TOP_TIMER_CFG_u {
    struct __attribute__ ((packed)) {
        jl_uint32 timer_interval:PHG_TOP_TIMER_CFG_OFFSET_TIMER_INTERVAL_WIDTH;                                           //[ 1: 0]
        jl_uint32 timer_clr:PHG_TOP_TIMER_CFG_OFFSET_TIMER_CLR_WIDTH;                                                     //[ 2: 2]
        jl_uint32 timer_en:PHG_TOP_TIMER_CFG_OFFSET_TIMER_EN_WIDTH;                                                       //[ 3: 3]
        jl_uint32 timer_mode:PHG_TOP_TIMER_CFG_OFFSET_TIMER_MODE_WIDTH;                                                   //[ 4: 4]
        jl_uint32 rsvd0:PHG_TOP_TIMER_CFG_OFFSET_RSVD0_WIDTH;                                                             //[31: 5]
    } BF;
    jl_uint32 val[PHG_TOP_TIMER_CFG_ENTRY_SIZE];
} PHG_TOP_TIMER_CFG_t;

#define PHG_TOP_WATCH                                                                          ((jl_uint32)0x002401A8U)
#define PHG_TOP_WATCH_NUM                                                                      ((jl_uint32)0x00000001U)
#define PHG_TOP_WATCH_ENTRY_SIZE                                                                                    (1)
#define PHG_TOP_WATCH_OFFSET_RSVD0                                                                                  (2)
#define PHG_TOP_WATCH_OFFSET_RSVD0_WIDTH                                                                           (30)
#define PHG_TOP_WATCH_OFFSET_WATCHDOG_EN                                                                            (0)
#define PHG_TOP_WATCH_OFFSET_WATCHDOG_EN_WIDTH                                                                      (1)
#define PHG_TOP_WATCH_OFFSET_CPU_RESET                                                                              (1)
#define PHG_TOP_WATCH_OFFSET_CPU_RESET_WIDTH                                                                        (1)
typedef union PHG_TOP_WATCH_u {
    struct __attribute__ ((packed)) {
        jl_uint32 watchdog_en:PHG_TOP_WATCH_OFFSET_WATCHDOG_EN_WIDTH;                                                     //[ 0: 0]
        jl_uint32 cpu_reset:PHG_TOP_WATCH_OFFSET_CPU_RESET_WIDTH;                                                         //[ 1: 1]
        jl_uint32 rsvd0:PHG_TOP_WATCH_OFFSET_RSVD0_WIDTH;                                                                 //[31: 2]
    } BF;
    jl_uint32 val[PHG_TOP_WATCH_ENTRY_SIZE];
} PHG_TOP_WATCH_t;

#define PHG_TOP_CPU_HOTFIX_ADDR                                                                ((jl_uint32)0x002401ACU)
#define PHG_TOP_CPU_HOTFIX_ADDR_NUM                                                            ((jl_uint32)0x00000001U)
#define PHG_TOP_CPU_HOTFIX_ADDR_ENTRY_SIZE                                                                          (1)
#define PHG_TOP_CPU_HOTFIX_ADDR_OFFSET_FIXUP_ADDR1                                                                  (0)
#define PHG_TOP_CPU_HOTFIX_ADDR_OFFSET_FIXUP_ADDR1_WIDTH                                                           (16)
#define PHG_TOP_CPU_HOTFIX_ADDR_OFFSET_FIXUP_ADDR0                                                                 (16)
#define PHG_TOP_CPU_HOTFIX_ADDR_OFFSET_FIXUP_ADDR0_WIDTH                                                           (16)
typedef union PHG_TOP_CPU_HOTFIX_ADDR_u {
    struct __attribute__ ((packed)) {
        jl_uint32 fixup_addr1:PHG_TOP_CPU_HOTFIX_ADDR_OFFSET_FIXUP_ADDR1_WIDTH;                                           //[15: 0]
        jl_uint32 fixup_addr0:PHG_TOP_CPU_HOTFIX_ADDR_OFFSET_FIXUP_ADDR0_WIDTH;                                           //[31:16]
    } BF;
    jl_uint32 val[PHG_TOP_CPU_HOTFIX_ADDR_ENTRY_SIZE];
} PHG_TOP_CPU_HOTFIX_ADDR_t;

#define PHG_TOP_CPU_HOTFIX_DATA                                                                ((jl_uint32)0x002401B0U)
#define PHG_TOP_CPU_HOTFIX_DATA_NUM                                                            ((jl_uint32)0x00000001U)
#define PHG_TOP_CPU_HOTFIX_DATA_ENTRY_SIZE                                                                          (1)
#define PHG_TOP_CPU_HOTFIX_DATA_OFFSET_FIXUP_DATA0                                                                  (0)
#define PHG_TOP_CPU_HOTFIX_DATA_OFFSET_FIXUP_DATA0_WIDTH                                                           (32)
typedef union PHG_TOP_CPU_HOTFIX_DATA_u {
    struct __attribute__ ((packed)) {
        jl_uint32 fixup_data0:PHG_TOP_CPU_HOTFIX_DATA_OFFSET_FIXUP_DATA0_WIDTH;                                           //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_CPU_HOTFIX_DATA_ENTRY_SIZE];
} PHG_TOP_CPU_HOTFIX_DATA_t;

#define PHG_TOP_CPU_HOTFIX_DATA1                                                               ((jl_uint32)0x002401B4U)
#define PHG_TOP_CPU_HOTFIX_DATA1_NUM                                                           ((jl_uint32)0x00000001U)
#define PHG_TOP_CPU_HOTFIX_DATA1_ENTRY_SIZE                                                                         (1)
#define PHG_TOP_CPU_HOTFIX_DATA1_OFFSET_FIXUP_DATA1                                                                 (0)
#define PHG_TOP_CPU_HOTFIX_DATA1_OFFSET_FIXUP_DATA1_WIDTH                                                          (32)
typedef union PHG_TOP_CPU_HOTFIX_DATA1_u {
    struct __attribute__ ((packed)) {
        jl_uint32 fixup_data1:PHG_TOP_CPU_HOTFIX_DATA1_OFFSET_FIXUP_DATA1_WIDTH;                                          //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_CPU_HOTFIX_DATA1_ENTRY_SIZE];
} PHG_TOP_CPU_HOTFIX_DATA1_t;

#define PHG_TOP_TOP_LOGGER0                                                                    ((jl_uint32)0x002401B8U)
#define PHG_TOP_TOP_LOGGER0_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER0_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER0_OFFSET_TOP_LOGGER0                                                                      (0)
#define PHG_TOP_TOP_LOGGER0_OFFSET_TOP_LOGGER0_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER0_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger0:PHG_TOP_TOP_LOGGER0_OFFSET_TOP_LOGGER0_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER0_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER0_t;

#define PHG_TOP_TOP_LOGGER1                                                                    ((jl_uint32)0x002401BCU)
#define PHG_TOP_TOP_LOGGER1_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER1_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER1_OFFSET_TOP_LOGGER1                                                                      (0)
#define PHG_TOP_TOP_LOGGER1_OFFSET_TOP_LOGGER1_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER1_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger1:PHG_TOP_TOP_LOGGER1_OFFSET_TOP_LOGGER1_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER1_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER1_t;

#define PHG_TOP_TOP_LOGGER2                                                                    ((jl_uint32)0x002401C0U)
#define PHG_TOP_TOP_LOGGER2_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER2_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER2_OFFSET_TOP_LOGGER2                                                                      (0)
#define PHG_TOP_TOP_LOGGER2_OFFSET_TOP_LOGGER2_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER2_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger2:PHG_TOP_TOP_LOGGER2_OFFSET_TOP_LOGGER2_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER2_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER2_t;

#define PHG_TOP_TOP_LOGGER3                                                                    ((jl_uint32)0x002401C4U)
#define PHG_TOP_TOP_LOGGER3_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER3_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER3_OFFSET_TOP_LOGGER3                                                                      (0)
#define PHG_TOP_TOP_LOGGER3_OFFSET_TOP_LOGGER3_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER3_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger3:PHG_TOP_TOP_LOGGER3_OFFSET_TOP_LOGGER3_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER3_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER3_t;

#define PHG_TOP_TOP_LOGGER4                                                                    ((jl_uint32)0x002401C8U)
#define PHG_TOP_TOP_LOGGER4_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER4_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER4_OFFSET_TOP_LOGGER4                                                                      (0)
#define PHG_TOP_TOP_LOGGER4_OFFSET_TOP_LOGGER4_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER4_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger4:PHG_TOP_TOP_LOGGER4_OFFSET_TOP_LOGGER4_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER4_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER4_t;

#define PHG_TOP_TOP_LOGGER5                                                                    ((jl_uint32)0x002401CCU)
#define PHG_TOP_TOP_LOGGER5_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER5_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER5_OFFSET_TOP_LOGGER5                                                                      (0)
#define PHG_TOP_TOP_LOGGER5_OFFSET_TOP_LOGGER5_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER5_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger5:PHG_TOP_TOP_LOGGER5_OFFSET_TOP_LOGGER5_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER5_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER5_t;

#define PHG_TOP_TOP_LOGGER6                                                                    ((jl_uint32)0x002401D0U)
#define PHG_TOP_TOP_LOGGER6_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER6_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER6_OFFSET_TOP_LOGGER6                                                                      (0)
#define PHG_TOP_TOP_LOGGER6_OFFSET_TOP_LOGGER6_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER6_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger6:PHG_TOP_TOP_LOGGER6_OFFSET_TOP_LOGGER6_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER6_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER6_t;

#define PHG_TOP_TOP_LOGGER7                                                                    ((jl_uint32)0x002401D4U)
#define PHG_TOP_TOP_LOGGER7_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER7_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER7_OFFSET_TOP_LOGGER7                                                                      (0)
#define PHG_TOP_TOP_LOGGER7_OFFSET_TOP_LOGGER7_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER7_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger7:PHG_TOP_TOP_LOGGER7_OFFSET_TOP_LOGGER7_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER7_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER7_t;

#define PHG_TOP_TOP_LOGGER8                                                                    ((jl_uint32)0x002401D8U)
#define PHG_TOP_TOP_LOGGER8_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER8_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER8_OFFSET_TOP_LOGGER8                                                                      (0)
#define PHG_TOP_TOP_LOGGER8_OFFSET_TOP_LOGGER8_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER8_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger8:PHG_TOP_TOP_LOGGER8_OFFSET_TOP_LOGGER8_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER8_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER8_t;

#define PHG_TOP_TOP_LOGGER9                                                                    ((jl_uint32)0x002401DCU)
#define PHG_TOP_TOP_LOGGER9_NUM                                                                ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER9_ENTRY_SIZE                                                                              (1)
#define PHG_TOP_TOP_LOGGER9_OFFSET_TOP_LOGGER9                                                                      (0)
#define PHG_TOP_TOP_LOGGER9_OFFSET_TOP_LOGGER9_WIDTH                                                               (32)
typedef union PHG_TOP_TOP_LOGGER9_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger9:PHG_TOP_TOP_LOGGER9_OFFSET_TOP_LOGGER9_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER9_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER9_t;

#define PHG_TOP_TOP_LOGGER10                                                                   ((jl_uint32)0x002401E0U)
#define PHG_TOP_TOP_LOGGER10_NUM                                                               ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER10_ENTRY_SIZE                                                                             (1)
#define PHG_TOP_TOP_LOGGER10_OFFSET_TOP_LOGGER10                                                                    (0)
#define PHG_TOP_TOP_LOGGER10_OFFSET_TOP_LOGGER10_WIDTH                                                             (32)
typedef union PHG_TOP_TOP_LOGGER10_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger10:PHG_TOP_TOP_LOGGER10_OFFSET_TOP_LOGGER10_WIDTH;                                            //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER10_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER10_t;

#define PHG_TOP_TOP_LOGGER11                                                                   ((jl_uint32)0x002401E4U)
#define PHG_TOP_TOP_LOGGER11_NUM                                                               ((jl_uint32)0x00000001U)
#define PHG_TOP_TOP_LOGGER11_ENTRY_SIZE                                                                             (1)
#define PHG_TOP_TOP_LOGGER11_OFFSET_TOP_LOGGER11                                                                    (0)
#define PHG_TOP_TOP_LOGGER11_OFFSET_TOP_LOGGER11_WIDTH                                                             (32)
typedef union PHG_TOP_TOP_LOGGER11_u {
    struct __attribute__ ((packed)) {
        jl_uint32 top_logger11:PHG_TOP_TOP_LOGGER11_OFFSET_TOP_LOGGER11_WIDTH;                                            //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_TOP_LOGGER11_ENTRY_SIZE];
} PHG_TOP_TOP_LOGGER11_t;

#define PHG_TOP_CPU_IRQ_PC_MATCH                                                               ((jl_uint32)0x002401E8U)
#define PHG_TOP_CPU_IRQ_PC_MATCH_NUM                                                           ((jl_uint32)0x00000001U)
#define PHG_TOP_CPU_IRQ_PC_MATCH_ENTRY_SIZE                                                                         (1)
#define PHG_TOP_CPU_IRQ_PC_MATCH_OFFSET_IRQ_PC_MATCH                                                                (0)
#define PHG_TOP_CPU_IRQ_PC_MATCH_OFFSET_IRQ_PC_MATCH_WIDTH                                                         (32)
typedef union PHG_TOP_CPU_IRQ_PC_MATCH_u {
    struct __attribute__ ((packed)) {
        jl_uint32 irq_pc_match:PHG_TOP_CPU_IRQ_PC_MATCH_OFFSET_IRQ_PC_MATCH_WIDTH;                                        //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_CPU_IRQ_PC_MATCH_ENTRY_SIZE];
} PHG_TOP_CPU_IRQ_PC_MATCH_t;

#define PHG_TOP_CPU_PROGADDR_IRQ                                                               ((jl_uint32)0x002401ECU)
#define PHG_TOP_CPU_PROGADDR_IRQ_NUM                                                           ((jl_uint32)0x00000001U)
#define PHG_TOP_CPU_PROGADDR_IRQ_ENTRY_SIZE                                                                         (1)
#define PHG_TOP_CPU_PROGADDR_IRQ_OFFSET_PROGADDR_IRQ                                                                (0)
#define PHG_TOP_CPU_PROGADDR_IRQ_OFFSET_PROGADDR_IRQ_WIDTH                                                         (32)
typedef union PHG_TOP_CPU_PROGADDR_IRQ_u {
    struct __attribute__ ((packed)) {
        jl_uint32 progaddr_irq:PHG_TOP_CPU_PROGADDR_IRQ_OFFSET_PROGADDR_IRQ_WIDTH;                                        //[31: 0]
    } BF;
    jl_uint32 val[PHG_TOP_CPU_PROGADDR_IRQ_ENTRY_SIZE];
} PHG_TOP_CPU_PROGADDR_IRQ_t;

#define PHG_TOP_BROADCAST_MDIO_CTRL                                                            ((jl_uint32)0x002401F0U)
#define PHG_TOP_BROADCAST_MDIO_CTRL_NUM                                                        ((jl_uint32)0x00000001U)
#define PHG_TOP_BROADCAST_MDIO_CTRL_ENTRY_SIZE                                                                      (1)
#define PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_RSVD1                                                                   (16)
#define PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_RSVD1_WIDTH                                                             (16)
#define PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_BROADCAST_MDIO_MASK                                                      (0)
#define PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_BROADCAST_MDIO_MASK_WIDTH                                               (10)
#define PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_RSVD0                                                                   (10)
#define PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_RSVD0_WIDTH                                                              (5)
#define PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_BROADCAST_MDIO_EN                                                       (15)
#define PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_BROADCAST_MDIO_EN_WIDTH                                                  (1)
typedef union PHG_TOP_BROADCAST_MDIO_CTRL_u {
    struct __attribute__ ((packed)) {
        jl_uint32 broadcast_mdio_mask:PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_BROADCAST_MDIO_MASK_WIDTH;                       //[ 9: 0]
        jl_uint32 rsvd0:PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_RSVD0_WIDTH;                                                   //[14:10]
        jl_uint32 broadcast_mdio_en:PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_BROADCAST_MDIO_EN_WIDTH;                           //[15:15]
        jl_uint32 rsvd1:PHG_TOP_BROADCAST_MDIO_CTRL_OFFSET_RSVD1_WIDTH;                                                   //[31:16]
    } BF;
    jl_uint32 val[PHG_TOP_BROADCAST_MDIO_CTRL_ENTRY_SIZE];
} PHG_TOP_BROADCAST_MDIO_CTRL_t;

#define PHG_TOP_BROADCAST_MDIO_STATUS                                                          ((jl_uint32)0x002401F4U)
#define PHG_TOP_BROADCAST_MDIO_STATUS_NUM                                                      ((jl_uint32)0x00000001U)
#define PHG_TOP_BROADCAST_MDIO_STATUS_ENTRY_SIZE                                                                    (1)
#define PHG_TOP_BROADCAST_MDIO_STATUS_OFFSET_RSVD0                                                                 (20)
#define PHG_TOP_BROADCAST_MDIO_STATUS_OFFSET_RSVD0_WIDTH                                                           (12)
#define PHG_TOP_BROADCAST_MDIO_STATUS_OFFSET_BROADCAST_MDIO_ERR                                                     (0)
#define PHG_TOP_BROADCAST_MDIO_STATUS_OFFSET_BROADCAST_MDIO_ERR_WIDTH                                              (10)
#define PHG_TOP_BROADCAST_MDIO_STATUS_OFFSET_BROADCAST_MDIO_READY                                                  (10)
#define PHG_TOP_BROADCAST_MDIO_STATUS_OFFSET_BROADCAST_MDIO_READY_WIDTH                                            (10)
typedef union PHG_TOP_BROADCAST_MDIO_STATUS_u {
    struct __attribute__ ((packed)) {
        jl_uint32 broadcast_mdio_err:PHG_TOP_BROADCAST_MDIO_STATUS_OFFSET_BROADCAST_MDIO_ERR_WIDTH;                       //[ 9: 0]
        jl_uint32 broadcast_mdio_ready:PHG_TOP_BROADCAST_MDIO_STATUS_OFFSET_BROADCAST_MDIO_READY_WIDTH;                   //[19:10]
        jl_uint32 rsvd0:PHG_TOP_BROADCAST_MDIO_STATUS_OFFSET_RSVD0_WIDTH;                                                 //[31:20]
    } BF;
    jl_uint32 val[PHG_TOP_BROADCAST_MDIO_STATUS_ENTRY_SIZE];
} PHG_TOP_BROADCAST_MDIO_STATUS_t;

#define PHG_TOP_BROADCAST_CPU_CTRL                                                             ((jl_uint32)0x002401F8U)
#define PHG_TOP_BROADCAST_CPU_CTRL_NUM                                                         ((jl_uint32)0x00000001U)
#define PHG_TOP_BROADCAST_CPU_CTRL_ENTRY_SIZE                                                                       (1)
#define PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_RSVD1                                                                    (16)
#define PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_RSVD1_WIDTH                                                              (16)
#define PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_BROADCAST_CPU_MASK                                                        (0)
#define PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_BROADCAST_CPU_MASK_WIDTH                                                 (10)
#define PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_RSVD0                                                                    (10)
#define PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_RSVD0_WIDTH                                                               (5)
#define PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_BROADCAST_CPU_EN                                                         (15)
#define PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_BROADCAST_CPU_EN_WIDTH                                                    (1)
typedef union PHG_TOP_BROADCAST_CPU_CTRL_u {
    struct __attribute__ ((packed)) {
        jl_uint32 broadcast_cpu_mask:PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_BROADCAST_CPU_MASK_WIDTH;                          //[ 9: 0]
        jl_uint32 rsvd0:PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_RSVD0_WIDTH;                                                    //[14:10]
        jl_uint32 broadcast_cpu_en:PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_BROADCAST_CPU_EN_WIDTH;                              //[15:15]
        jl_uint32 rsvd1:PHG_TOP_BROADCAST_CPU_CTRL_OFFSET_RSVD1_WIDTH;                                                    //[31:16]
    } BF;
    jl_uint32 val[PHG_TOP_BROADCAST_CPU_CTRL_ENTRY_SIZE];
} PHG_TOP_BROADCAST_CPU_CTRL_t;

#define PHG_TOP_BROADCAST_CPU_STATUS                                                           ((jl_uint32)0x002401FCU)
#define PHG_TOP_BROADCAST_CPU_STATUS_NUM                                                       ((jl_uint32)0x00000001U)
#define PHG_TOP_BROADCAST_CPU_STATUS_ENTRY_SIZE                                                                     (1)
#define PHG_TOP_BROADCAST_CPU_STATUS_OFFSET_RSVD0                                                                  (20)
#define PHG_TOP_BROADCAST_CPU_STATUS_OFFSET_RSVD0_WIDTH                                                            (12)
#define PHG_TOP_BROADCAST_CPU_STATUS_OFFSET_BROADCAST_CPU_ERR                                                       (0)
#define PHG_TOP_BROADCAST_CPU_STATUS_OFFSET_BROADCAST_CPU_ERR_WIDTH                                                (10)
#define PHG_TOP_BROADCAST_CPU_STATUS_OFFSET_BROADCAST_CPU_READY                                                    (10)
#define PHG_TOP_BROADCAST_CPU_STATUS_OFFSET_BROADCAST_CPU_READY_WIDTH                                              (10)
typedef union PHG_TOP_BROADCAST_CPU_STATUS_u {
    struct __attribute__ ((packed)) {
        jl_uint32 broadcast_cpu_err:PHG_TOP_BROADCAST_CPU_STATUS_OFFSET_BROADCAST_CPU_ERR_WIDTH;                          //[ 9: 0]
        jl_uint32 broadcast_cpu_ready:PHG_TOP_BROADCAST_CPU_STATUS_OFFSET_BROADCAST_CPU_READY_WIDTH;                      //[19:10]
        jl_uint32 rsvd0:PHG_TOP_BROADCAST_CPU_STATUS_OFFSET_RSVD0_WIDTH;                                                  //[31:20]
    } BF;
    jl_uint32 val[PHG_TOP_BROADCAST_CPU_STATUS_ENTRY_SIZE];
} PHG_TOP_BROADCAST_CPU_STATUS_t;

#define PHG_TOP_CPU_SP_LATCH                                                                   ((jl_uint32)0x00240200U)
#define PHG_TOP_CPU_SP_LATCH_NUM                                                               ((jl_uint32)0x00000001U)
#define PHG_TOP_CPU_SP_LATCH_ENTRY_SIZE                                                                             (1)
#define PHG_TOP_CPU_SP_LATCH_OFFSET_CPU_SP                                                                          (0)
#define PHG_TOP_CPU_SP_LATCH_OFFSET_CPU_SP_WIDTH                                                                   (16)
#define PHG_TOP_CPU_SP_LATCH_OFFSET_RSVD0                                                                          (16)
#define PHG_TOP_CPU_SP_LATCH_OFFSET_RSVD0_WIDTH                                                                    (15)
#define PHG_TOP_CPU_SP_LATCH_OFFSET_CPU_SP_CLR                                                                     (31)
#define PHG_TOP_CPU_SP_LATCH_OFFSET_CPU_SP_CLR_WIDTH                                                                (1)
typedef union PHG_TOP_CPU_SP_LATCH_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cpu_sp:PHG_TOP_CPU_SP_LATCH_OFFSET_CPU_SP_WIDTH;                                                        //[15: 0]
        jl_uint32 rsvd0:PHG_TOP_CPU_SP_LATCH_OFFSET_RSVD0_WIDTH;                                                          //[30:16]
        jl_uint32 cpu_sp_clr:PHG_TOP_CPU_SP_LATCH_OFFSET_CPU_SP_CLR_WIDTH;                                                //[31:31]
    } BF;
    jl_uint32 val[PHG_TOP_CPU_SP_LATCH_ENTRY_SIZE];
} PHG_TOP_CPU_SP_LATCH_t;

#endif /* __JL_REG_PHG_TOP_H__ */

