//reg_swc.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_SWC_H__
#define __JL_REG_SWC_H__

#include <jl_types.h>

#define SWC_BASE                                                                               ((jl_uint32)0x00124000U)
#define SWC_BLOCK_SIZE                                                                         ((jl_uint32)0x0001C000U)

#define SWC_SWC_INIT_STATUS                                                                    ((jl_uint32)0x00124000U)
#define SWC_SWC_INIT_STATUS_NUM                                                                ((jl_uint32)0x00000001U)
#define SWC_SWC_INIT_STATUS_ENTRY_SIZE                                                                              (1)
#define SWC_SWC_INIT_STATUS_OFFSET_RSVD0                                                                            (1)
#define SWC_SWC_INIT_STATUS_OFFSET_RSVD0_WIDTH                                                                     (31)
#define SWC_SWC_INIT_STATUS_OFFSET_INITIAL_DONE                                                                     (0)
#define SWC_SWC_INIT_STATUS_OFFSET_INITIAL_DONE_WIDTH                                                               (1)
typedef union SWC_SWC_INIT_STATUS_u {
    struct __attribute__ ((packed)) {
        jl_uint32 initial_done:SWC_SWC_INIT_STATUS_OFFSET_INITIAL_DONE_WIDTH;                                             //[ 0: 0]
        jl_uint32 rsvd0:SWC_SWC_INIT_STATUS_OFFSET_RSVD0_WIDTH;                                                           //[31: 1]
    } BF;
    jl_uint32 val[SWC_SWC_INIT_STATUS_ENTRY_SIZE];
} SWC_SWC_INIT_STATUS_t;

#define SWC_DEBUG_READ_DATA                                                                    ((jl_uint32)0x00124004U)
#define SWC_DEBUG_READ_DATA_NUM                                                                ((jl_uint32)0x00000001U)
#define SWC_DEBUG_READ_DATA_ENTRY_SIZE                                                                              (1)
#define SWC_DEBUG_READ_DATA_OFFSET_DEBUG_RDATA                                                                      (0)
#define SWC_DEBUG_READ_DATA_OFFSET_DEBUG_RDATA_WIDTH                                                               (32)
typedef union SWC_DEBUG_READ_DATA_u {
    struct __attribute__ ((packed)) {
        jl_uint32 debug_rdata:SWC_DEBUG_READ_DATA_OFFSET_DEBUG_RDATA_WIDTH;                                               //[31: 0]
    } BF;
    jl_uint32 val[SWC_DEBUG_READ_DATA_ENTRY_SIZE];
} SWC_DEBUG_READ_DATA_t;

#define SWC_DEBUG_READ_SELECT                                                                  ((jl_uint32)0x00124008U)
#define SWC_DEBUG_READ_SELECT_NUM                                                              ((jl_uint32)0x00000001U)
#define SWC_DEBUG_READ_SELECT_ENTRY_SIZE                                                                            (1)
#define SWC_DEBUG_READ_SELECT_OFFSET_RSVD2                                                                         (13)
#define SWC_DEBUG_READ_SELECT_OFFSET_RSVD2_WIDTH                                                                   (19)
#define SWC_DEBUG_READ_SELECT_OFFSET_DEBUG_RDATA_SELECT                                                             (0)
#define SWC_DEBUG_READ_SELECT_OFFSET_DEBUG_RDATA_SELECT_WIDTH                                                       (9)
#define SWC_DEBUG_READ_SELECT_OFFSET_RSVD1                                                                          (9)
#define SWC_DEBUG_READ_SELECT_OFFSET_RSVD1_WIDTH                                                                    (1)
#define SWC_DEBUG_READ_SELECT_OFFSET_DEBUG_MAC_SEL                                                                 (10)
#define SWC_DEBUG_READ_SELECT_OFFSET_DEBUG_MAC_SEL_WIDTH                                                            (1)
#define SWC_DEBUG_READ_SELECT_OFFSET_RSVD0                                                                         (11)
#define SWC_DEBUG_READ_SELECT_OFFSET_RSVD0_WIDTH                                                                    (1)
#define SWC_DEBUG_READ_SELECT_OFFSET_DEBUG_RDATA_EN                                                                (12)
#define SWC_DEBUG_READ_SELECT_OFFSET_DEBUG_RDATA_EN_WIDTH                                                           (1)
typedef union SWC_DEBUG_READ_SELECT_u {
    struct __attribute__ ((packed)) {
        jl_uint32 debug_rdata_select:SWC_DEBUG_READ_SELECT_OFFSET_DEBUG_RDATA_SELECT_WIDTH;                               //[ 8: 0]
        jl_uint32 rsvd1:SWC_DEBUG_READ_SELECT_OFFSET_RSVD1_WIDTH;                                                         //[ 9: 9]
        jl_uint32 debug_mac_sel:SWC_DEBUG_READ_SELECT_OFFSET_DEBUG_MAC_SEL_WIDTH;                                         //[10:10]
        jl_uint32 rsvd0:SWC_DEBUG_READ_SELECT_OFFSET_RSVD0_WIDTH;                                                         //[11:11]
        jl_uint32 debug_rdata_en:SWC_DEBUG_READ_SELECT_OFFSET_DEBUG_RDATA_EN_WIDTH;                                       //[12:12]
        jl_uint32 rsvd2:SWC_DEBUG_READ_SELECT_OFFSET_RSVD2_WIDTH;                                                         //[31:13]
    } BF;
    jl_uint32 val[SWC_DEBUG_READ_SELECT_ENTRY_SIZE];
} SWC_DEBUG_READ_SELECT_t;

#define SWC_RSV_REG                                                                            ((jl_uint32)0x0012400CU)
#define SWC_RSV_REG_NUM                                                                        ((jl_uint32)0x00000001U)
#define SWC_RSV_REG_ENTRY_SIZE                                                                                      (1)
#define SWC_RSV_REG_OFFSET_RSVD0                                                                                    (3)
#define SWC_RSV_REG_OFFSET_RSVD0_WIDTH                                                                             (29)
#define SWC_RSV_REG_OFFSET_GREEDY_MODE_EN                                                                           (0)
#define SWC_RSV_REG_OFFSET_GREEDY_MODE_EN_WIDTH                                                                     (1)
#define SWC_RSV_REG_OFFSET_GREEDY_PORT_SEL                                                                          (1)
#define SWC_RSV_REG_OFFSET_GREEDY_PORT_SEL_WIDTH                                                                    (1)
#define SWC_RSV_REG_OFFSET_GREEDY_SHARE_MODE                                                                        (2)
#define SWC_RSV_REG_OFFSET_GREEDY_SHARE_MODE_WIDTH                                                                  (1)
typedef union SWC_RSV_REG_u {
    struct __attribute__ ((packed)) {
        jl_uint32 greedy_mode_en:SWC_RSV_REG_OFFSET_GREEDY_MODE_EN_WIDTH;                                                 //[ 0: 0]
        jl_uint32 greedy_port_sel:SWC_RSV_REG_OFFSET_GREEDY_PORT_SEL_WIDTH;                                               //[ 1: 1]
        jl_uint32 greedy_share_mode:SWC_RSV_REG_OFFSET_GREEDY_SHARE_MODE_WIDTH;                                           //[ 2: 2]
        jl_uint32 rsvd0:SWC_RSV_REG_OFFSET_RSVD0_WIDTH;                                                                   //[31: 3]
    } BF;
    jl_uint32 val[SWC_RSV_REG_ENTRY_SIZE];
} SWC_RSV_REG_t;

#define SWC_MEMORY_EMA                                                                         ((jl_uint32)0x00124010U)
#define SWC_MEMORY_EMA_NUM                                                                     ((jl_uint32)0x00000001U)
#define SWC_MEMORY_EMA_ENTRY_SIZE                                                                                   (1)
#define SWC_MEMORY_EMA_OFFSET_RSVD0                                                                                 (3)
#define SWC_MEMORY_EMA_OFFSET_RSVD0_WIDTH                                                                          (29)
#define SWC_MEMORY_EMA_OFFSET_MEMORY_EMA                                                                            (0)
#define SWC_MEMORY_EMA_OFFSET_MEMORY_EMA_WIDTH                                                                      (3)
typedef union SWC_MEMORY_EMA_u {
    struct __attribute__ ((packed)) {
        jl_uint32 memory_ema:SWC_MEMORY_EMA_OFFSET_MEMORY_EMA_WIDTH;                                                      //[ 2: 0]
        jl_uint32 rsvd0:SWC_MEMORY_EMA_OFFSET_RSVD0_WIDTH;                                                                //[31: 3]
    } BF;
    jl_uint32 val[SWC_MEMORY_EMA_ENTRY_SIZE];
} SWC_MEMORY_EMA_t;

#define SWC_SWC_SCRATCH_REG                                                                    ((jl_uint32)0x00124014U)
#define SWC_SWC_SCRATCH_REG_NUM                                                                ((jl_uint32)0x00000001U)
#define SWC_SWC_SCRATCH_REG_ENTRY_SIZE                                                                              (1)
#define SWC_SWC_SCRATCH_REG_OFFSET_SWC_SCRATCH_REG                                                                  (0)
#define SWC_SWC_SCRATCH_REG_OFFSET_SWC_SCRATCH_REG_WIDTH                                                           (32)
typedef union SWC_SWC_SCRATCH_REG_u {
    struct __attribute__ ((packed)) {
        jl_uint32 swc_scratch_reg:SWC_SWC_SCRATCH_REG_OFFSET_SWC_SCRATCH_REG_WIDTH;                                       //[31: 0]
    } BF;
    jl_uint32 val[SWC_SWC_SCRATCH_REG_ENTRY_SIZE];
} SWC_SWC_SCRATCH_REG_t;

#define SWC_PAUSE_0_3_CAR                                                                      ((jl_uint32)0x00124018U)
#define SWC_PAUSE_0_3_CAR_NUM                                                                  ((jl_uint32)0x00000001U)
#define SWC_PAUSE_0_3_CAR_ENTRY_SIZE                                                                                (1)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_0                                                                       (0)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_0_WIDTH                                                                 (4)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_0                                                                       (4)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_0_WIDTH                                                                 (4)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_1                                                                       (8)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_1_WIDTH                                                                 (4)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_1                                                                      (12)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_1_WIDTH                                                                 (4)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_2                                                                      (16)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_2_WIDTH                                                                 (4)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_2                                                                      (20)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_2_WIDTH                                                                 (4)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_3                                                                      (24)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_3_WIDTH                                                                 (4)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_3                                                                      (28)
#define SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_3_WIDTH                                                                 (4)
typedef union SWC_PAUSE_0_3_CAR_u {
    struct __attribute__ ((packed)) {
        jl_uint32 pause_opfc_0:SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_0_WIDTH;                                               //[ 3: 0]
        jl_uint32 pause_iext_0:SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_0_WIDTH;                                               //[ 7: 4]
        jl_uint32 pause_opfc_1:SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_1_WIDTH;                                               //[11: 8]
        jl_uint32 pause_iext_1:SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_1_WIDTH;                                               //[15:12]
        jl_uint32 pause_opfc_2:SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_2_WIDTH;                                               //[19:16]
        jl_uint32 pause_iext_2:SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_2_WIDTH;                                               //[23:20]
        jl_uint32 pause_opfc_3:SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_OPFC_3_WIDTH;                                               //[27:24]
        jl_uint32 pause_iext_3:SWC_PAUSE_0_3_CAR_OFFSET_PAUSE_IEXT_3_WIDTH;                                               //[31:28]
    } BF;
    jl_uint32 val[SWC_PAUSE_0_3_CAR_ENTRY_SIZE];
} SWC_PAUSE_0_3_CAR_t;

#define SWC_PAUSE_4_7_CAR                                                                      ((jl_uint32)0x0012401CU)
#define SWC_PAUSE_4_7_CAR_NUM                                                                  ((jl_uint32)0x00000001U)
#define SWC_PAUSE_4_7_CAR_ENTRY_SIZE                                                                                (1)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_4                                                                       (0)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_4_WIDTH                                                                 (4)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_4                                                                       (4)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_4_WIDTH                                                                 (4)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_5                                                                       (8)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_5_WIDTH                                                                 (4)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_5                                                                      (12)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_5_WIDTH                                                                 (4)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_6                                                                      (16)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_6_WIDTH                                                                 (4)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_6                                                                      (20)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_6_WIDTH                                                                 (4)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_7                                                                      (24)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_7_WIDTH                                                                 (4)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_7                                                                      (28)
#define SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_7_WIDTH                                                                 (4)
typedef union SWC_PAUSE_4_7_CAR_u {
    struct __attribute__ ((packed)) {
        jl_uint32 pause_opfc_4:SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_4_WIDTH;                                               //[ 3: 0]
        jl_uint32 pause_iext_4:SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_4_WIDTH;                                               //[ 7: 4]
        jl_uint32 pause_opfc_5:SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_5_WIDTH;                                               //[11: 8]
        jl_uint32 pause_iext_5:SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_5_WIDTH;                                               //[15:12]
        jl_uint32 pause_opfc_6:SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_6_WIDTH;                                               //[19:16]
        jl_uint32 pause_iext_6:SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_6_WIDTH;                                               //[23:20]
        jl_uint32 pause_opfc_7:SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_OPFC_7_WIDTH;                                               //[27:24]
        jl_uint32 pause_iext_7:SWC_PAUSE_4_7_CAR_OFFSET_PAUSE_IEXT_7_WIDTH;                                               //[31:28]
    } BF;
    jl_uint32 val[SWC_PAUSE_4_7_CAR_ENTRY_SIZE];
} SWC_PAUSE_4_7_CAR_t;

#define SWC_PAUSE_8_10_CAR                                                                     ((jl_uint32)0x00124020U)
#define SWC_PAUSE_8_10_CAR_NUM                                                                 ((jl_uint32)0x00000001U)
#define SWC_PAUSE_8_10_CAR_ENTRY_SIZE                                                                               (1)
#define SWC_PAUSE_8_10_CAR_OFFSET_RSVD0                                                                            (24)
#define SWC_PAUSE_8_10_CAR_OFFSET_RSVD0_WIDTH                                                                       (8)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_OPFC_8                                                                      (0)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_OPFC_8_WIDTH                                                                (4)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_IEXT_8                                                                      (4)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_IEXT_8_WIDTH                                                                (4)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_OPFC_9                                                                      (8)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_OPFC_9_WIDTH                                                                (4)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_IEXT_9                                                                     (12)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_IEXT_9_WIDTH                                                                (4)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_OPFC_10                                                                    (16)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_OPFC_10_WIDTH                                                               (4)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_IEXT_10                                                                    (20)
#define SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_IEXT_10_WIDTH                                                               (4)
typedef union SWC_PAUSE_8_10_CAR_u {
    struct __attribute__ ((packed)) {
        jl_uint32 pause_opfc_8:SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_OPFC_8_WIDTH;                                              //[ 3: 0]
        jl_uint32 pause_iext_8:SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_IEXT_8_WIDTH;                                              //[ 7: 4]
        jl_uint32 pause_opfc_9:SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_OPFC_9_WIDTH;                                              //[11: 8]
        jl_uint32 pause_iext_9:SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_IEXT_9_WIDTH;                                              //[15:12]
        jl_uint32 pause_opfc_10:SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_OPFC_10_WIDTH;                                            //[19:16]
        jl_uint32 pause_iext_10:SWC_PAUSE_8_10_CAR_OFFSET_PAUSE_IEXT_10_WIDTH;                                            //[23:20]
        jl_uint32 rsvd0:SWC_PAUSE_8_10_CAR_OFFSET_RSVD0_WIDTH;                                                            //[31:24]
    } BF;
    jl_uint32 val[SWC_PAUSE_8_10_CAR_ENTRY_SIZE];
} SWC_PAUSE_8_10_CAR_t;

#define SWC_IHALT_STATUS                                                                       ((jl_uint32)0x00124024U)
#define SWC_IHALT_STATUS_NUM                                                                   ((jl_uint32)0x00000001U)
#define SWC_IHALT_STATUS_ENTRY_SIZE                                                                                 (1)
#define SWC_IHALT_STATUS_OFFSET_RSVD0                                                                              (11)
#define SWC_IHALT_STATUS_OFFSET_RSVD0_WIDTH                                                                        (21)
#define SWC_IHALT_STATUS_OFFSET_IHALT_STATUS                                                                        (0)
#define SWC_IHALT_STATUS_OFFSET_IHALT_STATUS_WIDTH                                                                 (11)
typedef union SWC_IHALT_STATUS_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_status:SWC_IHALT_STATUS_OFFSET_IHALT_STATUS_WIDTH;                                                //[10: 0]
        jl_uint32 rsvd0:SWC_IHALT_STATUS_OFFSET_RSVD0_WIDTH;                                                              //[31:11]
    } BF;
    jl_uint32 val[SWC_IHALT_STATUS_ENTRY_SIZE];
} SWC_IHALT_STATUS_t;

#define SWC_IHALT_CNT_0                                                                        ((jl_uint32)0x00124028U)
#define SWC_IHALT_CNT_0_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_0_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_0_OFFSET_IHALT_CNT_0                                                                          (0)
#define SWC_IHALT_CNT_0_OFFSET_IHALT_CNT_0_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_0_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_0:SWC_IHALT_CNT_0_OFFSET_IHALT_CNT_0_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_0_ENTRY_SIZE];
} SWC_IHALT_CNT_0_t;

#define SWC_IHALT_CNT_1                                                                        ((jl_uint32)0x0012402CU)
#define SWC_IHALT_CNT_1_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_1_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_1_OFFSET_IHALT_CNT_1                                                                          (0)
#define SWC_IHALT_CNT_1_OFFSET_IHALT_CNT_1_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_1_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_1:SWC_IHALT_CNT_1_OFFSET_IHALT_CNT_1_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_1_ENTRY_SIZE];
} SWC_IHALT_CNT_1_t;

#define SWC_IHALT_CNT_2                                                                        ((jl_uint32)0x00124030U)
#define SWC_IHALT_CNT_2_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_2_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_2_OFFSET_IHALT_CNT_2                                                                          (0)
#define SWC_IHALT_CNT_2_OFFSET_IHALT_CNT_2_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_2_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_2:SWC_IHALT_CNT_2_OFFSET_IHALT_CNT_2_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_2_ENTRY_SIZE];
} SWC_IHALT_CNT_2_t;

#define SWC_IHALT_CNT_3                                                                        ((jl_uint32)0x00124034U)
#define SWC_IHALT_CNT_3_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_3_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_3_OFFSET_IHALT_CNT_3                                                                          (0)
#define SWC_IHALT_CNT_3_OFFSET_IHALT_CNT_3_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_3_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_3:SWC_IHALT_CNT_3_OFFSET_IHALT_CNT_3_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_3_ENTRY_SIZE];
} SWC_IHALT_CNT_3_t;

#define SWC_IHALT_CNT_4                                                                        ((jl_uint32)0x00124038U)
#define SWC_IHALT_CNT_4_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_4_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_4_OFFSET_IHALT_CNT_4                                                                          (0)
#define SWC_IHALT_CNT_4_OFFSET_IHALT_CNT_4_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_4_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_4:SWC_IHALT_CNT_4_OFFSET_IHALT_CNT_4_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_4_ENTRY_SIZE];
} SWC_IHALT_CNT_4_t;

#define SWC_IHALT_CNT_5                                                                        ((jl_uint32)0x0012403CU)
#define SWC_IHALT_CNT_5_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_5_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_5_OFFSET_IHALT_CNT_5                                                                          (0)
#define SWC_IHALT_CNT_5_OFFSET_IHALT_CNT_5_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_5_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_5:SWC_IHALT_CNT_5_OFFSET_IHALT_CNT_5_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_5_ENTRY_SIZE];
} SWC_IHALT_CNT_5_t;

#define SWC_IHALT_CNT_6                                                                        ((jl_uint32)0x00124040U)
#define SWC_IHALT_CNT_6_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_6_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_6_OFFSET_IHALT_CNT_6                                                                          (0)
#define SWC_IHALT_CNT_6_OFFSET_IHALT_CNT_6_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_6_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_6:SWC_IHALT_CNT_6_OFFSET_IHALT_CNT_6_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_6_ENTRY_SIZE];
} SWC_IHALT_CNT_6_t;

#define SWC_IHALT_CNT_7                                                                        ((jl_uint32)0x00124044U)
#define SWC_IHALT_CNT_7_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_7_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_7_OFFSET_IHALT_CNT_7                                                                          (0)
#define SWC_IHALT_CNT_7_OFFSET_IHALT_CNT_7_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_7_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_7:SWC_IHALT_CNT_7_OFFSET_IHALT_CNT_7_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_7_ENTRY_SIZE];
} SWC_IHALT_CNT_7_t;

#define SWC_IHALT_CNT_8                                                                        ((jl_uint32)0x00124048U)
#define SWC_IHALT_CNT_8_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_8_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_8_OFFSET_IHALT_CNT_8                                                                          (0)
#define SWC_IHALT_CNT_8_OFFSET_IHALT_CNT_8_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_8_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_8:SWC_IHALT_CNT_8_OFFSET_IHALT_CNT_8_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_8_ENTRY_SIZE];
} SWC_IHALT_CNT_8_t;

#define SWC_IHALT_CNT_9                                                                        ((jl_uint32)0x0012404CU)
#define SWC_IHALT_CNT_9_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_9_ENTRY_SIZE                                                                                  (1)
#define SWC_IHALT_CNT_9_OFFSET_IHALT_CNT_9                                                                          (0)
#define SWC_IHALT_CNT_9_OFFSET_IHALT_CNT_9_WIDTH                                                                   (32)
typedef union SWC_IHALT_CNT_9_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_9:SWC_IHALT_CNT_9_OFFSET_IHALT_CNT_9_WIDTH;                                                   //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_9_ENTRY_SIZE];
} SWC_IHALT_CNT_9_t;

#define SWC_IHALT_CNT_10                                                                       ((jl_uint32)0x00124050U)
#define SWC_IHALT_CNT_10_NUM                                                                   ((jl_uint32)0x00000001U)
#define SWC_IHALT_CNT_10_ENTRY_SIZE                                                                                 (1)
#define SWC_IHALT_CNT_10_OFFSET_IHALT_CNT_10                                                                        (0)
#define SWC_IHALT_CNT_10_OFFSET_IHALT_CNT_10_WIDTH                                                                 (32)
typedef union SWC_IHALT_CNT_10_u {
    struct __attribute__ ((packed)) {
        jl_uint32 ihalt_cnt_10:SWC_IHALT_CNT_10_OFFSET_IHALT_CNT_10_WIDTH;                                                //[31: 0]
    } BF;
    jl_uint32 val[SWC_IHALT_CNT_10_ENTRY_SIZE];
} SWC_IHALT_CNT_10_t;

#define SWC_SWC_STATUS                                                                         ((jl_uint32)0x00124054U)
#define SWC_SWC_STATUS_NUM                                                                     ((jl_uint32)0x00000001U)
#define SWC_SWC_STATUS_ENTRY_SIZE                                                                                   (1)
#define SWC_SWC_STATUS_OFFSET_RSVD0                                                                                 (2)
#define SWC_SWC_STATUS_OFFSET_RSVD0_WIDTH                                                                          (30)
#define SWC_SWC_STATUS_OFFSET_ASSERT_RESET                                                                          (0)
#define SWC_SWC_STATUS_OFFSET_ASSERT_RESET_WIDTH                                                                    (1)
#define SWC_SWC_STATUS_OFFSET_SWC_REG_TIMEOUT                                                                       (1)
#define SWC_SWC_STATUS_OFFSET_SWC_REG_TIMEOUT_WIDTH                                                                 (1)
typedef union SWC_SWC_STATUS_u {
    struct __attribute__ ((packed)) {
        jl_uint32 assert_reset:SWC_SWC_STATUS_OFFSET_ASSERT_RESET_WIDTH;                                                  //[ 0: 0]
        jl_uint32 swc_reg_timeout:SWC_SWC_STATUS_OFFSET_SWC_REG_TIMEOUT_WIDTH;                                            //[ 1: 1]
        jl_uint32 rsvd0:SWC_SWC_STATUS_OFFSET_RSVD0_WIDTH;                                                                //[31: 2]
    } BF;
    jl_uint32 val[SWC_SWC_STATUS_ENTRY_SIZE];
} SWC_SWC_STATUS_t;

#define SWC_SWC_CAR_CLR                                                                        ((jl_uint32)0x00124058U)
#define SWC_SWC_CAR_CLR_NUM                                                                    ((jl_uint32)0x00000001U)
#define SWC_SWC_CAR_CLR_ENTRY_SIZE                                                                                  (1)
#define SWC_SWC_CAR_CLR_OFFSET_RSVD0                                                                                (1)
#define SWC_SWC_CAR_CLR_OFFSET_RSVD0_WIDTH                                                                         (31)
#define SWC_SWC_CAR_CLR_OFFSET_SWC_CAR_CLR                                                                          (0)
#define SWC_SWC_CAR_CLR_OFFSET_SWC_CAR_CLR_WIDTH                                                                    (1)
typedef union SWC_SWC_CAR_CLR_u {
    struct __attribute__ ((packed)) {
        jl_uint32 swc_car_clr:SWC_SWC_CAR_CLR_OFFSET_SWC_CAR_CLR_WIDTH;                                                   //[ 0: 0]
        jl_uint32 rsvd0:SWC_SWC_CAR_CLR_OFFSET_RSVD0_WIDTH;                                                               //[31: 1]
    } BF;
    jl_uint32 val[SWC_SWC_CAR_CLR_ENTRY_SIZE];
} SWC_SWC_CAR_CLR_t;

#define SWC_SWC_CAR_MODE                                                                       ((jl_uint32)0x0012405CU)
#define SWC_SWC_CAR_MODE_NUM                                                                   ((jl_uint32)0x00000001U)
#define SWC_SWC_CAR_MODE_ENTRY_SIZE                                                                                 (1)
#define SWC_SWC_CAR_MODE_OFFSET_RSVD0                                                                               (1)
#define SWC_SWC_CAR_MODE_OFFSET_RSVD0_WIDTH                                                                        (31)
#define SWC_SWC_CAR_MODE_OFFSET_SWC_CAR_MODE                                                                        (0)
#define SWC_SWC_CAR_MODE_OFFSET_SWC_CAR_MODE_WIDTH                                                                  (1)
typedef union SWC_SWC_CAR_MODE_u {
    struct __attribute__ ((packed)) {
        jl_uint32 swc_car_mode:SWC_SWC_CAR_MODE_OFFSET_SWC_CAR_MODE_WIDTH;                                                //[ 0: 0]
        jl_uint32 rsvd0:SWC_SWC_CAR_MODE_OFFSET_RSVD0_WIDTH;                                                              //[31: 1]
    } BF;
    jl_uint32 val[SWC_SWC_CAR_MODE_ENTRY_SIZE];
} SWC_SWC_CAR_MODE_t;

#define SWC_SWC_CAR_EN                                                                         ((jl_uint32)0x00124060U)
#define SWC_SWC_CAR_EN_NUM                                                                     ((jl_uint32)0x00000001U)
#define SWC_SWC_CAR_EN_ENTRY_SIZE                                                                                   (1)
#define SWC_SWC_CAR_EN_OFFSET_RSVD0                                                                                 (1)
#define SWC_SWC_CAR_EN_OFFSET_RSVD0_WIDTH                                                                          (31)
#define SWC_SWC_CAR_EN_OFFSET_SWC_CAR_EN                                                                            (0)
#define SWC_SWC_CAR_EN_OFFSET_SWC_CAR_EN_WIDTH                                                                      (1)
typedef union SWC_SWC_CAR_EN_u {
    struct __attribute__ ((packed)) {
        jl_uint32 swc_car_en:SWC_SWC_CAR_EN_OFFSET_SWC_CAR_EN_WIDTH;                                                      //[ 0: 0]
        jl_uint32 rsvd0:SWC_SWC_CAR_EN_OFFSET_RSVD0_WIDTH;                                                                //[31: 1]
    } BF;
    jl_uint32 val[SWC_SWC_CAR_EN_ENTRY_SIZE];
} SWC_SWC_CAR_EN_t;

#endif /* __JL_REG_SWC_H__ */

