//reg_pmx.h
/*
* Automatically generated by gen_c_api.py, don't edit it
*/
#ifndef __JL_REG_PMX_H__
#define __JL_REG_PMX_H__

#include <jl_types.h>

#define PMX_BASE                                                                               ((jl_uint32)0x00204000U)
#define PMX_BLOCK_SIZE                                                                         ((jl_uint32)0x00001000U)

#define PMX_PIN_MUX_0                                                                          ((jl_uint32)0x00204000U)
#define PMX_PIN_MUX_0_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_0_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_0_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_0_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_LPD_SEL                                                                        (0)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_LPD_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_SPF_MUX_SEL                                                                        (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_SPF_MUX_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_EN_PWRLIGHT_P10_SEL                                                                (2)
#define PMX_PIN_MUX_0_OFFSET_CFG_EN_PWRLIGHT_P10_SEL_WIDTH                                                          (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_DISAUTOLOAD_P10_SEL                                                                (3)
#define PMX_PIN_MUX_0_OFFSET_CFG_DISAUTOLOAD_P10_SEL_WIDTH                                                          (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_EEE_EN_P10_SEL                                                                     (4)
#define PMX_PIN_MUX_0_OFFSET_CFG_EEE_EN_P10_SEL_WIDTH                                                               (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_LED_SEL                                                                        (5)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_LED_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_EN_FLASH_P10_SEL                                                                   (6)
#define PMX_PIN_MUX_0_OFFSET_CFG_EN_FLASH_P10_SEL_WIDTH                                                             (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_SPIS_SEL                                                                       (7)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_SPIS_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_EEPROM_MOD_P85_SEL                                                                 (8)
#define PMX_PIN_MUX_0_OFFSET_CFG_EEPROM_MOD_P85_SEL_WIDTH                                                           (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_EN_PWRLIGHT_P8_SEL                                                                 (9)
#define PMX_PIN_MUX_0_OFFSET_CFG_EN_PWRLIGHT_P8_SEL_WIDTH                                                           (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_EN_FLASH_P85_SEL                                                                  (10)
#define PMX_PIN_MUX_0_OFFSET_CFG_EN_FLASH_P85_SEL_WIDTH                                                             (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_CPU_P85_SEL                                                                   (11)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_CPU_P85_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_DISAUTOLOAD_P85_SEL                                                               (12)
#define PMX_PIN_MUX_0_OFFSET_CFG_DISAUTOLOAD_P85_SEL_WIDTH                                                          (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_SMI_SEL_1_SEL                                                                     (13)
#define PMX_PIN_MUX_0_OFFSET_CFG_SMI_SEL_1_SEL_WIDTH                                                                (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_MID29_SEL                                                                         (14)
#define PMX_PIN_MUX_0_OFFSET_CFG_MID29_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_CPU_P10_SEL                                                                   (15)
#define PMX_PIN_MUX_0_OFFSET_CFG_DIS_CPU_P10_SEL_WIDTH                                                              (1)
typedef union PMX_PIN_MUX_0_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_dis_lpd_sel:PMX_PIN_MUX_0_OFFSET_CFG_DIS_LPD_SEL_WIDTH;                                             //[ 0: 0]
        jl_uint32 cfg_spf_mux_sel:PMX_PIN_MUX_0_OFFSET_CFG_SPF_MUX_SEL_WIDTH;                                             //[ 1: 1]
        jl_uint32 cfg_en_pwrlight_p10_sel:PMX_PIN_MUX_0_OFFSET_CFG_EN_PWRLIGHT_P10_SEL_WIDTH;                             //[ 2: 2]
        jl_uint32 cfg_disautoload_p10_sel:PMX_PIN_MUX_0_OFFSET_CFG_DISAUTOLOAD_P10_SEL_WIDTH;                             //[ 3: 3]
        jl_uint32 cfg_eee_en_p10_sel:PMX_PIN_MUX_0_OFFSET_CFG_EEE_EN_P10_SEL_WIDTH;                                       //[ 4: 4]
        jl_uint32 cfg_dis_led_sel:PMX_PIN_MUX_0_OFFSET_CFG_DIS_LED_SEL_WIDTH;                                             //[ 5: 5]
        jl_uint32 cfg_en_flash_p10_sel:PMX_PIN_MUX_0_OFFSET_CFG_EN_FLASH_P10_SEL_WIDTH;                                   //[ 6: 6]
        jl_uint32 cfg_dis_spis_sel:PMX_PIN_MUX_0_OFFSET_CFG_DIS_SPIS_SEL_WIDTH;                                           //[ 7: 7]
        jl_uint32 cfg_eeprom_mod_p85_sel:PMX_PIN_MUX_0_OFFSET_CFG_EEPROM_MOD_P85_SEL_WIDTH;                               //[ 8: 8]
        jl_uint32 cfg_en_pwrlight_p8_sel:PMX_PIN_MUX_0_OFFSET_CFG_EN_PWRLIGHT_P8_SEL_WIDTH;                               //[ 9: 9]
        jl_uint32 cfg_en_flash_p85_sel:PMX_PIN_MUX_0_OFFSET_CFG_EN_FLASH_P85_SEL_WIDTH;                                   //[10:10]
        jl_uint32 cfg_dis_cpu_p85_sel:PMX_PIN_MUX_0_OFFSET_CFG_DIS_CPU_P85_SEL_WIDTH;                                     //[11:11]
        jl_uint32 cfg_disautoload_p85_sel:PMX_PIN_MUX_0_OFFSET_CFG_DISAUTOLOAD_P85_SEL_WIDTH;                             //[12:12]
        jl_uint32 cfg_smi_sel_1_sel:PMX_PIN_MUX_0_OFFSET_CFG_SMI_SEL_1_SEL_WIDTH;                                         //[13:13]
        jl_uint32 cfg_mid29_sel:PMX_PIN_MUX_0_OFFSET_CFG_MID29_SEL_WIDTH;                                                 //[14:14]
        jl_uint32 cfg_dis_cpu_p10_sel:PMX_PIN_MUX_0_OFFSET_CFG_DIS_CPU_P10_SEL_WIDTH;                                     //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_0_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_0_ENTRY_SIZE];
} PMX_PIN_MUX_0_t;

#define PMX_PIN_MUX_1                                                                          ((jl_uint32)0x00204004U)
#define PMX_PIN_MUX_1_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_1_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_1_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_1_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_1_OFFSET_CFG_EN_PHY_SEL                                                                         (0)
#define PMX_PIN_MUX_1_OFFSET_CFG_EN_PHY_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_SMI_SEL_0_SEL                                                                      (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_SMI_SEL_0_SEL_WIDTH                                                                (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_EN_EEE_P5_SEL                                                                      (2)
#define PMX_PIN_MUX_1_OFFSET_CFG_EN_EEE_P5_SEL_WIDTH                                                                (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_EEPROM_MOD_P10_SEL                                                                 (3)
#define PMX_PIN_MUX_1_OFFSET_CFG_EEPROM_MOD_P10_SEL_WIDTH                                                           (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P9_SEL                                                                       (4)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P9_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P9_SEL                                                                       (5)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P9_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P9_SEL                                                                       (6)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P9_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P8_SEL                                                                       (7)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P8_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P8_SEL                                                                       (8)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P8_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P8_SEL                                                                       (9)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P8_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P7_SEL                                                                      (10)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P7_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P7_SEL                                                                      (11)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P7_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P7_SEL                                                                      (12)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P7_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P6_SEL                                                                      (13)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P6_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P6_SEL                                                                      (14)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P6_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P6_SEL                                                                      (15)
#define PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P6_SEL_WIDTH                                                                 (1)
typedef union PMX_PIN_MUX_1_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_en_phy_sel:PMX_PIN_MUX_1_OFFSET_CFG_EN_PHY_SEL_WIDTH;                                               //[ 0: 0]
        jl_uint32 cfg_smi_sel_0_sel:PMX_PIN_MUX_1_OFFSET_CFG_SMI_SEL_0_SEL_WIDTH;                                         //[ 1: 1]
        jl_uint32 cfg_en_eee_p5_sel:PMX_PIN_MUX_1_OFFSET_CFG_EN_EEE_P5_SEL_WIDTH;                                         //[ 2: 2]
        jl_uint32 cfg_eeprom_mod_p10_sel:PMX_PIN_MUX_1_OFFSET_CFG_EEPROM_MOD_P10_SEL_WIDTH;                               //[ 3: 3]
        jl_uint32 cfg_pled0_p9_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P9_SEL_WIDTH;                                           //[ 4: 4]
        jl_uint32 cfg_pled1_p9_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P9_SEL_WIDTH;                                           //[ 5: 5]
        jl_uint32 cfg_pled2_p9_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P9_SEL_WIDTH;                                           //[ 6: 6]
        jl_uint32 cfg_pled2_p8_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P8_SEL_WIDTH;                                           //[ 7: 7]
        jl_uint32 cfg_pled1_p8_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P8_SEL_WIDTH;                                           //[ 8: 8]
        jl_uint32 cfg_pled0_p8_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P8_SEL_WIDTH;                                           //[ 9: 9]
        jl_uint32 cfg_pled2_p7_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P7_SEL_WIDTH;                                           //[10:10]
        jl_uint32 cfg_pled0_p7_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P7_SEL_WIDTH;                                           //[11:11]
        jl_uint32 cfg_pled1_p7_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P7_SEL_WIDTH;                                           //[12:12]
        jl_uint32 cfg_pled2_p6_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED2_P6_SEL_WIDTH;                                           //[13:13]
        jl_uint32 cfg_pled0_p6_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED0_P6_SEL_WIDTH;                                           //[14:14]
        jl_uint32 cfg_pled1_p6_sel:PMX_PIN_MUX_1_OFFSET_CFG_PLED1_P6_SEL_WIDTH;                                           //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_1_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_1_ENTRY_SIZE];
} PMX_PIN_MUX_1_t;

#define PMX_PIN_MUX_2                                                                          ((jl_uint32)0x00204008U)
#define PMX_PIN_MUX_2_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_2_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_2_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_2_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P5_SEL                                                                       (0)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P5_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P5_SEL                                                                       (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P5_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P5_SEL                                                                       (2)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P5_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P4_SEL                                                                       (3)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P4_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P4_SEL                                                                       (4)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P4_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P4_SEL                                                                       (5)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P4_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P3_SEL                                                                       (6)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P3_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P3_SEL                                                                       (7)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P3_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P3_SEL                                                                       (8)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P3_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P2_SEL                                                                       (9)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P2_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P2_SEL                                                                      (10)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P2_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P2_SEL                                                                      (11)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P2_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P1_SEL                                                                      (12)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P1_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P1_SEL                                                                      (13)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P1_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P1_SEL                                                                      (14)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P1_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P0_SEL                                                                      (15)
#define PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P0_SEL_WIDTH                                                                 (1)
typedef union PMX_PIN_MUX_2_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_pled2_p5_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P5_SEL_WIDTH;                                           //[ 0: 0]
        jl_uint32 cfg_pled0_p5_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P5_SEL_WIDTH;                                           //[ 1: 1]
        jl_uint32 cfg_pled1_p5_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P5_SEL_WIDTH;                                           //[ 2: 2]
        jl_uint32 cfg_pled2_p4_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P4_SEL_WIDTH;                                           //[ 3: 3]
        jl_uint32 cfg_pled0_p4_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P4_SEL_WIDTH;                                           //[ 4: 4]
        jl_uint32 cfg_pled1_p4_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P4_SEL_WIDTH;                                           //[ 5: 5]
        jl_uint32 cfg_pled1_p3_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P3_SEL_WIDTH;                                           //[ 6: 6]
        jl_uint32 cfg_pled2_p3_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P3_SEL_WIDTH;                                           //[ 7: 7]
        jl_uint32 cfg_pled0_p3_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P3_SEL_WIDTH;                                           //[ 8: 8]
        jl_uint32 cfg_pled2_p2_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P2_SEL_WIDTH;                                           //[ 9: 9]
        jl_uint32 cfg_pled0_p2_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P2_SEL_WIDTH;                                           //[10:10]
        jl_uint32 cfg_pled1_p2_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P2_SEL_WIDTH;                                           //[11:11]
        jl_uint32 cfg_pled2_p1_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P1_SEL_WIDTH;                                           //[12:12]
        jl_uint32 cfg_pled0_p1_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED0_P1_SEL_WIDTH;                                           //[13:13]
        jl_uint32 cfg_pled1_p1_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED1_P1_SEL_WIDTH;                                           //[14:14]
        jl_uint32 cfg_pled2_p0_sel:PMX_PIN_MUX_2_OFFSET_CFG_PLED2_P0_SEL_WIDTH;                                           //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_2_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_2_ENTRY_SIZE];
} PMX_PIN_MUX_2_t;

#define PMX_PIN_MUX_3                                                                          ((jl_uint32)0x0020400CU)
#define PMX_PIN_MUX_3_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_3_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_3_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_3_OFFSET_CFG_PLED1_P0_SEL                                                                       (0)
#define PMX_PIN_MUX_3_OFFSET_CFG_PLED1_P0_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_PLED0_P0_SEL                                                                       (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_PLED0_P0_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_SLED_GRPB_SEL                                                                      (2)
#define PMX_PIN_MUX_3_OFFSET_CFG_SLED_GRPB_SEL_WIDTH                                                                (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_SLED_GRPA_SEL                                                                      (3)
#define PMX_PIN_MUX_3_OFFSET_CFG_SLED_GRPA_SEL_WIDTH                                                                (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO0_SEL                                                                          (4)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO0_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO1_SEL                                                                          (5)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO1_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO2_SEL                                                                          (6)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO2_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO3_SEL                                                                          (7)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO3_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO4_SEL                                                                          (8)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO4_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO5_SEL                                                                          (9)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO5_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO6_SEL                                                                         (10)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO6_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO7_SEL                                                                         (11)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO7_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO8_SEL                                                                         (12)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO8_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO9_SEL                                                                         (13)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO9_SEL_WIDTH                                                                    (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO10_SEL                                                                        (14)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO10_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO11_SEL                                                                        (15)
#define PMX_PIN_MUX_3_OFFSET_CFG_GPIO11_SEL_WIDTH                                                                   (1)
typedef union PMX_PIN_MUX_3_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_pled1_p0_sel:PMX_PIN_MUX_3_OFFSET_CFG_PLED1_P0_SEL_WIDTH;                                           //[ 0: 0]
        jl_uint32 cfg_pled0_p0_sel:PMX_PIN_MUX_3_OFFSET_CFG_PLED0_P0_SEL_WIDTH;                                           //[ 1: 1]
        jl_uint32 cfg_sled_grpb_sel:PMX_PIN_MUX_3_OFFSET_CFG_SLED_GRPB_SEL_WIDTH;                                         //[ 2: 2]
        jl_uint32 cfg_sled_grpa_sel:PMX_PIN_MUX_3_OFFSET_CFG_SLED_GRPA_SEL_WIDTH;                                         //[ 3: 3]
        jl_uint32 cfg_gpio0_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO0_SEL_WIDTH;                                                 //[ 4: 4]
        jl_uint32 cfg_gpio1_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO1_SEL_WIDTH;                                                 //[ 5: 5]
        jl_uint32 cfg_gpio2_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO2_SEL_WIDTH;                                                 //[ 6: 6]
        jl_uint32 cfg_gpio3_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO3_SEL_WIDTH;                                                 //[ 7: 7]
        jl_uint32 cfg_gpio4_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO4_SEL_WIDTH;                                                 //[ 8: 8]
        jl_uint32 cfg_gpio5_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO5_SEL_WIDTH;                                                 //[ 9: 9]
        jl_uint32 cfg_gpio6_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO6_SEL_WIDTH;                                                 //[10:10]
        jl_uint32 cfg_gpio7_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO7_SEL_WIDTH;                                                 //[11:11]
        jl_uint32 cfg_gpio8_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO8_SEL_WIDTH;                                                 //[12:12]
        jl_uint32 cfg_gpio9_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO9_SEL_WIDTH;                                                 //[13:13]
        jl_uint32 cfg_gpio10_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO10_SEL_WIDTH;                                               //[14:14]
        jl_uint32 cfg_gpio11_sel:PMX_PIN_MUX_3_OFFSET_CFG_GPIO11_SEL_WIDTH;                                               //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_3_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_3_ENTRY_SIZE];
} PMX_PIN_MUX_3_t;

#define PMX_PIN_MUX_4                                                                          ((jl_uint32)0x00204010U)
#define PMX_PIN_MUX_4_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_4_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_4_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_4_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO12_SEL                                                                         (0)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO12_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO13_SEL                                                                         (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO13_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO14_SEL                                                                         (2)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO14_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO15_SEL                                                                         (3)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO15_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO16_SEL                                                                         (4)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO16_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO17_SEL                                                                         (5)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO17_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO18_SEL                                                                         (6)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO18_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO19_SEL                                                                         (7)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO19_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO20_SEL                                                                         (8)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO20_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO21_SEL                                                                         (9)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO21_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO22_SEL                                                                        (10)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO22_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO23_SEL                                                                        (11)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO23_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO24_SEL                                                                        (12)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO24_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO25_SEL                                                                        (13)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO25_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO26_SEL                                                                        (14)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO26_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO27_SEL                                                                        (15)
#define PMX_PIN_MUX_4_OFFSET_CFG_GPIO27_SEL_WIDTH                                                                   (1)
typedef union PMX_PIN_MUX_4_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_gpio12_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO12_SEL_WIDTH;                                               //[ 0: 0]
        jl_uint32 cfg_gpio13_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO13_SEL_WIDTH;                                               //[ 1: 1]
        jl_uint32 cfg_gpio14_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO14_SEL_WIDTH;                                               //[ 2: 2]
        jl_uint32 cfg_gpio15_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO15_SEL_WIDTH;                                               //[ 3: 3]
        jl_uint32 cfg_gpio16_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO16_SEL_WIDTH;                                               //[ 4: 4]
        jl_uint32 cfg_gpio17_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO17_SEL_WIDTH;                                               //[ 5: 5]
        jl_uint32 cfg_gpio18_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO18_SEL_WIDTH;                                               //[ 6: 6]
        jl_uint32 cfg_gpio19_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO19_SEL_WIDTH;                                               //[ 7: 7]
        jl_uint32 cfg_gpio20_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO20_SEL_WIDTH;                                               //[ 8: 8]
        jl_uint32 cfg_gpio21_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO21_SEL_WIDTH;                                               //[ 9: 9]
        jl_uint32 cfg_gpio22_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO22_SEL_WIDTH;                                               //[10:10]
        jl_uint32 cfg_gpio23_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO23_SEL_WIDTH;                                               //[11:11]
        jl_uint32 cfg_gpio24_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO24_SEL_WIDTH;                                               //[12:12]
        jl_uint32 cfg_gpio25_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO25_SEL_WIDTH;                                               //[13:13]
        jl_uint32 cfg_gpio26_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO26_SEL_WIDTH;                                               //[14:14]
        jl_uint32 cfg_gpio27_sel:PMX_PIN_MUX_4_OFFSET_CFG_GPIO27_SEL_WIDTH;                                               //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_4_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_4_ENTRY_SIZE];
} PMX_PIN_MUX_4_t;

#define PMX_PIN_MUX_5                                                                          ((jl_uint32)0x00204014U)
#define PMX_PIN_MUX_5_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_5_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_5_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_5_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_5_OFFSET_CFG_GPIO28_SEL                                                                         (0)
#define PMX_PIN_MUX_5_OFFSET_CFG_GPIO28_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_GPIO29_SEL                                                                         (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_GPIO29_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_GPIO30_SEL                                                                         (2)
#define PMX_PIN_MUX_5_OFFSET_CFG_GPIO30_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_GPIO31_SEL                                                                         (3)
#define PMX_PIN_MUX_5_OFFSET_CFG_GPIO31_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_I2C_MG2_SEL                                                                        (4)
#define PMX_PIN_MUX_5_OFFSET_CFG_I2C_MG2_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_INNER_I2C_SEL                                                                      (5)
#define PMX_PIN_MUX_5_OFFSET_CFG_INNER_I2C_SEL_WIDTH                                                                (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_I2C_MG1_SEL                                                                        (6)
#define PMX_PIN_MUX_5_OFFSET_CFG_I2C_MG1_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_I2C_MG0_SEL                                                                        (7)
#define PMX_PIN_MUX_5_OFFSET_CFG_I2C_MG0_SEL_WIDTH                                                                  (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_SPF_SEL_0                                                                          (8)
#define PMX_PIN_MUX_5_OFFSET_CFG_SPF_SEL_0_WIDTH                                                                    (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_SPF_SEL_1                                                                          (9)
#define PMX_PIN_MUX_5_OFFSET_CFG_SPF_SEL_1_WIDTH                                                                    (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_SPF_SEL_P5                                                                        (10)
#define PMX_PIN_MUX_5_OFFSET_CFG_SPF_SEL_P5_WIDTH                                                                   (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_UART_P5_MODE                                                                      (11)
#define PMX_PIN_MUX_5_OFFSET_CFG_UART_P5_MODE_WIDTH                                                                 (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_UART_P10_MODE                                                                     (12)
#define PMX_PIN_MUX_5_OFFSET_CFG_UART_P10_MODE_WIDTH                                                                (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_SPI_MODE                                                                          (13)
#define PMX_PIN_MUX_5_OFFSET_CFG_SPI_MODE_WIDTH                                                                     (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_SMI_MODE                                                                          (14)
#define PMX_PIN_MUX_5_OFFSET_CFG_SMI_MODE_WIDTH                                                                     (1)
#define PMX_PIN_MUX_5_OFFSET_CFG_I2C_M_MODE                                                                        (15)
#define PMX_PIN_MUX_5_OFFSET_CFG_I2C_M_MODE_WIDTH                                                                   (1)
typedef union PMX_PIN_MUX_5_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_gpio28_sel:PMX_PIN_MUX_5_OFFSET_CFG_GPIO28_SEL_WIDTH;                                               //[ 0: 0]
        jl_uint32 cfg_gpio29_sel:PMX_PIN_MUX_5_OFFSET_CFG_GPIO29_SEL_WIDTH;                                               //[ 1: 1]
        jl_uint32 cfg_gpio30_sel:PMX_PIN_MUX_5_OFFSET_CFG_GPIO30_SEL_WIDTH;                                               //[ 2: 2]
        jl_uint32 cfg_gpio31_sel:PMX_PIN_MUX_5_OFFSET_CFG_GPIO31_SEL_WIDTH;                                               //[ 3: 3]
        jl_uint32 cfg_i2c_mg2_sel:PMX_PIN_MUX_5_OFFSET_CFG_I2C_MG2_SEL_WIDTH;                                             //[ 4: 4]
        jl_uint32 cfg_inner_i2c_sel:PMX_PIN_MUX_5_OFFSET_CFG_INNER_I2C_SEL_WIDTH;                                         //[ 5: 5]
        jl_uint32 cfg_i2c_mg1_sel:PMX_PIN_MUX_5_OFFSET_CFG_I2C_MG1_SEL_WIDTH;                                             //[ 6: 6]
        jl_uint32 cfg_i2c_mg0_sel:PMX_PIN_MUX_5_OFFSET_CFG_I2C_MG0_SEL_WIDTH;                                             //[ 7: 7]
        jl_uint32 cfg_spf_sel_0:PMX_PIN_MUX_5_OFFSET_CFG_SPF_SEL_0_WIDTH;                                                 //[ 8: 8]
        jl_uint32 cfg_spf_sel_1:PMX_PIN_MUX_5_OFFSET_CFG_SPF_SEL_1_WIDTH;                                                 //[ 9: 9]
        jl_uint32 cfg_spf_sel_p5:PMX_PIN_MUX_5_OFFSET_CFG_SPF_SEL_P5_WIDTH;                                               //[10:10]
        jl_uint32 cfg_uart_p5_mode:PMX_PIN_MUX_5_OFFSET_CFG_UART_P5_MODE_WIDTH;                                           //[11:11]
        jl_uint32 cfg_uart_p10_mode:PMX_PIN_MUX_5_OFFSET_CFG_UART_P10_MODE_WIDTH;                                         //[12:12]
        jl_uint32 cfg_spi_mode:PMX_PIN_MUX_5_OFFSET_CFG_SPI_MODE_WIDTH;                                                   //[13:13]
        jl_uint32 cfg_smi_mode:PMX_PIN_MUX_5_OFFSET_CFG_SMI_MODE_WIDTH;                                                   //[14:14]
        jl_uint32 cfg_i2c_m_mode:PMX_PIN_MUX_5_OFFSET_CFG_I2C_M_MODE_WIDTH;                                               //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_5_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_5_ENTRY_SIZE];
} PMX_PIN_MUX_5_t;

#define PMX_PIN_MUX_6                                                                          ((jl_uint32)0x00204018U)
#define PMX_PIN_MUX_6_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_6_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_6_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_6_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_6_OFFSET_CFG_I2C_S_MODE                                                                         (0)
#define PMX_PIN_MUX_6_OFFSET_CFG_I2C_S_MODE_WIDTH                                                                   (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_SERI_LED_MODE                                                                      (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_SERI_LED_MODE_WIDTH                                                                (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_INTN_SEL                                                                           (2)
#define PMX_PIN_MUX_6_OFFSET_CFG_INTN_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_BUZZER_SEL                                                                         (3)
#define PMX_PIN_MUX_6_OFFSET_CFG_BUZZER_SEL_WIDTH                                                                   (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV0_SEL                                                                           (4)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV0_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV1_SEL                                                                           (5)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV1_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV2_SEL                                                                           (6)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV2_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV3_SEL                                                                           (7)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV3_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV4_SEL                                                                           (8)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV4_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV5_SEL                                                                           (9)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV5_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV6_SEL                                                                          (10)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV6_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV7_SEL                                                                          (11)
#define PMX_PIN_MUX_6_OFFSET_CFG_RSV7_SEL_WIDTH                                                                     (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_INTN_SEL                                                                      (12)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_INTN_SEL_WIDTH                                                                 (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_BUZZER_SEL                                                                    (13)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_BUZZER_SEL_WIDTH                                                               (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_GPIO0_SEL                                                                     (14)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_GPIO0_SEL_WIDTH                                                                (1)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_P9_LED0_SEL                                                                   (15)
#define PMX_PIN_MUX_6_OFFSET_CFG_DBG_P9_LED0_SEL_WIDTH                                                              (1)
typedef union PMX_PIN_MUX_6_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_i2c_s_mode:PMX_PIN_MUX_6_OFFSET_CFG_I2C_S_MODE_WIDTH;                                               //[ 0: 0]
        jl_uint32 cfg_seri_led_mode:PMX_PIN_MUX_6_OFFSET_CFG_SERI_LED_MODE_WIDTH;                                         //[ 1: 1]
        jl_uint32 cfg_intn_sel:PMX_PIN_MUX_6_OFFSET_CFG_INTN_SEL_WIDTH;                                                   //[ 2: 2]
        jl_uint32 cfg_buzzer_sel:PMX_PIN_MUX_6_OFFSET_CFG_BUZZER_SEL_WIDTH;                                               //[ 3: 3]
        jl_uint32 cfg_rsv0_sel:PMX_PIN_MUX_6_OFFSET_CFG_RSV0_SEL_WIDTH;                                                   //[ 4: 4]
        jl_uint32 cfg_rsv1_sel:PMX_PIN_MUX_6_OFFSET_CFG_RSV1_SEL_WIDTH;                                                   //[ 5: 5]
        jl_uint32 cfg_rsv2_sel:PMX_PIN_MUX_6_OFFSET_CFG_RSV2_SEL_WIDTH;                                                   //[ 6: 6]
        jl_uint32 cfg_rsv3_sel:PMX_PIN_MUX_6_OFFSET_CFG_RSV3_SEL_WIDTH;                                                   //[ 7: 7]
        jl_uint32 cfg_rsv4_sel:PMX_PIN_MUX_6_OFFSET_CFG_RSV4_SEL_WIDTH;                                                   //[ 8: 8]
        jl_uint32 cfg_rsv5_sel:PMX_PIN_MUX_6_OFFSET_CFG_RSV5_SEL_WIDTH;                                                   //[ 9: 9]
        jl_uint32 cfg_rsv6_sel:PMX_PIN_MUX_6_OFFSET_CFG_RSV6_SEL_WIDTH;                                                   //[10:10]
        jl_uint32 cfg_rsv7_sel:PMX_PIN_MUX_6_OFFSET_CFG_RSV7_SEL_WIDTH;                                                   //[11:11]
        jl_uint32 cfg_dbg_intn_sel:PMX_PIN_MUX_6_OFFSET_CFG_DBG_INTN_SEL_WIDTH;                                           //[12:12]
        jl_uint32 cfg_dbg_buzzer_sel:PMX_PIN_MUX_6_OFFSET_CFG_DBG_BUZZER_SEL_WIDTH;                                       //[13:13]
        jl_uint32 cfg_dbg_gpio0_sel:PMX_PIN_MUX_6_OFFSET_CFG_DBG_GPIO0_SEL_WIDTH;                                         //[14:14]
        jl_uint32 cfg_dbg_p9_led0_sel:PMX_PIN_MUX_6_OFFSET_CFG_DBG_P9_LED0_SEL_WIDTH;                                     //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_6_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_6_ENTRY_SIZE];
} PMX_PIN_MUX_6_t;

#define PMX_PIN_MUX_7                                                                          ((jl_uint32)0x0020401CU)
#define PMX_PIN_MUX_7_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_7_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_7_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_7_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_P9_LED1_SEL                                                                    (0)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_P9_LED1_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_P9_LED2_SEL                                                                    (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_P9_LED2_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_P8_LED2_SEL                                                                    (2)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_P8_LED2_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_CLK_SEL                                                                    (3)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_CLK_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_SI_D0_SEL                                                                  (4)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_SI_D0_SEL_WIDTH                                                            (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_SO_D1_SEL                                                                  (5)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_SO_D1_SEL_WIDTH                                                            (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_CSN_SEL                                                                    (6)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_CSN_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD3_SEL                                                               (7)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD3_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD2_SEL                                                               (8)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD2_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD1_SEL                                                               (9)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD1_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD0_SEL                                                              (10)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD0_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXCTL_SEL                                                             (11)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXCTL_SEL_WIDTH                                                        (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXCLK_SEL                                                             (12)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXCLK_SEL_WIDTH                                                        (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXCLK_SEL                                                             (13)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXCLK_SEL_WIDTH                                                        (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXCTL_SEL                                                             (14)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXCTL_SEL_WIDTH                                                        (1)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXD0_SEL                                                              (15)
#define PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXD0_SEL_WIDTH                                                         (1)
typedef union PMX_PIN_MUX_7_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_dbg_p9_led1_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_P9_LED1_SEL_WIDTH;                                     //[ 0: 0]
        jl_uint32 cfg_dbg_p9_led2_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_P9_LED2_SEL_WIDTH;                                     //[ 1: 1]
        jl_uint32 cfg_dbg_p8_led2_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_P8_LED2_SEL_WIDTH;                                     //[ 2: 2]
        jl_uint32 cfg_dbg_spf_clk_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_CLK_SEL_WIDTH;                                     //[ 3: 3]
        jl_uint32 cfg_dbg_spf_si_d0_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_SI_D0_SEL_WIDTH;                                 //[ 4: 4]
        jl_uint32 cfg_dbg_spf_so_d1_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_SO_D1_SEL_WIDTH;                                 //[ 5: 5]
        jl_uint32 cfg_dbg_spf_csn_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SPF_CSN_SEL_WIDTH;                                     //[ 6: 6]
        jl_uint32 cfg_dbg_sys1_rg_txd3_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD3_SEL_WIDTH;                           //[ 7: 7]
        jl_uint32 cfg_dbg_sys1_rg_txd2_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD2_SEL_WIDTH;                           //[ 8: 8]
        jl_uint32 cfg_dbg_sys1_rg_txd1_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD1_SEL_WIDTH;                           //[ 9: 9]
        jl_uint32 cfg_dbg_sys1_rg_txd0_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXD0_SEL_WIDTH;                           //[10:10]
        jl_uint32 cfg_dbg_sys1_rg_txctl_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXCTL_SEL_WIDTH;                         //[11:11]
        jl_uint32 cfg_dbg_sys1_rg_txclk_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_TXCLK_SEL_WIDTH;                         //[12:12]
        jl_uint32 cfg_dbg_sys1_rg_rxclk_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXCLK_SEL_WIDTH;                         //[13:13]
        jl_uint32 cfg_dbg_sys1_rg_rxctl_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXCTL_SEL_WIDTH;                         //[14:14]
        jl_uint32 cfg_dbg_sys1_rg_rxd0_sel:PMX_PIN_MUX_7_OFFSET_CFG_DBG_SYS1_RG_RXD0_SEL_WIDTH;                           //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_7_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_7_ENTRY_SIZE];
} PMX_PIN_MUX_7_t;

#define PMX_PIN_MUX_8                                                                          ((jl_uint32)0x00204020U)
#define PMX_PIN_MUX_8_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_8_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_8_OFFSET_RSVD0                                                                                 (16)
#define PMX_PIN_MUX_8_OFFSET_RSVD0_WIDTH                                                                           (16)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS1_RG_RXD1_SEL                                                               (0)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS1_RG_RXD1_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS1_RG_RXD2_SEL                                                               (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS1_RG_RXD2_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS1_RG_RXD3_SEL                                                               (2)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS1_RG_RXD3_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_P4_LED2_SEL                                                                    (3)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_P4_LED2_SEL_WIDTH                                                              (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD3_SEL                                                               (4)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD3_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD2_SEL                                                               (5)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD2_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD1_SEL                                                               (6)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD1_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD0_SEL                                                               (7)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD0_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXCTL_SEL                                                              (8)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXCTL_SEL_WIDTH                                                        (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXCLK_SEL                                                              (9)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXCLK_SEL_WIDTH                                                        (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXCLK_SEL                                                             (10)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXCLK_SEL_WIDTH                                                        (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXCTL_SEL                                                             (11)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXCTL_SEL_WIDTH                                                        (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD0_SEL                                                              (12)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD0_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD1_SEL                                                              (13)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD1_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD2_SEL                                                              (14)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD2_SEL_WIDTH                                                         (1)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD3_SEL                                                              (15)
#define PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD3_SEL_WIDTH                                                         (1)
typedef union PMX_PIN_MUX_8_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_dbg_sys1_rg_rxd1_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS1_RG_RXD1_SEL_WIDTH;                           //[ 0: 0]
        jl_uint32 cfg_dbg_sys1_rg_rxd2_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS1_RG_RXD2_SEL_WIDTH;                           //[ 1: 1]
        jl_uint32 cfg_dbg_sys1_rg_rxd3_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS1_RG_RXD3_SEL_WIDTH;                           //[ 2: 2]
        jl_uint32 cfg_dbg_p4_led2_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_P4_LED2_SEL_WIDTH;                                     //[ 3: 3]
        jl_uint32 cfg_dbg_sys0_rg_rxd3_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD3_SEL_WIDTH;                           //[ 4: 4]
        jl_uint32 cfg_dbg_sys0_rg_rxd2_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD2_SEL_WIDTH;                           //[ 5: 5]
        jl_uint32 cfg_dbg_sys0_rg_rxd1_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD1_SEL_WIDTH;                           //[ 6: 6]
        jl_uint32 cfg_dbg_sys0_rg_rxd0_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXD0_SEL_WIDTH;                           //[ 7: 7]
        jl_uint32 cfg_dbg_sys0_rg_rxctl_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXCTL_SEL_WIDTH;                         //[ 8: 8]
        jl_uint32 cfg_dbg_sys0_rg_rxclk_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_RXCLK_SEL_WIDTH;                         //[ 9: 9]
        jl_uint32 cfg_dbg_sys0_rg_txclk_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXCLK_SEL_WIDTH;                         //[10:10]
        jl_uint32 cfg_dbg_sys0_rg_txctl_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXCTL_SEL_WIDTH;                         //[11:11]
        jl_uint32 cfg_dbg_sys0_rg_txd0_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD0_SEL_WIDTH;                           //[12:12]
        jl_uint32 cfg_dbg_sys0_rg_txd1_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD1_SEL_WIDTH;                           //[13:13]
        jl_uint32 cfg_dbg_sys0_rg_txd2_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD2_SEL_WIDTH;                           //[14:14]
        jl_uint32 cfg_dbg_sys0_rg_txd3_sel:PMX_PIN_MUX_8_OFFSET_CFG_DBG_SYS0_RG_TXD3_SEL_WIDTH;                           //[15:15]
        jl_uint32 rsvd0:PMX_PIN_MUX_8_OFFSET_RSVD0_WIDTH;                                                                 //[31:16]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_8_ENTRY_SIZE];
} PMX_PIN_MUX_8_t;

#define PMX_PIN_MUX_9                                                                          ((jl_uint32)0x00204024U)
#define PMX_PIN_MUX_9_NUM                                                                      ((jl_uint32)0x00000001U)
#define PMX_PIN_MUX_9_ENTRY_SIZE                                                                                    (1)
#define PMX_PIN_MUX_9_OFFSET_RSVD0                                                                                 (11)
#define PMX_PIN_MUX_9_OFFSET_RSVD0_WIDTH                                                                           (21)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_LED_DA_SEL                                                                     (0)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_LED_DA_SEL_WIDTH                                                               (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_LED_CK_SEL                                                                     (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_LED_CK_SEL_WIDTH                                                               (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_SPI_CS_SEL                                                                     (2)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_SPI_CS_SEL_WIDTH                                                               (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_SCL_MDC_SPI_CK_SEL                                                             (3)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_SCL_MDC_SPI_CK_SEL_WIDTH                                                       (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_SDA_MDIO_SPI_SI_SEL                                                            (4)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_SDA_MDIO_SPI_SI_SEL_WIDTH                                                      (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_SPI_SO_SEL                                                                     (5)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_SPI_SO_SEL_WIDTH                                                               (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_INNER_SCL_SEL                                                                  (6)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_INNER_SCL_SEL_WIDTH                                                            (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_INNER_SDA_SEL                                                                  (7)
#define PMX_PIN_MUX_9_OFFSET_CFG_DBG_INNER_SDA_SEL_WIDTH                                                            (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_SWC_DEBUG_MODE                                                                     (8)
#define PMX_PIN_MUX_9_OFFSET_CFG_SWC_DEBUG_MODE_WIDTH                                                               (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_PHY_DEBUG_MODE                                                                     (9)
#define PMX_PIN_MUX_9_OFFSET_CFG_PHY_DEBUG_MODE_WIDTH                                                               (1)
#define PMX_PIN_MUX_9_OFFSET_CFG_JTAG_SEL                                                                          (10)
#define PMX_PIN_MUX_9_OFFSET_CFG_JTAG_SEL_WIDTH                                                                     (1)
typedef union PMX_PIN_MUX_9_u {
    struct __attribute__ ((packed)) {
        jl_uint32 cfg_dbg_led_da_sel:PMX_PIN_MUX_9_OFFSET_CFG_DBG_LED_DA_SEL_WIDTH;                                       //[ 0: 0]
        jl_uint32 cfg_dbg_led_ck_sel:PMX_PIN_MUX_9_OFFSET_CFG_DBG_LED_CK_SEL_WIDTH;                                       //[ 1: 1]
        jl_uint32 cfg_dbg_spi_cs_sel:PMX_PIN_MUX_9_OFFSET_CFG_DBG_SPI_CS_SEL_WIDTH;                                       //[ 2: 2]
        jl_uint32 cfg_dbg_scl_mdc_spi_ck_sel:PMX_PIN_MUX_9_OFFSET_CFG_DBG_SCL_MDC_SPI_CK_SEL_WIDTH;                       //[ 3: 3]
        jl_uint32 cfg_dbg_sda_mdio_spi_si_sel:PMX_PIN_MUX_9_OFFSET_CFG_DBG_SDA_MDIO_SPI_SI_SEL_WIDTH;                     //[ 4: 4]
        jl_uint32 cfg_dbg_spi_so_sel:PMX_PIN_MUX_9_OFFSET_CFG_DBG_SPI_SO_SEL_WIDTH;                                       //[ 5: 5]
        jl_uint32 cfg_dbg_inner_scl_sel:PMX_PIN_MUX_9_OFFSET_CFG_DBG_INNER_SCL_SEL_WIDTH;                                 //[ 6: 6]
        jl_uint32 cfg_dbg_inner_sda_sel:PMX_PIN_MUX_9_OFFSET_CFG_DBG_INNER_SDA_SEL_WIDTH;                                 //[ 7: 7]
        jl_uint32 cfg_swc_debug_mode:PMX_PIN_MUX_9_OFFSET_CFG_SWC_DEBUG_MODE_WIDTH;                                       //[ 8: 8]
        jl_uint32 cfg_phy_debug_mode:PMX_PIN_MUX_9_OFFSET_CFG_PHY_DEBUG_MODE_WIDTH;                                       //[ 9: 9]
        jl_uint32 cfg_jtag_sel:PMX_PIN_MUX_9_OFFSET_CFG_JTAG_SEL_WIDTH;                                                   //[10:10]
        jl_uint32 rsvd0:PMX_PIN_MUX_9_OFFSET_RSVD0_WIDTH;                                                                 //[31:11]
    } BF;
    jl_uint32 val[PMX_PIN_MUX_9_ENTRY_SIZE];
} PMX_PIN_MUX_9_t;

#endif /* __JL_REG_PMX_H__ */

