#
#Chip ID config
#
ifeq ($(CONFIG_CHIP_JL61XX), y)
CFLAGS += -DCONFIG_JL_CHIP_JL61XX
endif
ifeq ($(CONFIG_HW_VER_JL6105), y)
CFLAGS += -DCONFIG_JL_CHIP_ID_6105
endif
ifeq ($(CONFIG_HW_VER_JL6108), y)
CFLAGS += -DCONFIG_JL_CHIP_ID_6108
endif
ifeq ($(CONFIG_HW_VER_JL6110), y)
CFLAGS += -DCONFIG_JL_CHIP_ID_6110
endif
ifeq ($(CONFIG_HW_VER_JL61XX), y)
CFLAGS += -DCONFIG_JL_CHIP_ID_61XX
endif

#
#Thread safe config
#
ifeq ($(CONFIG_LIBSWITCH_MULTI_THREAD_SUPPORT), y)
CFLAGS += -DCONFIG_JL_API_MUTEX
endif

#
#Debug level config
#
ifneq ($(CONFIG_LIBSWITCH_DEBUG_LEVEL),)
CFLAGS += -DCONFIG_JL_DEBUG
CFLAGS += -DJL_DBG_LEVEL=${CONFIG_LIBSWITCH_DEBUG_LEVEL}
endif

#
#IO device types config
#
#
ifeq ($(CONFIG_IO_CPU), y)
CFLAGS += -DCONFIG_JL_IO_CPU
endif
ifeq ($(CONFIG_IO_SMI), y)
CFLAGS += -DCONFIG_JL_IO_SMI
endif
ifeq ($(CONFIG_IO_I2C), y)
CFLAGS += -DCONFIG_JL_IO_I2C
endif
ifeq ($(CONFIG_IO_SPI), y)
CFLAGS += -DCONFIG_JL_IO_SPI
endif
ifeq ($(CONFIG_SMI_OVER_MDIO), y)
CFLAGS += -DCONFIG_JL_SMI_OVER_MDIO
endif
ifeq ($(CONFIG_SMI_OVER_GPIO), y)
CFLAGS += -DCONFIG_JL_SMI_OVER_GPIO
endif
ifeq ($(CONFIG_SMI_OVER_SPI), y)
CFLAGS += -DCONFIG_JL_SMI_OVER_SPI
endif
ifeq ($(CONFIG_SMI_OVER_FTDI), y)
CFLAGS += -DCONFIG_JL_SMI_OVER_FTDI
endif
ifeq ($(CONFIG_SMI_OVER_HID), y)
CFLAGS += -DCONFIG_JL_SMI_OVER_HID
endif

#
#Debug dump register write config
#
ifeq ($(CONFIG_DUMP_REG_WRITE), y)
CFLAGS += -DCONFIG_JL_DUMP_REG_WRITE
endif


#
#Module config
#
CFLAGS += $(addprefix -DCONFIG_, $(call UC, $(patsubst %.c, %, $(notdir $(wildcard $(DRV_DIRS)/*.c)))))
